### ISSUE TITLE
Missing main front and main back in Table of contents of TEI composite to one HTML page

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/Stylesheets#101]
**Warning**. I tried to use composite text to merge two existing TEIs. Instead of group-ing text A and text B, I could have em-body-ed div type="part" n=A" and div type="part" n="B" just as well — and even better. If nobody else is interested in composite texts to HTML, this is very low priority. As far as _I_ am concerned, it is no priority at all. I was surprised by the results of my experience. I then made a test to see the extent of the problem with minimal TEI and minimal XSL to reduce the risk of errors in my real projects. This being done, I give this post (and other similar posts) purely as information, to make my test work available. Furthermore the main problem may be a weakness in the concept of elements text and group (what about the title of a text?) and these elements are maybe not worth an investment in stylesheet work until some deeper questions are clarified.

The TEI is http://www.d-meeus.be/linux/sandbox/sandbox.xml, the stylesheet is http://www.d-meeus.be/linux/sandbox/splitLevel-1/sandbox-1.xsl and the result http://www.d-meeus.be/linux/sandbox/splitLevel-1/index.html.

The two texts children of group have a poor presence in the table of contents as simply 1 and 2 without a link. The main front matter and the main back matter are completely missing from the table of contents. (A hand-made table of contents is to be found in the Foreword div of the main front matter.)

_By the way_, back matter may be appendixes, but some Afterword just as well, not to be called appendix. I am not sure that prefixing all back matter as Appendix N by default is appropriate (composite or not). This test shows three Appendix A in one HTML page. After all, divs in front have no prefix.

**Comment by martindholmes** [comment]
With @ebeshero testing this today using the sandbox file, and using bin/teitohtml5, the problem no longer appears; all of the items appear correctly and linked in the TOC.
