### ISSUE TITLE
Missing text pages of TEI composite to HTML pages split at div level under text

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/Stylesheets#103]
The TEI is http://www.d-meeus.be/linux/sandbox/sandbox.xml, the stylesheet is http://www.d-meeus.be/linux/sandbox/splitLevel1/sandbox1.xsl and the result http://www.d-meeus.be/linux/sandbox/splitLevel1/index.html. The pages actually produced are listed in the text file http://www.d-meeus.be/linux/sandbox/splitLevel1/foldercontents.

The pages for the divs first children of the texts chidren of group are produced, but the pages for these texts are missing.

In the table of contents and elsewhere, links to sub-divs are not to anchors in parent divs, but to anchors in the non existing text pages. (This was my fist surprise in my real world project.)

Pages are produced for a div in the main front (Foreword) and for a div in the main back, but these pages are missing in the Table of contents.

**Comment by martindholmes** [comment]
@Dominique-M We (@sydb and me) have been looking at your three similar tickets here (we apologise for taking so long to get to this), and we're a bit puzzled because the problems you're reporting seem to relate to the presence of `<group>` in a TEI file, but test file you link to from all three tickets doesn't have a `<group>` element. Did you link to the wrong test file?

**Comment by Dominique-M** [comment]
Well, I forgot about this. Of course, with some research I could find 
back what I meant.

In the meanwhile, about the test file: all my TEI projects are 
subfolders of a TEIworkbench folder (so that ../ or ../../ always point 
to the same). Among them, sandbox folder for some tests, with the very 
little specific filenames sandbox.xml and sandbox.xsl. I suppose I then 
placed a symlink to this in my website. Between the time I did, and the 
time you read it, I could have been busy with other tests. This explains 
a TEI file without group (now).

In a subfolder called old stuff, I find a testingthings (élément 
group).xml with timestamp sam 28 sept. 2013 18∶56∶20 CEST, which is 
quite older than the 2015 ticket. I add the file. Then I find two of 
2015: testingthings.xml of 19 april and sandbox (composite).xml of 21 
april. I rediscover the last paragraph of the latter: a tribute to 
Sebastian.

I am not a digital humanist, but an amateur, using TEI only as the best 
way that I know of, to populate my personal website with HTML pages. 
Anyway, because I like the TEI, I am always happy to help if I can. 
Please ask again for missing links, proper or figuratively.

Le 15/04/19 à 20:12, Martin Holmes a écrit :

**Comment by martindholmes** [comment]
@Dominique-M @ebeshero and I believe this is very similar (identical?) to issues #101 and #102; we've left #102 open with a question to you, and we're closing the others.
