### ISSUE TITLE
Incorrect whitespace normalization, necessary whitespace lost

### ISSUE THREAD

**Issue by jure** [TEIC/Stylesheets#106]
From the Docx to TEI conversion, I get something similar to this TEI element:

```
         <p>
            All<hi rend="bold"> mutants. </hi> must live. 
         </p>
```

The output of TEI to xHTML conversion for this is (notice the missing single space before 'mutants'):

```
      <p>All<span style="font-weight:bold">mutants. </span> must live.
      </p>
```

This is because the whitespace normalization code strips it out:
https://github.com/TEIC/Stylesheets/blob/master/common/functions.xsl#L523

I know this is very critical behaviour, so I'm wondering if there is something trivial I'm missing, or if the algorithm needs to be adapted.

**Comment by jure** [comment]
I'm testing something like this, and it seems to be working well:

```
<!-- but if its in a run on inline objects with the same name (like a sequence of <hi>), or it follows a text node, then the space needs keeping -->
<xsl:when test="(tei:isInline(parent::*) and (parent::*/preceding-sibling::node()[1][name()=$context] or parent::*/preceding-sibling::node()[1][name()='']))">
  <xsl:call-template name="space"/>
</xsl:when>
```

**Comment by sebastianrahtz** [comment]
Ah. Now you are talking about the exact meaning of those damned rules. Need to think about that

**Comment by jure** [comment]
I realize how tricky those are, for sure. I can only tell you practically, from my test set of Docx to xHTML, that it corrected for a lot of missing whitespace, without a single issue so far.

**Comment by sebastianrahtz** [comment]
are the Stylesheets tests passing?

On 23 April 2015 at 07:32, Jure Triglav <notifications@github.com> wrote:

> I realize how tricky those are, for sure. I can only tell you practically,
> from my test set of Docx to xHTML, that it corrected for a lot of missing
> whitespace, without a single issue so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/106#issuecomment-95460111>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by jure** [comment]
That's a good question! Unfortunately I have to say I've never run them so
far. Can you point me in the right direction in terms of how the tests are
run?

**Comment by sebastianrahtz** [comment]
A "make" in the tests directory should do it. If you see any changes, we need to consider very carefully.

**Comment by jure** [comment]
Running make reveals some issues, e.g.:

```
624c624
<       <p><span class="said">‘Let me hear another sound from <em>you</em>,’</span> said Scrooge, <span class="said">‘ and you'll keep your Christmas by losing your situation. You're quite a powerful speaker, sir,’</span> he added, turning to his nephew. <span class="said">‘I wonder you don't go into Parliament.’</span><span class="pagebreak" id="index.xml-pb-d29e1064">[Page 10]</span></p>
---
>       <p><span class="said">‘Let me hear another sound from <em>you</em>,’</span> said Scrooge, <span class="said">‘and you'll keep your Christmas by losing your situation. You're quite a powerful speaker, sir,’</span> he added, turning to his nephew. <span class="said">‘I wonder you don't go into Parliament.’</span><span class="pagebreak" id="index.xml-pb-d29e1064">[Page 10]</span></p>
662c662
<       <p><span class="said">‘They are. Still,’</span> returned the gentleman, <span class="said">‘ I wish I could say they were not.’</span></p>
---
>       <p><span class="said">‘They are. Still,’</span> returned the gentleman, <span class="said">‘I wish I could say they were not.’</span></p>
```

There must be a middle way where we're both happy.

Would you not agree that the text version of this: 

```
         <p>
            All<hi rend="bold"> mutants</hi> must live. 
         </p>
```

should be `All mutants must live.`?

Purely as an observation, Nokogiri does this:

Nokogiri::XML("<p>All<hi> mutants</hi> must live.</p>").text
=> "All mutants must live."

It's going to be tricky, but I believe it's possible to satisfy all current test cases plus this one.

**Comment by sebastianrahtz** [comment]
Have you put in your fix code? Happy to go over these cases in derail once I can reproduce.

Carved in stone on my iPad

**Comment by jure** [comment]
Working on this today, I'll let you know what I find out. The code that failed the tests (and fixed my issue) is in this branch: https://github.com/Tahi-project/Stylesheets/tree/sciencejournal

**Comment by jure** [comment]
OK, so I've dug into this a bit more (http://wiki.tei-c.org/index.php/XML_Whitespace http://usingxml.com/Basics/XmlSpace) and I have a few questions.

1. In the case of this XML input (from the test cases), what would you expect the HTML output to be?

```
<p><said>They are.  Still,</said> returned the gentleman, <said> I wish I could say they were not.</said></p>
```

Right now, without the fix, the stylesheets produce:

```
<p><span class="said">‘They are. Still,’</span> returned the gentleman, <span class="said">‘I wish I could say they were not.’</span></p>
```

Which means that the initial space before "I wish I could" in the `said` element gets truncated, which I believe is the wrong thing to do. To be clear, this is a correctly functioning algorithm according to TEI's rules, and TEI says: `An encoder should assume that an element that includes nothing but text will get trimmed.` So that's all good and well, but it still seems strange to me. What do you think?

Nokogiri says that the text version of this XML includes the space:

```
Nokogiri::XML("<p><said>They are.  Still,</said> returned the gentleman, <said> I wish I could say they were not.</said></p>").text
=> "They are.  Still, returned the gentleman,  I wish I could say they were not."
```

And according to the XML spec, this is significant whitespace, given that the TEI DTD has `said` element as containing CDATA only. So I'm confused why this convention of trimming whitespace in this location is followed. Happy to read up on it to really understand what's going on.

**Comment by jure** [comment]
After reflecting briefly, I guess the original issue that I'm facing is that while the Docx element has a `xml:space="preserve"`:

```
      <w:r w:rsidRPr="001A62B7">
        <w:rPr>
          <w:rFonts w:cs="Arial"/>
          <w:i/>
          <w:sz w:val="24"/>
          <w:szCs w:val="24"/>
        </w:rPr>
        <w:t xml:space="preserve"> mof</w:t>
      </w:r>
```

The resulting TEI has no such attribute, which doesn't agree with this statement from TEI: `it must be ensured that downstream processors actually honor xml:space='preserve'`. Maybe that's where the actual flaw is, as when this attribute is present:

```
         <p>
            All<hi rend="bold" xml:space="preserve"> mutants. </hi> must live. 
         </p>
```

the conversion to HTML is of course correct.

**Comment by jure** [comment]
OK, this seems to have done the trick: https://github.com/Tahi-project/Stylesheets/commit/31fdbbf2163e8fd9098c84d9d148f10d5f6ed150

The xml:space attribute is now preserved on elements where it exists in the Docx. Any thoughts?

**Comment by jure** [comment]
I believe this is the correct solution. `xml:space=preserve` should be carried forward as long as is possible. I'd be happy to cherry pick some of these commits and make a pull request for master here.

**Comment by sebastianrahtz** [comment]
hmm. i am very reluctant indeed to contradict the TEI wiki's statement "An encoder should assume that an element that includes nothing but text will get trimmed", because it took such a long time to reach that agreement. I am not sure why you think it contradicts the XML space? I think its agreed that the spec is agnostic on the subject. So _a priori_, I'd say the mutants lose their space (sorry folks).  Which means that I agree the problem is at the docx to TEI end. Staring at it now.

**Comment by jure** [comment]
Hm, your solution is different and more specific, i.e. deals only with `hi` elements. What's the reason for that?

I solved it by preserving the `xml:space=preserve` in TEI if the Docx has that attribute (https://github.com/Tahi-project/Stylesheets/commit/31fdbbf2163e8fd9098c84d9d148f10d5f6ed150):

```
	    <xsl:if test="w:t[@xml:space='preserve']">
	  		<xsl:attribute name="xml:space">preserve</xsl:attribute>
	    </xsl:if>
```

To my untrained eye, that seems more bullet proof and less involved. What's the reason you went with your solution?

**Comment by sebastianrahtz** [comment]
I need to generalize it more, but not as general as yours.

if you meet `<r><t xml:space="preserve">hello </t><t>you</t></r>` you dont need to keep
the @xml:space, because the two <t> are combined.

**Comment by jure** [comment]
What is the harm though? How naive am I in thinking that all xml:space
preserves in Docx should be, well, preserved. What is the downside?

**Comment by sebastianrahtz** [comment]
if we had a 1:1 mapping from `<w:t>` (which has the attribute) to a TEI
element, I'd agree. But since we take it upon ourselves to map from `<w:r>`
to a TEI element, and ignore the `<w:t>` structure, it would not be honest
to impose @xml:space on elements where we have already destroyed the
sub-components.

I think I see a more general solution, however.

On 6 May 2015 at 05:24, Jure Triglav <notifications@github.com> wrote:

> What is the harm though? How naive am I in thinking that all xml:space
> preserves in Docx should be, well, preserved. What is the downside?
> On tor., 5. maj 2015 at 23.44 Sebastian Rahtz <notifications@github.com>
> wrote:
>
> > I need to generalize it more, but not as general as yours.
> >
> > if you meet <r><t xml:space="preserve">hello </t><t>you</t></r> you dont
> > need to keep
> > the @xml <https://github.com/xml>:space, because the two are combined.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/TEIC/Stylesheets/issues/106#issuecomment-99232642>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/106#issuecomment-99317607>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by sebastianrahtz** [comment]
I have put in new code which tries to identify any (non-mixed) element which has white space at start of finish, and adds an xml:space attribute accordingly. I could add another test of "contains(.,'  ')" I suppose,
to catch deliberately spaced-out stuff? I incline more to the view that the docx to TEI is cleaning up typically rubbish word processor docs. Does it give the right results for sciencejournal now?

**Comment by Conal-Tuohy** [comment]
I have a client who is using deliberately spaced out text in the middle of paragraphs, in Word. It's not just start and end at issue.

**Comment by sebastianrahtz** [comment]
I think I have put in enough code to deal with this now. whitespace isn't thrown away from the original, but the @xml:space="preserve" is only added if you specify the parameter $preserveSpace to  be true, or if its an inline element with white space at start or end.

**Comment by jure** [comment]
Thanks for your effort, Sebastian. I'm checking the results right now!

**Comment by jure** [comment]
Forgot to phone you back on this, we're all good now!
