### ISSUE TITLE
teitorelaxng ignores source date when adding documentary comment

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#107]
A schema generated from an ODD by teitorelaxng includes a comment at the start like this
 

This comment is produced even if the schemaSpec being processed requests a different version via the @source attribute. The specified version (e.g. tei:2.1.0) *is* used, but the version number in the comment is wrong. This is potentially confusing.

**Comment by sebastianrahtz** [comment]
This shouldn't happen. The code in odd2odd.xsl (template
name="odd2odd-getversion") is checking for this circumstance.

can you see whats wrong with the code?

Sebastian

**Comment by lb42** [comment]
Have you tried it? Maybe it's my Oxygen set up which is confused.

**Comment by sebastianrahtz** [comment]
ah. spotted it. two typos in the XSLT, now fixed.
