### ISSUE TITLE
An attribute node (xml:id) cannot be created after a child of the containing element.

### ISSUE THREAD

**Issue by jure** [TEIC/Stylesheets#111]
When converting certain Docx documents to TEI (using the `sciencejournal` profile), I get the following error:

```
XTDE0410: An attribute node (xml:id) cannot be created after a child of the containing element. Most recent element start tag was output at line 171 of module from.xsl
```

Upon debugging, this is found to be the offending code (the `<xsl:copy-of select="@xml:id"/>`):

```
   <xsl:template match="tei:anchor" mode="pass3">
     <xsl:choose>
       <xsl:when test="not(preceding-sibling::text()) and not(parent::*/@xml:id)">
	 <xsl:copy-of select="@xml:id"/>
       </xsl:when>
       <xsl:otherwise>
	 <xsl:copy-of select="."/>
       </xsl:otherwise>
     </xsl:choose>
   </xsl:template>
```

When the error occurs, this is the TEI output:

```
           <div>
               <head>
                  <hi rend="italic" style="font-size:18pt">Methods</hi>
```

If I understand this correctly, it's trying to add the `id` attribute to the `head` element, which already has children. 

Any thoughts on this one? I can just add a check if the containing element has no children, but I was wondering about the intended behavior.

**Comment by sebastianrahtz** [comment]
oh, nasty. its trying to use an ID wherever it can, rather than create an anchor

if you have a test file, it would be useful.

I suspect the fix should be preceding-sibling::node() instead of text()

**Comment by sebastianrahtz** [comment]
I have put in a fix for this

**Comment by jure** [comment]
Works great! I've merged it into my fork and tested to confirm that it works as intended.
