### ISSUE TITLE
Position of table of contents in TEI to HTML5 and other musings

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/Stylesheets#113]
In the html:body
  div stdheader
  div tei_front
    section…
  table of contents (heading, three lists, no container)
  div teo_body
    section…
  div tei_back
    section…
  div stdfooter

If the contents of TEI:front are to appear in the table of contents, the table of contents coming after some contents (and mentioning contents above, already passed, past) looks queer. It should come between div stdheader and div tei_front.
A container would satisfy my sense of aesthetics (logic? TEI habit?) but also allow some CSS.
(I would not decide a priori that any back div is to be called Appendix A… if the author choose his own TEI:heading.)

http://www.d-meeus.be/linux/sandbox/sandbox.xml
transformed with /usr/share/xml/tei/stylesheet/html5/html5.xsl
gives http://www.d-meeus.be/linux/sandbox/index.html

**Comment by adunning** [comment]
I would suggesting putting it within a `<nav id="TOC">`.

**Comment by peterstadler** [comment]
You can provide a dedicated place for the TOC in your TEI file with 
```XML
<divGen type="toc"/>
```

**Comment by Dominique-M** [comment]
Peter Stadler a écrit le 22/09/15 09:55 :
>
> You can provide a dedicated place for the TOC in your TEI file with
>
> <divGen  type="toc"/>
Thanks. I was very happy to be able to use |<divGen type="index"/>| 
since a few years. I am sorry that I overlooked the possibility of 
|type="toc"|.
