### ISSUE TITLE
Newest EPUBCheck 4.0.1 validator reports problem with TEI created EPUB 3 

### ISSUE THREAD

**Issue by raducoravu** [TEIC/Stylesheets#115]
When validating an EPUB 3 book created from TEI sources the validator complains with two warnings like:

```
   EpubCheck4.0.0
   CSS selector specifies absolute position.
   zip:file:/D:/projects/eXml/test/ant/EXM-21295/out/TEI-P5.epub!/OPS/stylesheet.css
   line: 66, column: 4
```

I think that the explanation for this is here:

http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-css-2.1

So what are those absolute positions in the CSS user for?

**Comment by martindholmes** [comment]
I ran epubcheck 4 against the Guidelines epub and got over 1300 warnings, but not this error, so I think we have some work to do here. :-)

**Comment by martindholmes** [comment]
The code is attempting to create a full-page image for a facsimile. This happens in epub/tei-to-epub.xsl and epub3/tei-to-epub3.xsl, and it's based on a class of "fullpage" which is set in html/html_textstructure.xsl.

**Comment by martindholmes** [comment]
This ant file will get the validator and run it against the test.epub created by the Stylesheets test.

1. Save the ant file as [Stylesheets]/temp/build.xml

2. cd to [Stylesheets]/Test and run `make test-epub`

3. cd to [Stylesheets]/temp and run `ant`

4. See warnings.

~~~~~
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="epubcheck" xmlns:if="ant:if"
  xmlns:unless="ant:unless" default="validateEpub">

  <description>
    Ant file for testing epubcheck 4.
  </description>
  
  <property name="epubcheckDist" value="https://github.com/IDPF/epubcheck/releases/download/v4.0.2/epubcheck-4.0.2.zip"/>
  
  
    <target name="getEpubCheck">
      <description>
        TARGET getEpubCheck
        This checks for the presence of the epubcheck.jar  and associated files in the ${basedir}
        directory, and if it's not there, downloads a copy.
      </description>
      <echo message="${echo.separator}"/>
      <echo message="Checking for presence of epubcheck.jar..."/>
      <property name="getEpubCheckAlreadyExecuted" value="true" />
      <available property="epubCheckAvailable" file="${basedir}/epubcheck-4.0.2/epubcheck.jar"/>
      <echo unless:true="${epubCheckAvailable}" message="Downloading epubcheck.jar to enable validation of ePubs..."/>
      <get unless:true="${epubCheckAvailable}" src="${epubcheckDist}" 
        dest="${basedir}/" verbose="on" retries="3" usetimestamp="true"/>
      <unzip unless:true="${epubCheckAvailable}" src="${basedir}/epubcheck-4.0.2.zip" dest="${basedir}/" failonemptyarchive="true"/>
      <delete unless:true="${epubCheckAvailable}" file="${basedir}/epubcheck-4.0.2.zip"/>
    </target>
  
  
  <target name="validateEpub" depends="getEpubCheck">
    <description>
      TARGET validateEpub
      This target validates the complete collection of XHTML5 documents 
      comprising the output website, using the VNU validator (the same validator used by 
      the W3C's online validation service).
    </description>
    <echo message="${echo.separator}"/>
    <echo message="Validating an epub using the ePubCheck 4.0.2 validator."/>
    <java jar="${basedir}/epubcheck-4.0.2/epubcheck.jar" failonerror="false" fork="true">
      <arg value="../Test/test.epub"/>
    </java>
  </target>

</project>
~~~~~

**Comment by martindholmes** [comment]
Stylesheets group thinks the problem lines should be commented out in the CSS, with a comment explaining why, when generating the ePub. Quick and simple solution that should just work.

**Comment by martindholmes** [comment]
In commit c0a5410c..171f74f3 and the preceding one, I've commented out these rules. If nothing breaks, we should be able to close the ticket, although we obviously have to revisit the warnings from the TEI Guidelines epub output.

**Comment by martindholmes** [comment]
Only warnings remain; they all seem to be for "CSS selector specifies absolute position." Closing this for now.
