### ISSUE TITLE
Processing of <egXML> elides namespace nodes

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#118]
Hugh points out that if you put a namespace prefix declaration on the first child element of an `<egXML>` element, the resulting output in the Guidelines prose does not show it. This means you have to deal with namespaces by explaining them in the accompanying prose (see `<xenoData>` examples). If this is fixable (it's a notoriously difficult area), and there will be potentially unwanted side-effects) we should fix it, and then refine the prose for the `<xenoData>` examples.

**Comment by lb42** [comment]
As formulated above, this is simply not true. You can put namespace declarations, with or without a prefix, on the child elements of an egXML to your heart's content and they will appear in the output. What you *can't* do is declare the namespace   **http://www.tei-c.org/ns/Examples** on a child element of an egXML, and expect to see it appear in the output. The declaration for that element puts both it and (by default) its children in that namespace so your attempt to state this again is redundant.  A (possibly unexpected) consequence of this is that another thing you *can't* do is nest one egXML inside another.

**Comment by martindholmes** [comment]
@lb42 I think you're missing the point. I think there needs to be special-case processing for a nested `<egXML>` which explicitly adds the xmlns declaration in the output, because we know that it's going to appear as an example, and it needs that declaration to avoid confusing the reader.

**Comment by lb42** [comment]
I don't think I was missing the point: I was addressing what this ticket actually says, not what you are now saying you meant! Don't you think special case processing of this kind is  a bit dubious ?  though I note that we are apparently doing something like this already  for the TEI element : an egXML containing a TEI with a namespace will cause an error, whereas one without one will get one added in the formatting. Maybe that's all you want here?

**Comment by martindholmes** [comment]
The element is actually in the examples namespace; when we output it as an example without that declaration, we're getting it wrong. If you take an element out of a context in which it inherits a namespace from an ancestor, the namespace needs to be carried with it, and should show up if it's serialized as the root of its own fragment or document. We'll probably have to special-case this because the code we have is not expecting to have to do it, but it's definitely not dubious.

**Comment by ebeshero** [comment]
@martindholmes and I think @sydb may have resolved this with #361 but we are not sure the fix was fully tested.

**Comment by martindholmes** [comment]
@sydb and I tested this today, and the basic issue appears to be solved, so we're going to close the ticket. The additional issue of special-case processing for the egXML namespace itself (i.e. nested egXML elements to exemplify the use of egXML) is a complicated edge-case and probably not worth addressing.
