### ISSUE TITLE
teitoschematron doesn't work

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#119]
I've been puzzled for a while over why the teitoschematron script doesn't output any Schematron, even when there's loads of it in an ODD. Today I went digging and learned that it depends on an "odd2odd" macro defined in common/teianttasks.xml. You'd think that would do what it sounds like it does: take your ODD and inline all of the references, but what it actually does is do that and then transform the thing to TEI Lite. The XSLT that attempts to extract Schematron rules is baffled by TEI Lite. I'm about to commit a fix that renames the macro to "odd2lite", adds an "odd2odd" macro that just expands your ODD, and changes all the Ant scripts except the schematron one to call "odd2lite".

**Comment by lb42** [comment]
Hang on a bit -- odd2odd is used all over the place to process ODDs to HTML, PDF etc. Are you sure this is a good idea?

**Comment by hcayless** [comment]
I only changed the macro name—to "odd2lite", which does what it says on the tin, and then changed the build scripts that call it. The odd2odd.xsl is unchanged. The tests all pass :-).

**Comment by lb42** [comment]
OK, I'll stop panicking then.
