### ISSUE TITLE
Stylesheets do not display English note when there is no translation

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#123]
If there is no translation of a note (remark) in a specific language, the Stylesheets rendering displays nothing. It should actually display the English note instead, because that's much better than nothing. Compare:

http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-cb.html
versus
http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-cb.html

The first has a French note; there is no note in the German because it was never  translated, but in this case the English note should be used.

**Comment by martindholmes** [comment]
@sydb , @jamescummings and me think the problem is in this template:

https://github.com/TEIC/Stylesheets/blob/dev/common/common_tagdocs.xsl#L2394

which has a lot of code inherited from workarounds required for XSLT 1.0.

**Comment by hcayless** [comment]
It was, sort of, and we fixed it.
