### ISSUE TITLE
model.contentPart not linked to from ref-content.html tagdoc

### ISSUE THREAD

**Issue by jamescummings** [TEIC/Stylesheets#128]
If you look at the declaration at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-content.html you'll see that model.contentPart is not a link to http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.contentPart.html which it should be. 

Clearly something is borked in the the creating of links in the generation of the tagdoc HTML.

**Comment by lb42** [comment]
It also says May contain ANY which looks doubtful

**Comment by lb42** [comment]
Closing, as fixed in version 2.9.1
