### ISSUE TITLE
Composite datatypes not properly included

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#130]
@martindholmes noticed that in one of his ODDs, att.global.responsibility was defining it's `@cert` as empty. Some investigation shows that this is a bug in the ODD expansion XSLT, which only pulls in references when they're a direct child of `<datatype>`, meaning composite datatypes, like a choice between a value list or a numeric `@cert` won't get properly resolved. 

Note that everything works if the macros are otherwise included in the expansion.

**Comment by hcayless** [comment]
@lb42 reports that this sort of composite datatype is illegal in Pure ODD, so we should probably not compose datatypes in this way, Leaving this open to make sure it's properly reverted when we switch to Pure ODD.

**Comment by martindholmes** [comment]
This seems a sad regression to me. But if a datatype can be constrained by a regex, then a "single" datatype definition can surely handle the requirement here for two options in this datatype.

But I would suggest that Pure ODD is impoverished in this respect, and should be enhanced to allow this.

**Comment by martindholmes** [comment]
@ebeshero and I note that since Pure ODD is not supposed to support this, then we can just close the ticket.
