### ISSUE TITLE
teitopdf teiantasks.xml problem

### ISSUE THREAD

**Issue by welblaud** [TEIC/Stylesheets#131]
I am trying to export a short test file from TEI xml to pdf on an Ubuntu server. I got this:

    $ ../git/Stylesheets/bin/teitopdf sport_pohyb_jh.xml
    Convert sport_pohyb_jh.xml to /home/honza/development_testing/sport_pohyb_jh.xml.pdf (tei to pdf) using profile default
    Warning: XML resolver not found; external catalogs will be ignored
    Warning: XML resolver not found; external catalogs will be ignored
    [echo] Running XeLaTeX on /home/honza/development_testing/sport_pohyb_jh.xml.tex in /home/honza/development_testing
    
    BUILD FAILED
    /home/honza/git/Stylesheets/pdf/build-to.xml:56: The following error occurred while executing this line:
    /home/honza/git/Stylesheets/common/teianttasks.xml:211: exec returned: 1
    
     Total time: 9 seconds

**Comment by smjwsk-onb** [comment]
most likely xelatex is (assuming it is installed) running into an error 
condition due some possibly missing font, or any number of other errors. 
Is there any useful information in 
/home/honza/development_testing/sport_pohyb_jh.xml.log? This is where 
xetex will most likely log possible errors. Does xelatex run fine when 
run manually on sport_pohyb_jh.xml.tex?

Am 19.11.2015 um 15:06 schrieb Honza Hejzl:
>
> I am trying to export a short test file from TEI xml to pdf on an 
> Ubuntu server. I got this:
>
> |$ ../git/Stylesheets/bin/teitopdf sport_pohyb_jh.xml Convert 
> sport_pohyb_jh.xml to 
> /home/honza/development_testing/sport_pohyb_jh.xml.pdf (tei to pdf) 
> using profile default Warning: XML resolver not found; external 
> catalogs will be ignored Warning: XML resolver not found; external 
> catalogs will be ignored [echo] Running XeLaTeX on 
> /home/honza/development_testing/sport_pohyb_jh.xml.tex in 
> /home/honza/development_testing BUILD FAILED 
> /home/honza/git/Stylesheets/pdf/build-to.xml:56: The following error 
> occurred while executing this line: 
> /home/honza/git/Stylesheets/common/teianttasks.xml:211: exec returned: 
> 1 Total time: 9 seconds |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TEIC/Stylesheets/issues/131>.
>


-- 
Mag. Stefan Majewski
Projektmanager
Abteilung Forschung und Entwicklung
Österreichische Nationalbibliothek

Josefsplatz 1, 1015 Wien
Tel.: (+43 1) 534 10-434
E-Mail: stefan.majewski@onb.ac.at
Skype: stefan.majewski.onb.ac.at

**Comment by welblaud** [comment]
Thank you! No, unfortunately it logs:

$ xelatex sport_pohyb_jh.xml.tex
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./sport_pohyb_jh.xml.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 2 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg)
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-def/xetex.def))
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty))

! LaTeX Error: File `wrapfig.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)


2015-11-19 15:15 GMT+01:00 smjwsk-onb <notifications@github.com>:

**Comment by smjwsk** [comment]
$ apt-get install texlive-latex-extra
should get you this package installed. Be aware that this might not be the last package latex will require for running without complaints on the file, but this is most likely the way to proceed.

**Comment by lb42** [comment]
Just to confirm: to use teitopdf or teioslides you should need to install the  following packages under Ubuntu

 $apt-get install texlive texlive-xetex texlive-latex-extra 

You may also  need to install some fonts, especially if you aim to produce the PDF version of P5. 
sudo apt-get install fonts-linuxlibertine  fonts-junicode ttf-kochi-* fonts-arphic-uming
will get <emph>almost</emph> everything you  need: to complete it, you should also install the Han Nom A fonts which are   (seemingly) only available from          http://vietunicode.sourceforge.net/fonts/fonts_hannom.html

**Comment by martindholmes** [comment]
I suspect the Han Nom fonts are actually no longer necessary.

**Comment by smjwsk** [comment]
for the build of the guidelines they are still required, but I think that is something we could change. I have this on my list, will open an issue concerning this.

**Comment by welblaud** [comment]
Thanks to all, however, even with all of these recommended packages,
xelatex logs:

$ xelatex sport_pohyb_jh.xml.texThis is XeTeX, Version
3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./sport_pohyb_jh.xml.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 2 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg)
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-def/xetex.def))
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty))
(/usr/share/texlive/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3names.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3bootstrap.sty))
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3basics.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3expan.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3tl.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3seq.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3int.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3quark.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prg.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3clist.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3token.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prop.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3msg.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3file.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3skip.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3keys.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3fp.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3box.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3coffins.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3color.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3luatex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3candidates.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty))
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-patches.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fixltx2e.sty)
*************************************************
* LaTeX warning: "xparse/redefine-command"
*
* Redefining document command \oldstylenums with arg. spec. 'm' on line 128.
*************************************************
) (/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmr.fd))
(/usr/share/texlive/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(/usr/share/texmf/tex/latex/tipa/t3enc.def
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmss.fd))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg))))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texlive/texmf-dist/tex/latex/relsize/relsize.sty)
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/framed/framed.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ulem/ulem.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline
fix
<2008/02/07> (tvz))
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/marginnote/marginnote.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)

Package hyperref Warning: XeTeX driver only supports unicode.
(hyperref)                Enabling option `unicode'.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
kpathsea: Running mktextfm pzdr
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode;
input pzdr
This is METAFONT, Version 2.718281 (TeX Live 2013/Debian)

kpathsea: Running mktexmf pzdr
! I can't find file `pzdr'.
<*> \mode:=ljfour; mag:=1; nonstopmode; input pzdr

Please type another input file name
! Emergency stop.
<*> \mode:=ljfour; mag:=1; nonstopmode; input pzdr

Transcript written on mfput.log.
grep: pzdr.log: Adresář nebo soubor neexistuje
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input
pzdr' failed to make pzdr.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font \XeTeXLink@font=pzdr at 0.00002pt not loadable: Metric (TFM) file or
ins
talled font not found.
<to be read again>
                   \relax
l.5125   \font\XeTeXLink@font=pzdr at 1sp\relax

?

This reminds me of days when I was testing/trying several branches of
TeX/LaTeX... :) a bit frustrating up today.

I am trying to set this up for testing of the XML-based workflow for a
publishing house I work for. If this worked, it would be a very interesting
solution!

Honza

2015-11-19 17:11 GMT+01:00 Stefan Majewski <notifications@github.com>:

**Comment by welblaud** [comment]
P. S. I am relatively new to TEI and its pro usage. I even don't know
whether it could be possible to generate TEI Lite/Simple with docxtotei!

2015-11-19 20:40 GMT+01:00 Honza Hejzl <honza.hejzl@gmail.com>:

**Comment by smjwsk** [comment]
texlive-fonts-recommended is most likely what you need.
http://tex.stackexchange.com/questions/50596/latex-font-error-i-cant-find-file-pzdr

But I guess your question is most likely a good match for as there are
probably more working with publishing pipelines.
https://listserv.brown.edu/archives/cgi-bin/wa?SUBED1=tei-l&A=1/

**Comment by welblaud** [comment]
Thanks, at the moment, xelatex really generates the pdf (seems good) with
only one additional warning:

! Package xcolor Error: Undefined color `FF0000'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.454 {\bfseries\color{FF0000}
                              <obr01.eps>}\par
? ^C! Interruption.
\GenericError  ...
                                                  \endgroup
l.454 {\bfseries\color{FF0000}
                              <obr01.eps>}\par
?

However, teitopdf still fails:

$ ../git/Stylesheets/bin/teitopdf sport_pohyb_jh.xml
Convert sport_pohyb_jh.xml to
/home/honza/development_testing/sport_pohyb_jh.xml.pdf (tei to pdf) using
profile default
Warning: XML resolver not found; external catalogs will be ignored
Warning: XML resolver not found; external catalogs will be ignored
     [echo] Running XeLaTeX on
/home/honza/development_testing/sport_pohyb_jh.xml.tex in
/home/honza/development_testing

BUILD FAILED
/home/honza/git/Stylesheets/pdf/build-to.xml:56: The following error
occurred while executing this line:
/home/honza/git/Stylesheets/common/teianttasks.xml:211: exec returned: 1

Total time: 17 seconds

Anyway, thanks for the tip!

2015-11-19 21:36 GMT+01:00 Stefan Majewski <notifications@github.com>:

**Comment by peterstadler** [comment]
Just for the record: For creating PDF output from a TEI file you could as well use the oxgarage web service (which is scriptable) at http://www.tei-c.org/oxgarage/

**Comment by welblaud** [comment]
Thanks, I am still seeking for information. At the moment, I am trying to
figure out whether it should be better to stick to TEI Lite (or some
customized variant of TEI in general) or adopt TEI Simple immediately. With
the later I have more problems (can’t properly produce PDF in Oxygen, the
whole rendition thing seems a bit ahead of the state of things). Thanks
again for the recommendation.
H.

2015-11-23 9:53 GMT+01:00 Peter Stadler <notifications@github.com>:

**Comment by welblaud** [comment]
I have just tested the same file in Oxygen 16.1, Oxygen 17 (Linux/Win) and
XeLaTeX and there is a strange problem with styling footnotes.

When generated through XeLaTeX, footnotes seem good. When via Oxygen, the
number and the rest of the footnotes’ body are separated (linebreak). I
can’t figure where could be the problem.

Besides, I am very satisfied with the whole Stylesheet set :)

2015-11-19 15:15 GMT+01:00 smjwsk-onb <notifications@github.com>:

**Comment by jamescummings** [comment]
Also just for the record: 

In your original commandline if you added  --debug to the commandline (e.g. teitopdf --debug ....) then it would do two things, not delete any intermediate files and give a more verbose output.  Usually I find the problem is with fonts that I don't have installed when this happens.

**Comment by welblaud** [comment]
Thanks, suddenly it works. The warning about missing XML resolver is still
there (don’t understand, I have installed it) but the pdf is produced. I am
nearly totally satisfied with the result. I know in stylesheets there is a
statement about tables – they should have a bit smaller font and able to
fit the page properly. In Oxygen, this works, here not. The funny thing is
in Oxygen don’t work footnotes, in XeLaTeX tables (with the same
stylesheets). Any advice how to deal with that in the former or the later
is more than welcome :)

XeLaTeX result (the last page) <ftp://46.28.111.241/sport_tei_lite.xml.pdf>
<ftp://46.28.111.241/sport_tei_lite.xml.pdf>(problem with tables, Captions
work but I am not able to set them like in Oxygen)

Oxygen result <ftp://46.28.111.241/tei_lite_FO_test.pdf>
(problem with footnotes and table Captions)

Honza


2015-11-24 19:00 GMT+01:00 James Cummings <notifications@github.com>:
