### ISSUE TITLE
Hannom fonts could be removed

### ISSUE THREAD

**Issue by smjwsk** [TEIC/Stylesheets#132]
The fonts HAN NOM A and HAN  NOM B could most likely be removed, which is sensible as there is no package for most systems that renders them readily installable on a variety of platforms.

http://vietunicode.sourceforge.net/fonts/fonts_hannom.html

Will check how to remove them without breaking too much. The fonts don't work in all circumstances anyway. See http://www.tei-c.org/Vault/P5/2.9.1/doc/tei-p5-doc/en/Guidelines.pdf page 202 (pdfpage 258)

**Comment by martindholmes** [comment]
I thought the Han Nom fonts were intended for Vietnamese (although now I check, we have nothing in the Guidelines tagged as xml:lang="vi"). Why are they being used for Japanese there?

**Comment by smjwsk** [comment]
They cover much of the CJK range, but as I see there are other actively maintained fonts that do that as well: http://www.babelstone.co.uk/Fonts/Han.html . The babelstone fonts made it into an Ubuntu package, which may be useful. I'll give it a try

**Comment by martindholmes** [comment]
@ebeshero and I suggest that at this point, it would make more sense to move to Noto fonts, which cover all ranges we need, are open-source etc., and would provide a more consistent appearance. We suggest that this ticket be closed and a new one opened for switching to Noto.

**Comment by hcayless** [comment]
I heartily endorse this idea.
