### ISSUE TITLE
Translations: indicate when they are out of date with the English version

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#138]
A sizable chunk of the text in the reference pages is translated to other languages (mostly French). It would be useful to indicate _on the ref pages_ whether the English text has outdated the translation. It would be possible to determine this based on `@versionDate` on `<desc>` and `<remarks>`.

Moved from TEIC/TEI#1348

**Comment by lb42** [comment]
I had assumed that all that would be required would be to add a signal in the HTML (say, add class="outofdate" to the relevant block) so that it can be rendered in a different way, e.g. wavy type to indicate uncertainty or something. The stylesheet doesn't need to do more than compare the @versionDate on the chunk it's handling with that of its  sibling with xml:lang="en" (assuming that the English one is always up to date, ha ha)

**Comment by martindholmes** [comment]
It's easy to do that, but unless you know what it means, it's not helpful. I don't know of any generally-accepted visual/design signal for "out-of-date translation", so somewhere, somehow, it has to be explained; and if you're in need of the translation for a gloss or desc, the chances are you'd be equally in need of a translated explanation for the signal.

**Comment by lb42** [comment]
So what is your suggestion? Insert the phrase "[traduction douteuse/déplacée/perimée]"  vel sim? It seems to me that there are already quite a few visual conventions in the way the Glines are displayed on screen (e.g. use of red box for deprecated examples). Or is the suggestion that out of date translations should be silently suppressed/replaced by English or what?

**Comment by martindholmes** [comment]
I don't have a suggestion; I'm just looking for guidance. The ticket was assigned to me, but I don't know exactly what to do to handle it.

**Comment by martindholmes** [comment]
Quick note to say that this is problematic with `<remarks>` because there may be multiple remarks in various languages and it's not clear which remark in (say) Japanese should correspond with which remark in English. So I'm working on `<gloss>` and `<desc>` at the moment.

**Comment by martindholmes** [comment]
First stage is done in commit 863fed8: the odd2lite.xsl process now adds `@rend='outOfDateTranslation'` to `<seg>` elements generated from `<gloss>` and `<desc>` elements which are dated before the English version. The next stage is to process that `@rend` attribute into a class in the HTML generation. (Do we care about PDF?)

**Comment by martinascholger** [comment]
Sorry that I'm just joining the discussion now. I try to summarize for myself:
we need some kind of indicator for outdated translations, which means a) text rendered in some way or b) an icon. Both has to be explained. I personally tend towards an icon before or after the affected text with a tooltip saying "translation out of date". I think it rarely affects `<gloss>`?, it more frequently affects `<desc>` and `<remarks>` (if we find a solution for the allocation problem). 
Should we use `@corresp` for this purpose in the future? I'm not suggesting to add this to every single spec now, but we could make those changes whenever we are working on a specific spec anyway. 
And, we must not forget attributes and their values ... 
I don't know either if there is a generally-accepted icon for out-of-date-translation. Maybe an icon like this: [https://cdn2.iconfinder.com/data/icons/social-productivity-line-art-1/128/history-512.png](https://cdn2.iconfinder.com/data/icons/social-productivity-line-art-1/128/history-512.png)

**Comment by jamescummings** [comment]
I like b). Just an icon or asterisk or something afterwards with a hover/title tooltip saying "Translation out of date".

**Comment by martindholmes** [comment]
Stylesheets coop group likes the idea of an icon with a tooltip in the HTML output. We need to get translations in all the languages of the explanatory text, and then figure out how to put those into the i18n system, then make the icon and tooltip appear in the text.

**Comment by sydb** [comment]
Of the 518 constructs with child `<remarks>`, only 6 have different counts of individual languages:

construct                | en | fr | ja | es | de
--------------------------|----|----|----|----|----
`@degree` of att.damaged  | 1  |  1 |  2 | 1  | 0
att.editLike 		  |  2 |  1 |  1 | 1  | 0
`@unit` of att.milestoneUnit | 1 | 2 | 1 | 0  | 0
`<expan>`  		  | 2  | 1  | 1  | 0  | 2 
`@type` of `<list>` 	  | 2  | 1  | 1  | 0  | 2
`<locus>`  		  | 2  | 1  | 0  | 0  | 0

**Comment by martinascholger** [comment]
@martindholmes I wanted to run this test, but can't find text.xml
`java -jar Utilities/lib/saxon9he.jar -xsl:`pwd`/../../Stylesheets/odds/odd2lite.xsl -s:p5.xml -o:test.xml documentationLanguage=ja lang=ja language=ja doclang=ja`
Or did you already fix the issue with `hi` ?

**Comment by martindholmes** [comment]
@martinascholger You'd be running this in order to create "test.xml". It assumes you have p5.xml already in your TEI/P5 folder, and that the Stylesheets repo is in the same folder as the TEI repo. What happens when you run it?

**Comment by martinascholger** [comment]
Do we agree to say "Translation out of date" in the tooltip? We could start to collect the translations then. 
ko, zh-TW, ja, fr, es, it, de

**Comment by martindholmes** [comment]
That works for me.

**Comment by martinascholger** [comment]
Ok, we need translations of the explanatory text "Translation out of date" in the tooltip. 
@lb42, @raffazizzi could you please help us with this and add translations? 

| language       | info text    | 
| ------------- |:------------- |
| en      | Translation out of date |
| de      | Übersetzung veraltet    | 
| ko       |            |
| zh-TW    |            |
| ja       |            |
| fr       |            |
| es       |            |
| it       |            |

**Comment by lb42** [comment]
Traduction périmée

**Comment by lb42** [comment]
Otoh the translation is not necessarily wrong, even if it's "out of date". Itmay just lack some  nuance added in the English. I don't think  anything is edited for the first time in any non English language is it,?

**Comment by martindholmes** [comment]
It's almost certainly wrong if it's out of date. What that means (assuming people have done things properly) is that the English version has changed since the original translation was made. Unless the change was so trivial that translations remain accurate (hard to imagine), any out-of-date translation is wrong.

**Comment by lb42** [comment]
Sorry @martindholmes, but the evidence does not  
[langCounts.txt](https://github.com/TEIC/Stylesheets/files/2067808/langCounts.txt)
support your assertion. I ran the attached stylesheet against the current version of p5subset to look at "out of date" desc elements in French (there are 351 of them) in comparison with the "correct" English version. I got bored eyeballing the results, but well over 70% of those I checked were perfectly OK. Try it for yourself.

**Comment by martindholmes** [comment]
@lb42 That suggests one of two things: either the dates on the English translations were changed without their contents being changed, or the French translations were updated without their version date being updated. I think the latter is more plausible.

Nevertheless, you can't know without checking, can you? So they all have to be looked at.

**Comment by lb42** [comment]
Speculation as to whether contents were changed without dates being changed could be resolved by attention to the version history for the file I suppose, but I don't think that's what's happening here. My speculation is that @versionDate  changed when *any* change was made to the specification concerned, whether or not it invalidated existing descriptions.

**Comment by martindholmes** [comment]
If people are arbitrarily changing the `@versionDate` on the English `<gloss>` or `<desc>` when they didn't actually change the `<gloss>` or `<desc>` itself, then we have a problem. Why would anyone do that?

**Comment by lb42** [comment]
My suspicions focus on commit 087964ad7e7b3b369368e4974d7481d0f7ddbef5, which is the one that introduced @versionDate values for english language descs (previously missing). Who knows where the date that was introduced there came from?

**Comment by lb42** [comment]
FWIW, here are the counts for elements which have been translated in the current p5subset
I'll do another table for the allegedly out of date ones later. This shows that there's still some way to go on German, and that the French are excessively fond of glosses. 

element|en|de|fr|ja|ko|es|it|zh-TW|nolang
-------|----|----|----|----|----|----|----|---|---|
DESC|1808|292|1471|1410|1374|1396|1417|1287|24
GLOSS|530|209|680|10|460|488|478|306|3
REMARKS|523|87|391|367|0|69|0|0|0

**Comment by martindholmes** [comment]
How does French have more glosses than English?

**Comment by lb42** [comment]
You may well ask....

**Comment by martindholmes** [comment]
Stylesheets group believes the manifestation of this should be an asterisk with a mouseover explanation. We need to strike a balance between worrying people and soliciting corrections.

**Comment by ebeshero** [comment]
See https://github.com/TEIC/TEI/issues/1780 : which should be an agenda item for next Council meeting.

**Comment by martindholmes** [comment]
GI|en|de|fr|ja|ko|es|it|zh-TW|NO LANG
-------|----|----|----|----|----|----|----|---|---|
gloss|1 / 530|1 / 209|1 / 680|1 / 10|1 / 460|1 / 488|1 / 478|1 / 306
desc|1 / 1800|1 / 292|1 / 1449|1 / 1389|1 / 1374|1 / 1396|1 / 1396|1 / 1266
remarks|1 / 523|1 / 87|1 / 391|1 / 367|1 / 0|1 / 69|1 / 0|1 / 0

**Comment by martindholmes** [comment]
Table of items out of date for each language:

GI|en|de|fr|ja|ko|es|it|zh-TW|NO LANG
-------|----|----|----|----|----|----|----|---|---|
gloss|0 / 530|6 / 209|121 / 680|0 / 10|17 / 460|104 / 488|63 / 478|101 / 306
desc|0 / 1800|22 / 292|350 / 1449|250 / 1389|268 / 1374|409 / 1396|652 / 1396|603 / 1266
remarks|2 / 523|1 / 87|147 / 391|128 / 367|0 / 0|26 / 69|0 / 0|0 / 0

**Comment by martindholmes** [comment]
Count of out-of-date items for each language:

GI|en|de|fr|ja|ko|es|it|zh-TW
-------|----|----|----|----|----|----|----|---|---|
gloss|0 / 530|6 / 209|121 / 680|0 / 10|17 / 460|104 / 488|63 / 478|101 / 306
desc|0 / 1800|22 / 292|350 / 1449|250 / 1389|268 / 1374|409 / 1396|652 / 1396|603 / 1266
remarks|2 / 523|1 / 87|147 / 391|128 / 367|0 / 0|26 / 69|0 / 0|0 / 0

**Comment by martindholmes** [comment]
Counts of out-of-date items versus total items for each language:

GI|en|de|fr|ja|ko|es|it|zh-TW
-------|----|----|----|----|----|----|----|---|
gloss|0 / 530|6 / 209|121 / 680|0 / 10|17 / 460|104 / 488|63 / 478|101 / 306
desc|0 / 1800|22 / 292|350 / 1449|250 / 1389|268 / 1374|409 / 1396|652 / 1396|603 / 1266
remarks|2 / 523|1 / 87|147 / 391|128 / 367|0 / 0|26 / 69|0 / 0|0 / 0

**Comment by martinascholger** [comment]
@sydb and @martindholmes: since you already have a script, could you please let me know which German gloss/desc/remarks are out-of-date? Since there aren't that many, I'd update them.

**Comment by sydb** [comment]
OK. (@martindholmes, if you want to send me a copy of the script, I can modify for German-only and say which ones; @martinascholger: I will try to do that tomorrow night your time)

**Comment by lb42** [comment]
To answer Martin's question of a while ago (why does French have more glosses than English?) -- gloss is only (should only be) provided if the meaning of an element's GI is not apparent from its form, i.e. we don't explain that the tag "editor" is so called because it contains an editor, though we do explain that the tag "fs" contains a feature structure. The French translators, being French and logical, reasoned that therefore they should provide a literal translation of the GI for each element, and tag it as gloss, since (e.g.) "editor" is not a French word (well it is nearly but it means something different).

**Comment by martindholmes** [comment]
Here it is (quick and dirty as usual).
[outOfDate.xsl.zip](https://github.com/TEIC/Stylesheets/files/2171532/outOfDate.xsl.zip)

**Comment by martinascholger** [comment]
Thanks for the list @sydb. I had a look at the translations today. Some of the German glosses aren't out of date, although they have an older date than the English gloss. This is because the spelling has been changed to lower-case in some of the English glosses, which doesn't make a difference for the German translations. How should we deal with that? For practical reasons it would make sense to change the date for the German translations, but that would distort the history.

**Comment by martinascholger** [comment]
Updated German translations with https://github.com/TEIC/TEI/commit/1e148284d78b6c52a526f3642769d3b36cf6bc02U

**Comment by hcayless** [comment]
I contend this is done.
