### ISSUE TITLE
Implement @include and @exclude on classRef

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#139]
See discussion on TEIC/TEI#1412. One possibility is to generate a schematron rule that fires if excluded elements appear. Possibly ODD expansion should translate `@include` to `@exclude`.

**Comment by JanelleJenstad** [comment]
@sydb and I think that this ticket can be closed. 20 days after @hcayless opened, @lb42 closed the related ticket, implying that it already worked. There are 5 examples of how to use <code>@accept</code> but we don't actually use it anywhere. Assigning to @HelenaSabel to try using it to test if it works. If it does, this ticket can be closed. If not, this ticket needs discussion.

**Comment by sydb** [comment]
Note that #140 is directly related.

**Comment by HelenaSabel** [comment]
Tested with a slight modification of the ODD generated by @lb42 and mentioned in ticket #140: it works as expected.
