### ISSUE TITLE
dataRef as child of content nearly works

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#141]
It should be possible to specify just a dataRef as content for an element. However this only seems to work if the dataRef uses @name to point to an XSD definition; a @key value pointing to a TEI dataspec is ignored and the element winds up empty. 
~~~~
<content>
<dataRef name="anyURI"/>
</content>
<!-- ought to have the same effect as -->
<content>
<dataRef key="teidata.pointer"/>
</content>
<!-- but while the former correctly produces a content model of xsd:anyuri
     the latter produces a content model which is empty -->
~~~~

(evidenced in CMIF odd; thanks Peter Stadler)

**Comment by hcayless** [comment]
I can't reproduce if I remember to set the $#!*%! localsource variable to a build of TEI with Pure ODD in it. I get:
~~~~~
<define name="dataElt">
  <element name="dataElt">
    <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">Element with a datatype as content</a:documentation>
    <data type="anyURI"/>
  </element>
</define>
~~~~~
which seems right. This keeps happening to me. I think we should have a better warning about which source is being used when the script is run. Right now it gives you a message only if you set localsource, but really, it should warn you it's going and downloading a copy from the last release if you *didn't* set it.

**Comment by lb42** [comment]
This definitely suggests we should be aiming for a new release ASAP!
