### ISSUE TITLE
ODD Expansion produces RNG content models

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#142]
ODD expansion (the inlining of referenced items in an ODD to produce a full version) outputs an ODD with RelaxNG content models rather than Pure ODD ones. This is undesirable behavior if we consider the expanded ODD to be a first class artifact rather than simply an intermediary. It is frequently the latter, as ODD expansion is a precursor to any schema generation operation, and the expanded version is then thrown away. But it can also be used to produce a full ODD for a project, and in that case, Pure ODD content models would be nice.

Fixing this is probably low priority and fraught with all sorts of potential bugs.

**Comment by lb42** [comment]
Not sure what you mean. Can you provide an example?

**Comment by hcayless** [comment]
Just run bin/teitoodd on any ODD. You should get an ODD with all the references inlined, but with all content models turned into RNG.

**Comment by hcayless** [comment]
I keep getting bitten by this one: forgetting to set localsource when I run Stylesheets executables. That's the problem. Never mind
