### ISSUE TITLE
odd2xhtml: customisation not shown when schema associated with source document

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [TEIC/Stylesheets#143]
I have a very weird bug with ODD customisation and the ODD to XHTML stylesheets (oXygen plugin, current version, 4.0.0). 
When I try to create a xhtml output, if a schema association is present at the start of the document, modifications to attribute or content models are not shown in the documentation, but the standard descriptions are shown instead. If I comment out the schema association (more precisely, the `?xml-model`instruction pointing to http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng), it suddenly works.
I add a quick MWE that shows the bug (and its disappearance, as soon as `<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>` is commented).
Did I miss something ?

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Comment the following line and the bug disappears -->
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml"
    schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Title</title>
            </titleStmt>
            <publicationStmt>
                <p>Publication Information</p>
            </publicationStmt>
            <sourceDesc>
                <p>Information about the source</p>
            </sourceDesc>
        </fileDesc>
    </teiHeader>
    <text>
        <body>
            <p> Here the doc of some element: <specDesc key="TEI" atts="n"/>
            </p>
            <schemaSpec ident="myTEI" start="TEI">
                    <moduleRef key="tei"/>
                    <moduleRef key="textstructure" include="TEI"/>
                    <elementSpec ident="TEI" mode="change">
                    <attList>
                        <attDef ident="n" mode="change">
                            <valList mode="add">
                                <valItem ident="1"/>
                                <valItem ident="2"/>
                            </valList>
                        </attDef>
                    </attList>
                </elementSpec>
            </schemaSpec>
        </body>
    </text>
</TEI>
```

**Comment by sydb** [comment]
Sorry, @Jean-Baptiste-Camps, but I cannot reproduce any error, here. That is, there is no difference for me (except the timestamp) of the XHTML generated from the code above with or without the `xml-model` PIs at the top. How are you generating documentation?

**Comment by ebeshero** [comment]
@martindholmes and I think this should be closed because we were not able to reproduce the problem and the OP didn't respond.
