### ISSUE TITLE
PureODD <sequence> occasionally needs to be transformed to <rng:list>

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/Stylesheets#152]
Currently, a PureODD datatype defined like this:

```xml
<dataSpec ident="meidata.twoDecimals">
   <content>
      <sequence>
         <dataRef name="decimal"/>
         <dataRef name="decimal"/>
      </sequence>
   </content>
<dataSpec>
```
results in the invalid RNG:
```xml
<group>
    <data type="decimal"/>
    <data type="decimal"/>
</group>
```
There should be a list instead.

This may be a either:
 * a PureODD issue, e.g. this should be a different type of "sequence" (see https://github.com/TEIC/TEI/issues/1462)
 * a processing issue, e.g. the Stylesheets should be smart and figure out whether the correct RNG output is `list` or `group`.

In the latter case, we should patch the Stylesheets. A possible approach is:
 * resolve all `dataRef[@key]`s in a `sequence`
 * if they return any sequence of `dataRef[@name]`, it's a list, if not, it's a group

**Comment by lb42** [comment]
Can someone explain what the difference is?

**Comment by raffazizzi** [comment]
From http://relaxng.org/tutorial-20011203.html#IDAK0YR

lists
> The list pattern matches a whitespace-separated sequence of tokens; it contains a pattern that the sequence of individual tokens must match.

groups
> The group and choice patterns can combine element and attribute patterns without restriction.

**Comment by lb42** [comment]
Yes, I saw that, but I am not a whole lot  wiser. It seems like rng:list is a way of defining complex datatypes, for which we could use a dataSpec (as I suggested earlier, I'd define this datatype with an appropriate regexp)

**Comment by raffazizzi** [comment]
Yes, defining it with a regex would work, but you'd lose the datatype specification: it would just be a string as opposed to a pair of decimal numbers (I realize that it's all strings all the way down anyway...)

**Comment by lb42** [comment]
If rng@group is more general than rng:list, I really don't understand why jing complains about its use here. But if w weant to respect the distinction, would it be fair to say that tei:sequence always becomes rng:group EXCEPT in the case where it appears within the tei:content of a tei:dataSpec ? Or is there an additional requirement that its children should be identical?
