### ISSUE TITLE
content/valList is ignored

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#154]
In the attached teeny customization file, a `<valList>` is used as the content of `<content>` to express that there is an enumerated closed list of possible values for the content of an element. Section [22.5.1 Defining Content Models](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#DEFCON) clearly states that this is a possible way to define a content model. However, whether I process this ODD customization file on the commandline using `roma`, on the commandline using `teitornc`, using the stylesheets in the oXygen framework, or [Roma](http://tei.oucs.ox.ac.uk/Roma/), the resulting RELAX NG allows no content at all. E.g.: 

```
a_licence =

  ## contains information about a licence or other legal agreement applicable to the text. [2.2.4. Publication, Distribution, Licensing, etc.]
  element licence {
    empty,
    a_att.global.attributes,
    a_att.pointing.attributes,
    a_att.datable.attributes,
    empty
  }
```

[t.odd.txt](https://github.com/TEIC/Stylesheets/files/296090/t.odd.txt)

**Comment by sydb** [comment]
Note also that the generated HTML documentation also asserts that the content of the modified element is empty. Although interestingly, the schema declaration snippet does not include the `empty,` that occurs before the attribute patterns.

**Comment by lb42** [comment]
I can confirm that this is a usage  which the stylesheets are currently not handling, even when the typo in your sample file is corrected. Of course we dont *guarantee* that everything permitted in the documentation will be implemented by our stylesheets, but still ...

**Comment by martindholmes** [comment]
I'm just implementing a test for this in Test2, and I don't get an empty content model at all. Here's my ODD fragment:

~~~~~
<elementSpec ident="email" module="core" mode="change">
          <content>
            <valList type="closed">
              <valItem ident="amourdecosmos@gmail.com">
                <gloss>The email address of Amour de Cosmos.</gloss>
              </valItem>
              <valItem ident="thevenerablebede@gmail.com">
                <gloss>The email address of The Venerable Bede.</gloss>
              </valItem>
            </valList>
          </content>
        </elementSpec>
~~~~~
This is the resulting RNG:

~~~~~
<define name="t_email">
      <element name="email">
         <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(electronic mail address) contains an email address identifying a location to which email messages can be delivered. [3.5.2. Addresses]</a:documentation>
         <choice>
            <value>amourdecosmos@gmail.com</value>
            <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(The email address of Amour de Cosmos.) </a:documentation>
            <value>thevenerablebede@gmail.com</value>
            <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(The email address of The Venerable Bede.) </a:documentation>
         </choice>
         <ref name="t_att.global.attributes"/>
         <empty/>
      </element>
   </define>
~~~~~
which works as advertized, constraining the content for that element. I'm not sure what that `<empty/>` is doing there, but it doesn't appear to have any effect. Converting to RNC with Trang gives this:

~~~~~
t_email =
  
  ## (electronic mail address) contains an email address identifying a location to which email messages can be delivered. [3.5.2. Addresses]
  element email {
    (
     ## (The email address of Amour de Cosmos.) 
     "amourdecosmos@gmail.com"
     | 
       ## (The email address of The Venerable Bede.) 
       "thevenerablebede@gmail.com"),
    t_att.global.attributes,
    empty
  }
~~~~~
which also seems to work fine, despite the final "empty". (The element is not allowed to be empty in either case.)

**Comment by sydb** [comment]
Yup. Seems to be working just fine. However, the documentation is problematic. Hence closing this ticket, and just opened #365.
