### ISSUE TITLE
Paragraps ignored in <remarks>

### ISSUE THREAD

**Issue by gioele** [TEIC/Stylesheets#161]
Converting the following piece of ODD to HTML

``` xml
<elementSpec ident="div" mode="change">
    <remarks>
        <p>aaa</p>
        <p>bbb</p>
    </remarks>
</elementSpec>
```

produces the following HTML code

``` html
<tr>
    <td class="wovenodd-col1"><span class="label" lang="en">Note</span></td>
    <td class="wovenodd-col2">aaabbb</td>
</tr>
```

Please note that the two paragraphs are merged together.

What I would had expected is, instead, a `<td>` element like this:

``` html
    <td class="wovenodd-col2">
        <p>aaa</p>
        <p>bbb</p>
    </td>
```

Could you please convert the TEI paragraphs inside the `<remarks>` section into HTML paragraphs?

**Comment by martindholmes** [comment]
Just saw this ticket go by while I was in the Stylesheets, so for reference: around line 1683 in common/common_tagdocs.xsl, there's a call to apply-templates which should process the contents of a remarks element...

**Comment by martindholmes** [comment]
The XSLT study group today made a tentative change to odds/odd2lite.xsl in commit:

c2e02b8..20d7526

And we'll see if it works.

**Comment by martindholmes** [comment]
The build failed, but because of a test comparison, which is expected from any change. Will follow up, but things look promising...

**Comment by martindholmes** [comment]
Pushed a change for expected-results to handle the difference in commit 53e3eca. Test build OK locally for me with only this change (although the LaTeX stuff isn't working on my machine).

**Comment by emylonas** [comment]
This seems to be working, see [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html). Can we close the ticket? @martindholmes

**Comment by martindholmes** [comment]
Seems to be working...
