### ISSUE TITLE
Normal ODD processing to RNG results in two Schematron rules with the same id

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#176]
If you generate an RNG schema which includes `<relatedItem>`, you will get something like this:

```
<pattern xmlns="http://purl.oclc.org/dsdl/schematron"
                  id="vpn-relatedItem-targetorcontent1-constraint-8">
            <rule context="tei:relatedItem">
               <sch:report xmlns:rng="http://relaxng.org/ns/structure/1.0"
                           xmlns="http://www.tei-c.org/ns/1.0"
                           xmlns:sch="http://purl.oclc.org/dsdl/schematron"
                           test="@target and count( child::* ) &gt; 0">
If the @target attribute on <sch:name/> is used, the
relatedItem element must be empty</sch:report>
            </rule>
         </pattern>
         <pattern xmlns="http://purl.oclc.org/dsdl/schematron"
                  id="vpn-relatedItem-targetorcontent1-constraint-8">
            <rule context="tei:relatedItem">
               <sch:assert xmlns:rng="http://relaxng.org/ns/structure/1.0"
                           xmlns="http://www.tei-c.org/ns/1.0"
                           xmlns:sch="http://purl.oclc.org/dsdl/schematron"
                           test="@target or child::*">A relatedItem element should have either a 'target' attribute
        or a child element to indicate the related bibliographic item</sch:assert>
            </rule>
         </pattern>
```

which is not invalid, but if you then try to validate a file with it and you include embedded Schematron validation, you'll get an error from the Schematron process because of the duplicate id. I'll do a bit more investigation of this, since I think I have a suspicion about what's happening here.

**Comment by martindholmes** [comment]
I think this is triggered by the fact that the spec for relatedItem has two tests (one sch:report and one sch:assert) in the same constraintSpec/constraint:

~~~~~
<constraintSpec ident="targetorcontent1" scheme="isoschematron">
    <constraint>
      <sch:report test="@target and count( child::* ) &gt; 0">
If the @target attribute on <sch:name/> is used, the
relatedItem element must be empty</sch:report>
      <sch:assert test="@target or child::*">A relatedItem element should have either a 'target' attribute
        or a child element to indicate the related bibliographic item</sch:assert>
    </constraint>
  </constraintSpec>
~~~~~

However, since there's nothing wrong with doing this, it is a bug in the Stylesheets. My guess is that the numeric id suffix is calculated by counting constraints or constraintSpecs, and it should be calculated by counting sch:reports and sch:asserts.

**Comment by martindholmes** [comment]
I think the problem is in common/functions.xsl, starting at line 1417:

~~~~~
<doc xmlns="http://www.oxygenxml.com/ns/doc/xsl">
    <desc>work out unique ID for generated Schematron</desc>
  </doc>
  <xsl:function name="tei:makePatternID" as="xs:string">
    <xsl:param name="context"/>
    <xsl:for-each select="$context">
      <xsl:variable name="num">
	<xsl:number level="any"/>
      </xsl:variable>
      <xsl:value-of
	  select="(../ancestor::*[@ident]/@ident,'constraint',../@ident,$num)"
	  separator="-"/>
    </xsl:for-each>
  </xsl:function>
~~~~~

This is called from a variety of contexts, triggering on any child of a constraint element or any element in the Schematron namespace (see the last lines of odds/teiodds.xsl). This would make a good ticket for our Stylesheets study group, since it's inherently a rather simple problem, but due to the complexity of the stylesheet hierarchy it's a little tricky to figure out what the $context node is when the function is actually called.

**Comment by martindholmes** [comment]
After discussion with SB, we think that the best fix would be to rewrite the processing such that the resulting output from a case where more than one assertion and/or report occurs in the same rule results not in two separate patterns but in one, with a single id.

**Comment by martindholmes** [comment]
This ODD file generates the error; it doesn't always appear (so it doesn't appear in tei_all, for instance).

**Comment by sydb** [comment]
And worth noting that the *position* of the `<constraintSpec>` within the ODD has some effect on the numeric value of the generated name of the output `<pattern>`.

**Comment by martindholmes** [comment]
Syd committed an attempted fix for this a few days ago, which broke the build, but having looked at the fix itself:

https://github.com/TEIC/Stylesheets/commit/d518a209296ac549de5fe02cd744038c3d18be22

I don't think it can work; the problem is that when the pattern ids are created for two different constraints, the same ancestor element is passed into the function as the $context parameter; that means that the fix can't be made simply in the function itself, because the same input twice will produce the same output twice.

Or am I misunderstanding something?

**Comment by martindholmes** [comment]
It turns out I was misunderstanding: Syd's fix was aimed at the process of extracting schematron rather than solving this problem. The build-break was caused by altered expected-results, which should be fixed in a commit around now.

**Comment by martindholmes** [comment]
Linked to this issue:

https://github.com/TEIC/oxygen-tei/issues/7

**Comment by lb42** [comment]
What's wrong with saying you can only have either a sch:assert or a sch:report in a single constraint? wouldnt that solve the issue?

**Comment by hcayless** [comment]
Adjusting the makePatternID function to be a wee bit more unique. The problem occurs because of the way `<xsl:number/>` works. It counts the occurrences of elements of the same name in the document. If you happen to be unlucky enough to have an ODD where an assert and a report occur in the same constraint, and they happen to both be the 8th assert/report, then they'll get the same ID. I just included the name of the context element in the ID. Fixing tests now.

**Comment by martindholmes** [comment]
@lb42: We didn't want to create a limitation in ODD which doesn't exist in the parallel Schematron structure, just to work around a processing bug.

**Comment by hcayless** [comment]
Fixed.
