### ISSUE TITLE
Schematron 1.x (non-ISO Schematron) support should be removed from the Stylesheets

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#178]
This arises out of https://github.com/TEIC/TEI/issues/537. Support for obsolete Schematron has been removed from the TEI infrastructure, but the Stylesheets Schematron processing code remains complicated by the fact that two separate flavours are being handled side by side (s: and sch: prefixed namespaces, with the former being the one we want to remove). It would considerably help in maintaining and bugfixing Schematron-related code if we could just clean out all this cruft.

**Comment by martindholmes** [comment]
This would be a useful task for the Stylesheets co-operative learning group to divide amongst themselves. The first stage would be to confirm that the respective prefixes are used consistently throughout the repo.

**Comment by sydb** [comment]
(Note: this may already be approved by Council, as it was discussed, at least a little, as part of https://github.com/TEIC/TEI/issues/537.)

**Comment by ebeshero** [comment]
@martindholmes I'm definitely game to work on this!

**Comment by martindholmes** [comment]
This ticket needs to begin with a survey of all the Stylesheets to find all instances of the ISO Schematron namespace, to see where it's being declared unnecessarily, and also where it's actually being used.

**Comment by martindholmes** [comment]
The Stylesheets working group is working on this in the branch issue-178-remove-old-sch.

**Comment by martindholmes** [comment]
There is a temporary Jenkins job on the UVic Jenkins building the temporary branch.

**Comment by ebeshero** [comment]
Stylesheets working group moved to a temporary branch to remove all references to the old Schematron namespace, `http://www.ascc.net/xml/schematron` as well as to the prefix `s:` associated with it (and mentions of `s` in `exclude-result-prefixes`. We then tested the branch on Jenkins 2...and it passed all tests at the very end of the session! https://teijenkins.hcmc.uvic.ca/view/Temporary%20jobs/job/Stylesheets-issue-178-remove-old-sch/7/

**Comment by martindholmes** [comment]
Test2 also passes, so I believe anyone who would like to can merge this branch into dev.

**Comment by ebeshero** [comment]
@martindholmes I've merged it in to dev.

**Comment by martindholmes** [comment]
Thanks @ebeshero. I'll close the ticket and delete the Jenkins job. Nice work everybody!

**Comment by JanelleJenstad** [comment]
Bravo all! You’re going to have a hard time persuading me now that stylesheets meetings don’t get stuff done!

Sent from my iPhone

On Apr 22, 2021, at 7:18 PM, Martin Holmes ***@***.***> wrote:

﻿
Notice: This message was sent from outside the University of Victoria email system. Please be cautious with links and sensitive information.


Closed #178<https://github.com/TEIC/Stylesheets/issues/178>.

**Comment by martindholmes** [comment]
@JanelleJenstad I honestly think this is the first one where we've actually solved a complete problem and closed a ticket. Not that we don't make progress, but we usually get half-way into a problem and then it gets carried on by one or two people afterwards. This time, seven different people made commits on the same ticket in the space of an hour.

**Comment by sydb** [comment]
Oh, @JanelleJenstad, we certainly get stuff done. Just not that much that fast. Primarily because we typically find there is more to a problem than meets the eye, as it were. I think we have even closed an occasional ticket before. But this was certainly the most dramatic, and perhaps one of the fastest and best fixes we’ve done _during_ a meeting. (Either way, this is not really the place to chat about group meeting accomplishments.)
