### ISSUE TITLE
Cannot generate valid DTD within oXygen (TEI#1501)

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#180]
Issue 1501 in TEI actually looks like it's a Stylesheets issue or perhaps an oxygen-tei issue:

https://github.com/TEIC/TEI/issues/1501

Investigate and triage appropriately...

**Comment by lb42** [comment]
Look at P5/antbuilder.xml to see how this is fixed in the default build. Essentially, what happens is that the step in which odd is processed to dtd (using odd2dtd.xsl) must do so with reference to a non-default compiled ODD, imaginatively called p5subsetDoctored.xml which is created by transforming the usual p5subset.xml with the  stylesheet Utilities/dtdMagic.xsl

**Comment by martindholmes** [comment]
So the situation we have is that there's a hack in the P5 source which enables the Exemplar ODDs to be built to DTDs successfully, but the same hack was never added to the Stylesheets codebase it currently generates broken ODDs.

If I'm understanding correctly, then, we we probably need to:

1. Make p5subsetDoctored.xml a part of the distribution: http://www.tei-c.org/Vault/P5/current/xml/tei/odd/
2. Modify the common/teianttasks.xml macro oddexpand so that when it receives a parameter suggesting that the odd is being expanded in order to create an eventual DTD, it passes a parameter to odd2odd.xsl telling it to use the p5subsetDoctored.xml file instead of p5subset.xml to expand the ODD.

Have I diagnosed this correctly? I'm assuming that if the doctored version is going to be found in all future releases, it should be available to the Stylesheets whether they're pointing at the TEI server as a source or some other location.

I'm presuming that what we DON'T want to do is put dtdMagic.xsl into the Stylesheets repo. It's a product of the P5 build, like p5subset.xml.

However, this raises potential difficulties for anyone using ODD for non-TEI work. So, ultimately, we're back to the issue of getting rid of DTDs completely so none of these ugly workarounds are necessary.

**Comment by hcayless** [comment]
Can someone give me an example where this *doesn't* work? When I try generating DTDs for random exemplars using teitodtd, it seems to work...I need an example where it's broken so I can see how to fix it.

**Comment by martindholmes** [comment]
Have you tried tei_all? If that doesn't trigger it, it's difficult to imagine what would.

**Comment by hcayless** [comment]
Yeah that did it!

**Comment by hcayless** [comment]
96a82d6232b731496e100d7badee801440136f0e should fix this
