### ISSUE TITLE
Integrate dtdMagic.xsl into odd2dtd.xsl

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#184]
The file [P5]/Utilities/dtdMagic.xsl provides a necessary preliminary step for processing a subset when generating a DTD. This step needs to be integrated into odds/odd2dtd.xsl. See TEIC/TEI#1501 and TEIC/Stylesheets#180.

**Comment by hcayless** [comment]
Done in 96a82d6232b731496e100d7badee801440136f0e
