### ISSUE TITLE
TEI ODD XHTML generates wrong links pointing to the GL

### ISSUE THREAD

**Issue by laurannebp** [TEIC/Stylesheets#186]
Hello,
I was checking my links inside my documentation and I see multiple wrong links pointing to the Guidelines, maybe only when the link concerns the Manuscript Description chapter (logical deduction after a few minutes of multiple clicks on my output).
I tried default transformations inside oXygen (18.0) and Roma transformation (Documentation) and I obtained the same issue in the URL (small letters instead of capital ones) 

> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ms.html#mshy
instead of
> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#mshy

Maybe it was already reported ?

**Comment by martindholmes** [comment]
I've tried to reproduce this with one of my own schemas, and it doesn't seem to happen for me, but I don't have any schemas that point explicitly at the MS chapter. Could you attach your ODD file to the ticket for us?

**Comment by lb42** [comment]
I just tried this with the Exemplars/tei_ms.odd, and yes, the links generated are indeed faulty. Probably a stylesheets issue?

**Comment by laurannebp** [comment]
Thank you Lou !
Here is my ODD file, and the output. The first broken link is on [10.8 History] on the desc of the <acquisition> element.
[bnf_reliure_tei_not_odd.zip](https://github.com/TEIC/Stylesheets/files/599379/bnf_reliure_tei_not_odd.zip)

**Comment by martindholmes** [comment]
This must happen somewhere during odd2lite.xsl, but I can't find it yet. That file imports so much other stuff....

**Comment by hcayless** [comment]
I've found it. It's actually in https://github.com/TEIC/Stylesheets/blob/dev/odds/odd2odd.xsl#L2015 which assumes that Guidelines sections use uppercase IDs. They don't always, and especially not in the MS chapter, which is relatively new. in certain circumstances, it's grabbing the reference from the listRef. So history, for example, has:
````xml
  <listRef>
    <ptr target="#mshy"/>
  </listRef>
````
If the ID being referenced were "MSHY", then everything would work. In other words, we broke our own unspoken conventions.

We can either patch it by uppercasing the chapter reference in the XSLT I referenced, or by changing the IDs and adopting this as an explicit convention. The former will break a bunch of tests, but that's easily fixed. The latter means a bit more work...

**Comment by lb42** [comment]
It's just luck that in the gl the identifier for each section of a chapter is also used as a prefix for chunks within it. The xslt should be patched to find and use the chapter Id on the parent div,  not make a guess or munge the first two characters of the reference it has. That stinks.

**Comment by hcayless** [comment]
@lb42 It does. I assume the difficulty was in generating a link to the published TEI Guidelines from custom ODD documentation when you don't actually have a local copy of the GLs to check for the proper chapter names. I think the only way to do that would be to fetch a copy of p5.xml so you could look up the chapter IDs. So that's a 6+ MB download every time you run any ODD processing. Sebastian might have been a little reluctant to do it that way, so maybe he settled for the quick hack instead...

**Comment by lb42** [comment]
No need to get the whole of p5.xml tho Shirley? A simple file mapping I'd value to character would do it.

**Comment by hcayless** [comment]
or a convention that IDs must contain their parent chapter ID as a prefix :-)

**Comment by lb42** [comment]
I hate conventions like that! They always come back to bite you in the end....

**Comment by sydb** [comment]
I have not been following this conversation, so forgive me if I’m off base here, but p5subset.xml retains the `<div>` of each chapter or section complete with its `@xml:id` and child `<head>` just for this purpose.

**Comment by hcayless** [comment]
@sydb so it does! That should make for a better fix then...

**Comment by hcayless** [comment]
Testing a fix now...

**Comment by hcayless** [comment]
Should be fixed with 1a399e627c05f7d48bc20bbb6af2a4ee9e6669eb
