### ISSUE TITLE
datatype should be a member of att.repeatable

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#193]
The element &lt;datatype> currently has locally defined attributes @minOccurs and @maxOccurs. Surely this ought to be indicated by making this element a member of the att.repeatable class?

**Comment by hcayless** [comment]
@lb42 did you mean to open this on the TEI issues? And yes, I don't see why it shouldn't be.

**Comment by sydb** [comment]
Either way, I did this in commit 7edb48e0f013a4d53f1d672bc70a4cb5cc5b8564
