### ISSUE TITLE
default value for @maxOccurs should be unbounded

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#194]
At present the default value for @maxOccurs is 1 which leads to a contradictory situation if @minOccurs is supplied with a value greater than 1. Clearly if I say @minOccurs=3 I am expecting at least 3 occurrences, and maybe more, whatever the notional default for @maxOccurs might be. Possible solutions might  be (a) some clever schematron rule (b) abolish default value (c) set default value to unbounded. I prefer the last, I think.

**Comment by lb42** [comment]
Should be a Guidelines issue methinks, so moving it thetre.

**Comment by martindholmes** [comment]
If you've done this, bear in mind this bug:

https://github.com/TEIC/Stylesheets/issues/190

which is directly affected by the default value of @maxOccurs, especially if it's not an integer.
