### ISSUE TITLE
Error in Guidelines PDF generation

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#202]
If you build the PDF version of the Guidelines and go to the end of section 22.5.4 (around page 689), you will see an example containing some Korean text which is not properly rendered. Presumably an issue with the monospace font? Should we consider replacing it with something like Google's Noto Mono, which supposedly has everything in Unicode?

**Comment by martindholmes** [comment]
There are a number of similar tickets:

#148 #149 #151 

We need a LaTeX guru.

**Comment by sieversMartin** [comment]
https://github.com/dejavu-fonts/dejavu-fonts/blob/master/langcover.txt says:
`ko Korean (0/2442) (0/2442) (0/2442)`

So no support for Korean at all in the used font.

**Comment by sieversMartin** [comment]
BTW: Is `<xsl:param name="sansFont">DejaVu Sans Mono</xsl:param>` correct?

**Comment by sieversMartin** [comment]
http://de.cooltext.com/fonts-unicode-korean lists some free Korean fonts. I wonder, whether a Monotype variant will exists at all. Maybe one should just declare a special font for Korean glyphs.

**Comment by martindholmes** [comment]
On my system, DejaVu Sans Mono appears to have full Hangul support.

**Comment by sieversMartin** [comment]
Strange. http://www.alanwood.net/unicode/fontsbyrange.html does not list it as well.

**Comment by martindholmes** [comment]
I wondered if the Linux font app was fooling me, so I typed a few Hangul characters and pasted them into gedit and Libre Office Writer, then set the font to DejaVu Sans Mono [Book]. The characters appear unchanged. But I suspect something very clever is happening at the system level to switch in a compatible font that supports the range.

**Comment by martindholmes** [comment]
xfd -fa "DevaVu Sans Mono" -start 4364 reveals the truth: no Hangul. This confirms my operating system is more intelligent than I am.

**Comment by martindholmes** [comment]
I wonder if we should consider switching to Noto fonts for the entire PDF generation process. It seems likely we would have a more consistent presentation across languages, with less complexity in keeping the font array up to date.

**Comment by peterstadler** [comment]
So I just assigned the bunch of LaTeX issues to myself and had a first look. I think I fixed the original issue posted by @hcayless ("the end of section 22.5.4 (around page 689)") with 
c4fbe2c. 

It turned out it's not a fine issue but a processing issue – which is way bigger, sigh. There is actually almost no support for `@xml:lang` except for occurrences on `<bibl>` and `<seg>`. Hence the other issue about Japanese captions (#151).

**Comment by peterstadler** [comment]
That said, I did experiment with the Noto CJK fonts and this seems to work as well. I added the font to the Jenkins Dockerfile (https://github.com/TEIC/Jenkins/commit/1fb61a2060815d472a0f6bc67a4dbfe18135790c) so it's available. All that would need to change is here:
https://github.com/TEIC/Stylesheets/blob/5265b007c7f6e582f011c872f3143f1bac24ef59/latex/latex_param.xsl#L247-L249
and probably here:  https://github.com/TEIC/TEI/blob/513c0b14a94a157ddede60dea902d8cd00208224/P5/Utilities-1/guidelines-latex.xsl#L150-L152
and here: https://github.com/TEIC/TEI/blob/513c0b14a94a157ddede60dea902d8cd00208224/P5/Utilities/guidelines-latex.xsl#L226-L228

**Comment by peterstadler** [comment]
The original issue got resolved by c4fbe2c and the Noto CJK fonts have been made the default for the Guidelines by https://github.com/TEIC/TEI/commit/66144683a4a210a8ea6a5e23dffc74ad80d142b6 and https://github.com/TEIC/Stylesheets/commit/b31835fa675bfa7ffaa82c058365687570f7a94c.

**Comment by duncdrum** [comment]
I actually use noto for Hangul, and hannom for Chinese and Japanese in my latex by default. My Korean requirements are minimal, So maybe someone actually working with historic documents from Korea can weigh in here
