### ISSUE TITLE
ODD to FO/PDF processing has multiple bugs

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#205]
As part of work on these linked tickets:

TEIC/TEI#1559
TEIC/oxygen-tei#15

I've added a temporary shell script to TEI/P5/Test called testfo.sh, which calls ant tasks I've added to antruntest.xml to test the generation of PDFs via XSL:FO using FOP, using testbasic.odd. This transformation is currently broken, with the first error shown below (there will probably be several more once this is fixed). I suggest we raise and solve these errors on this ticket until the transformation works, then add some more complex ODDs than testbasic.odd, until we're confident odd-to-pdf through FO is working. Then work can return to the two tickets linked above, the first one of which needs a decision on whether this specific set of tests should be done as part of the regular P5 build tests (I think so myself, since these scenarios are built into the Oxygen plugin).

~~~~~
/tei/TEI/P5/Test/antruntest.xml:266: Fatal error during transformation using /home/mholmes/DiskStation/tei/Stylesheets/profiles/default/fo/to.xsl: Effective boolean value is not defined for a sequence of two or more items starting with a boolean; SystemID: file:/tei/Stylesheets/fo/fo_figures.xsl; Line#: 336; Column#: 23
~~~~~

**Comment by martindholmes** [comment]
Committed fix for this first bug in commit 68536b1. Amazingly, the FO conversion now completes successfully, but it is not valid, so FOP fails with a validation error:

<code>
[fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 6509:244)>org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 6509:244)
</code>

It's complaining about this (from testbasic.doc.fo):

~~~~~
<basic-link internal-destination="" text-decoration="underline"/>
~~~~~

and that's clearly wrong; a link should have both a destination and some content. I'll investigate this next.

**Comment by martindholmes** [comment]
The broken ref above results from this block of TEI Lite in tesbasic.doc.xml:

~~~~~
<row>
    <cell rend="odd_label">usage</cell>
    <cell rend="odd_value">
        <seg xml:lang="en">specifies the approximate percentage (by volume) of the text which uses
            this language.</seg>
        <table rend="attDef">
            <row>
                <cell rend="odd_label">
                    <hi rend="label" xml:lang="en">Status</hi>
                </cell>
                <cell rend="odd_value">
                    <seg xml:lang="en">Optional</seg>
                </cell>
            </row>
            <row>
                <cell rend="odd_label">
                    <hi xml:lang="en" rend="label">Datatype</hi>
                </cell>
                <cell rend="odd_value">
                    <tei:ref xmlns:tei="http://www.tei-c.org/ns/1.0" target="#"/>
                </cell>
            </row>
        </table>
    </cell>
</row>
~~~~~

which is obviously broken. So the problem doesn't seem to be in the FO conversion at all. The issue is that the processing of the datatype is wrong; and it looks like this is because the processing of `<dataRef name="nonNegativeInteger"/> is borked. This page demonstrates the problem:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-language.html

I've raised this as TEIC.TEI#1562.

**Comment by lb42** [comment]
In addition to the above error I am seeing loads of " [fop] WARNING: The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) " Unfortunately, I suspect we rely on this facility to produce acceptable layout of the complex tables which make up the display of element specs etc. So it may be that Sebastian's view that Apache FOP did not provide a good  enough implementation for that purpose is still valid.

**Comment by martindholmes** [comment]
Well, we'll find out. And we can always manage the table layout manually.

**Comment by martindholmes** [comment]
Committed a fix for the internal link bug in c8614d3. Now I'm seeing a problem with table cell count:

<code>
  [fop] SEVERE: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: The column-number or number of cells in the row overflows the number of fo:table-columns specified for the table. (See position 130895:12)
</code>

Investigating...

**Comment by martindholmes** [comment]
The next bug may be the fault of the code @sydb and I introduced recently to handle display of deprecation information. The context is a table which is specified as having two columns; a row appears like this:

~~~~~
<table-row>
    <table-cell border-after-style="solid" border-start-style="solid" padding="2pt"
        text-align="left">
        <block>
            <inline font-weight="bold">
                <basic-link
                    external-destination="url(http://www.tei-c.org/Activities/Council/Working/tcw27.xml)"
                    >Deprecated</basic-link>
            </inline>
        </block>
    </table-cell>
    <table-cell number-columns-spanned="2" border-after-style="solid" border-end-style="solid"
        border-start-style="solid" padding="2pt" text-align="left">
        <block>
            <inline>will be removed on 2017-03-01</inline>
        </block>
    </table-cell>
</table-row>
~~~~~

The second cell clearly should not have `@number-columns-spanned="2".

**Comment by martindholmes** [comment]
The problem I think lies in common/common_tagdocs.xsl line 3025 ff:

~~~~~
        <xsl:element namespace="{$outputNS}" name="{$cellName}">
          <xsl:if test="not($inline)">
            <xsl:attribute name="{$colspan}"
              select="
                if (ancestor-or-self::tei:attDef)
                then
                  1
                else
                  2"/>
            <xsl:attribute name="{$rendName}">
              <xsl:sequence
                select="
                  if (ancestor::tei:attDef) then
                    'odd_value'
                  else
                    'wovenodd-col2'"
              />
            </xsl:attribute>
          </xsl:if>
[...]
~~~~~

My guess is that the ancestor-or-self::tei:attDef test is failing in odd-to-lite but I'm not sure why yet.

**Comment by martindholmes** [comment]
I believe I've fixed that bug in de3f490. It was also generating an error in Guidelines output (look at the deprecation column for pVar in the current Guidelines release, which erroneously has cols="2"). The FO processing now completes, but I haven't yet had a chance to look at the PDF.

**Comment by martindholmes** [comment]
PDF looks pretty good! @lb42, the warnings about automatic table rendering prove not to be a problem. Try it and look for yourself:

<code>
cd [TEI]/P5/Test
./testfo.sh
</code>

then look at [TEI]/P5/Test/testbasic.doc.fo.pdf.

**Comment by lb42** [comment]
Well, not that good. The nested tables are coming out pretty illegible, and the links they contain are inoperative.

**Comment by martindholmes** [comment]
The cosmetic stuff is merely that; we can figure it out with a bit of work. The links to TEI datatypes are probably a result of the fact that nobody has touched the FO code since before the Pure ODD stuff was brought in. You can't expect the XSLT to update itself automatically.

Note to self: internal links to bibliography entries are broken too (see test27.fo).

**Comment by martindholmes** [comment]
@lb42 overlapping table cells should be fixed now.

**Comment by lb42** [comment]
Um, not quite. Look at page 4 (spec for &lt;abbr>)

**Comment by lb42** [comment]
I tried this also with tei_simplePrint.odd and tei_jtei.odd from the Exemplars folder. The overlapping text problem reappears in both, and not just in the specs. simplePrint has a couple of longish glossary-style lists which get badly messed up, and tei_jtei has a textual table which gets a bit confused. But overall, not at all bad!

**Comment by martindholmes** [comment]
Curses. Those are nested three tables deep, one for elementSpec, one for attDef, and one for valList. If this FO stuff were not so damnably with all the other rendering outputs through the /common/ modules, it would be easy to do something pragmatic like turning the valList into an actual list block, but something more gnarly will be necessary.

**Comment by martindholmes** [comment]
Actually, though, the combination of simplePrint.odd and testbasic.odd, if we can get all the bugs thrown up by those fixed, would be enough of a build test to satisfy me that the core code is working acceptably. jTEI is a different thing; we purposely wrote our own PDF output for that because we have specific requirements for the journal.

**Comment by martindholmes** [comment]
Tweaked the valList stuff so that looks OK now (p.4 of testbasic.doc.fo.pdf). Next is to look at the issues that show up in simplePrint. I've added simplePrint to the testfo.sh script in 8d80839, and I see an instance of the problem on p.33 of the rendered PDF. It looks to me that the same solution as I applied in the case of valLists would be appropriate here.

**Comment by martindholmes** [comment]
Added a fix in commit 62cbaf7 for `list[@type='gloss'] ` to match that for valLists. In both cases, the odd thing was the original assumption that lists with labels (which are naturally of varying length) could be rendered using a fixed-width label component. That mechanism will only really work for bullets and numbers. 

@lb42, do you see any further rendering issues (other than the broken links, which are a slightly larger problem) in testbasic or simplePrint?

**Comment by martindholmes** [comment]
Thanks Lou. I'll move onto these next.

**Comment by martindholmes** [comment]
I think images are fixed in commit 79b8686.

**Comment by martindholmes** [comment]
The missing quote marks are puzzling; the rendering uses the named templage makeQuote in common/common.xsl, which should be inserting the $preQuote and $postQuote strings around the quotes, but at the point when they're doing that, those variables seem to be empty. The variables are defined as curly single quotes in common/common_param.xsl, which is imported by fo/fo.xsl, and I can't find any place they're being overridden. Strange...

**Comment by martindholmes** [comment]
Not strange at all, it turns out. My own stupid fault, copying params over from the doclatex target in antruntest.xml. Quotes are now working as of TEIC/TEI commit a8f37b1.

**Comment by martindholmes** [comment]
Fixed the table on p. 40 in commit 850f668. The original column width calculation is crude; my hack simply discards its results completely when they result in one or more tiny columns. Someone could do a better job of adjusting the output when they have more time.

@lb42, do you see anything else broken in simplePrint?

**Comment by martindholmes** [comment]
The problem with internal links comes as a result of the links being constructed like this:

~~~~~
<basic-link internal-destination="teidata.enumerated" text-decoration="underline">teidata.enumerated</basic-link>
~~~~~

and the targets like this:

~~~~~
<block keep-with-next.within-page="always" id="TEI.teidata.enumerated" text-align="left" font-family="Times" font-size="14pt" font-weight="bold" space-after="3pt" space-before.optimum="9pt" text-indent="0em">5.5. teidata.enumerated</block>
~~~~~

where the `@id` attribute has a leading "TEI.", while the links don't. Don't know why it's so, but it shouldn't be too hard to fix.

**Comment by lb42** [comment]
Comparing the PDF produced by FO with that produced by LaTex suggests there is ample scope for aesthetic/readability improvements in the former, but it is at least now not broken. The links to teidata.objects dont work in the LaTex route either, by the way.

**Comment by martindholmes** [comment]
I agree there's a lot of work to do, and I will be raising a couple more tickets to refine some of the stuff I've done so far and look at some other things, but I think we're further forward. The link problem is at the odd2lite level so it will afflict every ODD-to-documentation transformation. I'm hoping to rope @sydb in tomorrow to help me figure it out. Once that is fixed, I think there's a strong argument for a new Stylesheets release, leading to a new stable plugin release, but we may also want to include P5, because we've tweaked a few things there.

**Comment by martindholmes** [comment]
I think those links are working now, and in my local build bug #203 is fixed, but it doesn't seem to be on the server. Still a bit of work to do...

**Comment by martindholmes** [comment]
Remaining to be done:

1. Passing the foEngine="fop" parameter into the transformation in antruntest.xml.

2. Revisit the optimizations I've made in working on this ticket to ensure that the ones which are designed to work around FOP limitations are only triggered when foEngine="fop".

3. Revisit the table column calculation algorithm. My "fix" for this involves giving up on the current algorithm when its results are unusable, but it should be possible to optimize it instead, such that no column is less than 10% of the width of the table.

4. Use foEngine="fop" to insert `@table-layout="fixed", to avoid the repeated error message from FOP saying it doesn't support the default "auto".

5. Investigate the few remaining broken links in the ODD-to-doc PDF, which seem to result from links targeting model references; almost all of these references apparently work, but there are a few exceptions which may result from some idiosyncracy in the original specs.

6. Figure out how best to integrate the FOP build tests (probably testbasic, Exemplars/tei_simplePrint, and Exemplars/tei_jtei) into the test process. Should it be part of the Stylesheets tests or the P5 tests? The FOP libs are currently in the P5 tree, but that may have been the wrong place to put them.

**Comment by lb42** [comment]
No 5 above is interesting. The broken links all seem to be to classes which don't have any members in the ODD being documented, and which one would not expect to see being referenced in the "members" list (except that detecting them in advance is non-trivial). In the LaTeX version, the name of the class appears but it is not formatted as if it were a link.

**Comment by martindholmes** [comment]
A simple approach, which would get us to the same place as the LaTeX output, would be to check whether a target id exists before creating a link to it. That would be a step in the right direction, but leaves us with the non-trivial problem, perhaps for another ticket. The Stylesheets learning group could get their teeth into that ticket, possibly, since it wouldn't be urgent.

**Comment by martindholmes** [comment]
1, 2, 4 and 5 should be handled in commit a56f067. I've also cleaned up a few more display issues with nested tables and glossary lists.

**Comment by martindholmes** [comment]
In addition to no. 3 above, I'll add:

7. Integrate the FOP hyphenation jar into the FOP lib folder to enable hyphenation. This requires checking licensing to ensure we're able to use the compiled jar from:

http://offo.sourceforge.net/

We should also check that it covers the languages we need, and test that it's found by FOP and is working.

**Comment by martindholmes** [comment]
@rvdb reports that when generating PDF documentation from the newly-PURE-ified tei_jtei.odd file that he's about to commit to the repo, the old figures.xsl bug is back:

> the PDF transformation is failing with following error in ${frameworks}\tei\xml\tei\stylesheet\fo\fo_figures.xsl:

~~~~~
    FORG0006: Effective boolean value is not defined for a sequence of two or more items starting with a boolean 
~~~~~

Since this is an official TEI customization, I think that makes the bug release-blocking.

**Comment by rvdb** [comment]
I've tested the PDF transformation (bleeding edge TEI-Oxygen plugin) for all ODD files in the Exemplars folder, and found some more errors.

- **`tei_enrich.odd`**:
When the `odd2odd.xsl` step is executed during the PDF transformation task, this is failing with following error in `${frameworks}\tei\xml\tei\stylesheet\fo\fo_figures.xsl`:

      FORG0001: Cannot convert zero-length string to an integer

- **`tei_tite.odd`** and **`tei_xlinclude.odd`**:
While the `odd2odd.xsl` step succeeds without errors, the FOP process reports errors due to malformed tables in the generated XSL-FO files:

      ERROR - net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: The column-number or number of cells in the row overflows the number of fo:table-columns specified for the table.

**Comment by martindholmes** [comment]
Thanks Ron. The FO processing needs a lot more work.

**Comment by hcayless** [comment]
Removed the Release Blocker label, as it sounds like there was not a regression.

**Comment by martindholmes** [comment]
I'm going to close this ticket since it's become completely unfocused, and most specific bugs on it have been fixed. There are still table-layout problems with FOP, but they're exemplified by a specific handy example in the tei_jtei.odd exemplar, so I'll raise a more specific ticket on that.
