### ISSUE TITLE
ant 1.8 complains about the zip64Mode attribute

### ISSUE THREAD

**Issue by bansp** [TEIC/Stylesheets#207]
Running Ubuntu 12.04 (time flies...) with ant 1.8.2 and getting the following during the `make` process:

> BUILD FAILED
> /home/piotr/projects/Stylesheets/epub3/build-to.xml:38: The following error occurred while executing this line:
> /home/piotr/projects/Stylesheets/common/teianttasks.xml:282: zip doesn't support the "zip64Mode" attribute

I gather that this is due to the old age of the base system (and more directly, to running ant 1.8 rather than 1.9), which I won't be able to modify for some time to come. 

Question: am I relatively safe just ignoring this, because I don't need epub conversions, or should I find some workaround because this error breaks more than just the epub conversion, please? Thanks!

**Comment by martindholmes** [comment]
I updated the main Jenkins server from 12.04 to 14.04 using "sudo do-release-upgrade -d", IIRC; it was pretty seamless. Is there anything keeping you at 12.04?

**Comment by bansp** [comment]
I don't think your server was as cluttered with extra stuff as this laptop is, and I can't afford to render it unusable (I travel too often), so I'm trying not to fix a thing not completely broken yet, and ant 1.9 is not a factor to push me across the threshold :-) But of course I recognize this as my own trouble, I was just wondering how bad my installation of the Stylesheets is now. 
(Tried manipulating the values of `zip/@zip64Mode` in common/teianttasks.xml, but the error was the same. It would have been a monkey's luck if that had helped...)

**Comment by bansp** [comment]
Ah, so the kludge for ant 1.8 is to remove the 4 occurrences `@zip64Mode` attributes altogether.

**Comment by martindholmes** [comment]
I just realized that if you have a recent version of Oxygen on the system, then you have a recent version of ant too, in [Oxygen]/tools/ant. You could call that instead.
