### ISSUE TITLE
values of key= in tagdoc content models should be links

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#209]
In a tagdoc, references to elements and classes from the “content model” portion of the tagdoc should be links to the tagdocs for those elements and classes. This should happen both during the build of P5 (see P5/Utilities/guildelines.xsl.model) and during customization (common/common_tagdocs.xsl), and of course the links are different in those two cases.

Note that, IIRC, in the pre-Pure ODD days this did happen, but only for HTML generation of the Guidelines — it generated bad links for customization, and nothing for PDF etc.

**Comment by martindholmes** [comment]
This appears to have been done for the Guidelines HTML, but it is broken for customizations:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-exemplars/html/tei_jtei.doc.html#listBibl

**Comment by martindholmes** [comment]
Looking at the linked customization, it appears that the links are now working OK, so @ebeshero and I are closing this.
