### ISSUE TITLE
P4 to P5 test is not a proper test

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#217]
The test of P4 to P5 conversion is:

~~~~~
test-p4top5:
	@echo BUILD: testing p4top5
	$(SAXON) -o:test17.tei test17.xml ../profiles/default/p4/from.xsl
	if [ $(REGENERATING) -ne 1 ]; \
		then diff  test17.tei expected-results/test17.tei; fi
	$(SAXON) A54031.tcp ../tcp/tcp2tei.xsl | xmllint --format - > A54031.xml
	if [ $(REGENERATING) -ne 1 ]; \
		then diff  A54031.xml expected-results/A54031.xml; fi
~~~~~

The second file is a TCP file, and in fact uses the tcp conversion code, so it's not strictly speaking converting P4 to P5 (although it's still a good test as far as I know). The first test converts a file which is not standard P4 at all; it has P5 features such as `@when` on `<date>`, it has `@url` instead of `@to` on `<xref>`, and it has some very weird `@ana` values. I haven't edited it because I'm not sure why it was chosen -- it seems to be a web document explaining email at Oxford authored by Sebastian in 2000 -- but it should either be fixed, or perhaps replaced by a genuine valid P4 document so that we do have one test which uses real P4.

**Comment by lb42** [comment]
It is a P4 file with Oxford extensions needed for web authoring. Don't ask. I'll look around for a better P4 document.

**Comment by martindholmes** [comment]
My Test2 setup is now using Lou's file. Closing.
