### ISSUE TITLE
XSL:FO page-sequence gets bad language attribute value

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#223]
The XSL:FO conversion produces (by default, with Test/test.xml) a `<page-sequence>` element withy `@language="en_US", which is ill-formed. Need to figure out where the language param is coming from, and process it appropriately to provide the correct value per https://www.w3.org/TR/2001/REC-xsl-20011015/xslspec.html#language, which points to RFC3066.

Assigning this to myself. Just raised the bug so I don't forget it.

**Comment by martindholmes** [comment]
Bug fixed for foEngine='fop' (which hates en_US) in commit 6cdfa80, but I'm leaving this open until I get a chance to test with some other engines. I believe it should always be en.

**Comment by martindholmes** [comment]
The Antenna House multilingual formatting example page:

https://www.antennahouse.com/XSLsample/multi.htm

shows "en" for English, and their uses of a region subtag use a dash, as we would expect.

**Comment by martindholmes** [comment]
And a RenderX tech support answer shows en-US too:

http://services.renderx.com/lists/xep-support/5169.html

**Comment by martindholmes** [comment]
While the FOP documentation on hyphenation shows a possible source of the confusion: "en_US.xml would be the file name for American English hyphenation patterns."

https://xmlgraphics.apache.org/fop/1.0/hyphenation.html

while the actual standard appears not to allow region subtags in the `@language` attribute at all:

https://www.w3.org/TR/2006/REC-xsl11-20061205/#d0e4626

which aligns with the errors that show up when you validate generated FO files in Oxygen. I now think the default should simply be "en", but I'll do a bit more digging around to see if there's anything in passivetex that might have given rise to en_US.

**Comment by martindholmes** [comment]
The passivetex code is littered with en_US, so it looks like we might have to preserve that value for passivetex. FOP, with the default OFFO hyphenation lib, chokes on en-US because no such language is included; there's "en" and "en-GB".

So at this point, I think the best approach would be:

1. Default to "en" for all processors except for passivetex; that's valid FO.
2. Continue to use "en_US" for passivetex; that's technically wrong, but shouldn't cause any problems with what seems to be a long-unmaintained codebase.

I think Council should sign off on this before I make the change.

**Comment by lb42** [comment]
I agree with you.

**Comment by martindholmes** [comment]
Pinged Council about this 2017-04-02; if no objections in the next few days, I'll go ahead and do this.

**Comment by martindholmes** [comment]
I've set this to 'en' in all cases as of commit 9b80ab3.

**Comment by martindholmes** [comment]
No reason to keep this open, since the bug appears to be fixed.
