### ISSUE TITLE
Inconsistent behaviour of built in transformations for JTEI

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#229]
[Not sure where this ticket goes but I'll put it here for now]. The oxygen framework comes with two very nice predefined transformation scenarios for JTEI documents. One goes to PDF, one to ODT. In each case, the output filename is constructed from the basename of the input file. However, for the PDF one only, it is assumed that the input file will have an extension of ".xml"; if this is not the case (if for example it's called "wibble.tei" or "wibble.jtei") the conversion fails because it cannot find "wibble.xml". This isn't the case for the ODT conversion, which will happily turn "wibble.anydamnthing" into "wibble.odt". Whichever behaviour is correct, the two should be consistent methinks.

**Comment by rvdb** [comment]
Thanks for pointing this out. This is too limited, indeed. I've found the cause in the ANT script driving the XSL-FO transformation, and will provide a fix soon.
