### ISSUE TITLE
docx to tei transform in Java project 

### ISSUE THREAD

**Issue by Vitaliy-1** [TEIC/Stylesheets#233]
Greetings, 

thanks for these stylesheets, they are great. I have already use them with Oxygen and OxGarage. For now I want to transform DOCX to TEI with Java for consequent processing. But I really don`t know how to do this. Can you help me to find a solution?

Here is what I already wrote for simple xlst with saxon:
```
public class TransformationXSLT {
    public static void oneFileTransform(String inputPath, String xsltPath, String outputPath) throws TransformerException {
        TransformerFactory tFactory = TransformerFactory.newInstance();
       
            Transformer transformer = tFactory.newTransformer(new StreamSource(new File(xsltPath)));
            transformer.transform(new StreamSource(new File(inputPath)),
                                  new StreamResult(new File(outputPath)));
        
    }
    public static void main(String[] args) throws TransformerException {
        //set saxon 
        System.setProperty("javax.xml.transform.TransformerFactory", "net.sf.saxon.TransformerFactoryImpl");
        oneFileTransform("test.xml", "test.xsl", "out.xml");
    }
}

```

It, obviously, work well for simple 1 file transformation. How can I modify this code to work with many stylesheets like docx2tei (compile with ant?) , supposing that document.xml from DOCX archive is already extracted?

**Comment by martindholmes** [comment]
Could you not take the ant build file here:

https://github.com/TEIC/Stylesheets/blob/dev/docx/build-from.xml

and call it from another ant file, passing all the files you need to convert? No need for Java code, surely.

**Comment by Vitaliy-1** [comment]
Greetings @martindholmes, 
Hmm, do not understand for sure. There is a need to create `build.xml`, that will evoke  transformation process through `build-from.xml`? Is there an example of such script?

The reason why I want to do this in Java, is because the result document will undergo a series of transformations. Including transformation to JATS XML and modifying the DOM structure.

**Comment by Vitaliy-1** [comment]
So, after manipulation, I have successfully evoked transformation from windows command line.  Simplify script in my case looked like this:

`java.exe -classpath "\path\to\ant-launcher.jar" "-Dant.home=\path\to\ant\and\saxon\" org.apache.tools.ant.launch.Launcher -f "path\to\build-from.xml" "-DinputFile=\path\to.docx" "-DoutputFile=\path\to\TEI-P5.xml" `

Suppose, there is a need to additionally correct  such classpathes, like `<classpath location="${oxygenlib}/saxon9ee.jar"/>` in build-from.xml. Can you give me a hint, how to do all this in Java? Where I can read about this? 

Thanks in advance :)

**Comment by martindholmes** [comment]
You've identified what I believe is a bug: saxon EE should only be invoked when the transformation is run from within Oxygen. I'll raise a ticket for this.

If you're not familiar with ant, and you'd rather write Java to do the job, then it would just be a question of having your Java code follow the same steps as the ant task does; much of the real work happens in teianttasks.xml.

**Comment by Vitaliy-1** [comment]
Problem solved. Several lines of code actually, but poor javadoc.
And also works fine with saxon9he.
