### ISSUE TITLE
saxon9ee.jar hard-coded into ant tasks?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#234]
@Vitaliy-1 has pointed out in #233 that the saxon9ee.jar is hard-coded into docx/build-from.xml. There are actually more than 20 instances of this use of the EE version of Saxon, and I think all of them could be replaced by the HE version for users who don't have a licence for Saxon or Oxygen. We would need to check whether the processes might be using EE-only functionality, and find ways to code around it.

**Comment by Vitaliy-1** [comment]
Saxon9he.jar works fine for DOCX to TEI and for TEI to JATS transformations.

**Comment by martindholmes** [comment]
Yes, I think it works fine for everything (otherwise a non-Oxygen install of the Stylesheets wouldn't be able to do all the transformations). My understanding is that ee was used because Oxygen has some special optimizations for ee which make it run more quickly; I don't know what the optimizations are -- perhaps they're a trade secret -- but I've encountered a couple of cases where they actually result in problems (https://github.com/TEIC/oxygen-tei/issues/15).

**Comment by ebeshero** [comment]
Note: this should be resolved with #308

**Comment by tuurma** [comment]
closed with 4195daa, not any more references to Saxon EE left
