### ISSUE TITLE
double slash in teitoodd --help 

### ISSUE THREAD

**Issue by bansp** [TEIC/Stylesheets#242]
Since I've just read that a new release is imminent, I'm quickly posting a symptom rather than investigating the cause:

when you do `teitoodd --help`, you can see the following at the bottom, note the double slash before `saxon9he.jar`:

    Options, shown with defaults:
    --saxonjar=/usr/share/xml/tei/stylesheet/lib//saxon9he.jar  # location of Saxon jar file
    --trangjar=/usr/share/xml/tei/stylesheet/lib/trang.jar  # location of trang jar file

**Comment by sydb** [comment]
Fixed in b77ac5f.
But what is this imminent release of which you speak?

**Comment by bansp** [comment]
Oh I thought I saw a mention of that, so I made sure to post this ticket before I left the office, just in case.
Well, if you don't know about it being imminent, then it most probably isn't :-)

**Comment by martindholmes** [comment]
@sydb I thought a release of the Stylesheets was due soon? We need to get a new version of the stable plugin out that fixes the bugs with PDF generation and a couple of other things.

**Comment by martindholmes** [comment]
@bansp I see this when I do bin/teitoodd --help in a current checkout of the dev tree of the Stylesheets:
~~~~~
  Options, shown with defaults:
  --saxonjar=/home/mholmes/WorkData/tei/Stylesheets/lib/saxon9he.jar  # location of Saxon jar file
  --trangjar=/home/mholmes/WorkData/tei/Stylesheets/lib/trang.jar  # location of trang jar file
~~~~~

**Comment by bansp** [comment]
Yep, Syd the Magician was there ;-)
