### ISSUE TITLE
ODD to XHTML|EPUB|DOCX|ODT transformations fail with the same error in functions.xsl

### ISSUE THREAD

**Issue by rvdb** [TEIC/Stylesheets#246]
When generating documentation for the pureODD version of [tei_jtei.odd](https://github.com/TEIC/TEI/blob/4a4cc532a80730bdb7f4f273f26f0be01a4a698f/P5/Exemplars/tei_jtei.odd) with the bleeding-edge Oxygen-TEI framework (version 3.1.95), following transformations all fail with the same error:

- TEI ODD XHTML
- TEI ODD EPUB
- TEI ODD DOCX
- TEI ODD ODT

The error reported is situated in `${frameworks}\tei\xml\tei\stylesheet\common\functions.xsl`:

    XPTY0004: A sequence of more than one item is not allowed as the first argument of translate() ("teix:", "eg:")

(Note how the PDF transformation also fails with a different error, which is reported in https://github.com/TEIC/Stylesheets/issues/205)

**Comment by martindholmes** [comment]
Do we just have two different prefixes defined for the examples namespace?

**Comment by rvdb** [comment]
Ah, indeed: there is an (unused) namespace declaration on the &lt;TEI> element:

    <TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:eg="http://www.tei-c.org/ns/Examples">

Yet, all example snippets declare their own (unprefixed) namespace:

    <egXML xmlns="http://www.tei-c.org/ns/Examples">

If I remove the `xmlns:eg="http://www.tei-c.org/ns/Examples"` declaration from the &lt;TEI> element, the transformations succeed.

**Comment by martindholmes** [comment]
It's not uncommon to end up with multiple prefixes for the same ns where multiple XSLTs and input docs are involved. We should still fix this, I think.

**Comment by rvdb** [comment]
I think the stylesheets should be able to cope with duplicate namespace declarations, indeed. Should I keep them in tei_jtei.odd as a reminder, or just remove the unused one?

I've had a quick (and tired) look at the offending code in `functions.xsl`; maybe a couple of bold suggestions:
- in the `tei:createSpecPrefix()` function, change the call to `<xsl:value-of select="translate(tei:getPrefix($ns,.),':','_')"/>` (https://github.com/TEIC/Stylesheets/blob/dev/common/functions.xsl#L1396) into:

      <xsl:value-of select="for $item in tei:getPrefix($ns,.) return translate($item,':','_')"/>

- or in the `tei:getPrefix()` function, only return the first in-scope prefix for a namepace (https://github.com/TEIC/Stylesheets/blob/dev/common/functions.xsl#L1407):

      <xsl:for-each select="in-scope-prefixes($here)[1]">

Either of these makes the error go away. I haven't been able to figure out where these functions are used exactly, what they do exactly, and I'm aware they might be used in a plethora of different contexts, so well aware that I might be talking rubbish, it could be a pointer...

**Comment by martindholmes** [comment]
Let's leave the namespace in the jtei ODD for the moment, but remember to remove it before the next release of TEI just in case. In the meantime, it's a simple test for the bug.

I don't really know what those functions are doing either. But this might be a nice little problem for our Stylesheets Co-operative Learning Group to look into.

**Comment by martindholmes** [comment]
Quick fix done for the graphics problem, to be committed by Syd; I will raise a separate ticket for some oddities in image rendering that still remain, and assign it to myself.

**Comment by martindholmes** [comment]
Added a fix for the second bug in https://github.com/TEIC/Stylesheets/commit/05502d1ad1f08c628d617d7196db57371e4f3b40.

**Comment by martindholmes** [comment]
I think this can be closed, assuming Mr Jenkins doesn't complain (he's slow today because it's the day for the Guidelines link checking job).

**Comment by martindholmes** [comment]
All seems good. Closing this.
