### ISSUE TITLE
pureODD to DTD processing of <content> is incorrect

### ISSUE THREAD

**Issue by rvdb** [TEIC/Stylesheets#247]
This is probably related to https://github.com/TEIC/Stylesheets/issues/219: when a pureODD file is transformed to DTD, the children of `<content>` are just output next to each other, without proper grouping and sequencing. For example:

    <elementSpec ident="test">
      <desc>a test element</desc>
      <content>
        <elementRef key="one"/>
        <elementRef key="two"/>
      </content>
    </elementSpec>

This is transformed into following incorrect DTD element declaration:

    <!ELEMENT test onetwo>

Only when the `<elementRef>` elements are wrapped in `<sequence>` (or `<alternate>`) wrappers, they are properly grouped in the DTD. Following pureODD snippet:

    <elementSpec ident="test">
      <desc>a test element</desc>
      <content>
        <sequence>
          <elementRef key="one"/>
          <elementRef key="two"/>
        </sequence>
      </content>
    </elementSpec>

..is transformed (correctly) into:

    <!ELEMENT test ((one,two))>

Yet, when `<sequence>` and `<alternate>` are siblings inside `<content>`, grouping is lacking as well in the generated DTD:

    <elementSpec ident="test">
      <desc>a test element</desc>
      <content>
        <sequence>
          <elementRef key="one"/>
          <elementRef key="two"/>
        </sequence>
        <alternate>
          <elementRef key="one"/>
          <elementRef key="two"/>
        </alternate>
      </content>
    </elementSpec>

...results in: 

    <!ELEMENT test ((one,two))(one|two)>

I think this illustrates that the pureODD --> DTD transformation should:
- wrap the contents of `<content>` in parentheses
- separate different child elements of `<content>` with a comma

**Comment by lb42** [comment]
Your example elementSpec is (or should be) invalid though: you can't have multiple elementRefs  which are not wrapped in either an alternate or a sequence. The schema permits it, but it shouldn't.

**Comment by rvdb** [comment]
Ah, shouldn't the content model for `<content>` be restricted, then? Or if it can't via ODD, a Schematron check could catch this, surely?

**Comment by martindholmes** [comment]
Sorry Ron, I should have caught that before merging. Too many things happening at once.

**Comment by rvdb** [comment]
No worries, the jTEI ODD is all right, Martin: I had wrapped the multiple `<elementRef>` elements in `<sequence>` where applicable to avoid this error, thus doing the right thing, apparently. 

I just tried to report this behaviour in this test case, but since the test case itself appears to be wrong, perhaps this ticket should just be deleted. I'd be happy to create a new ticket (or PR) suggesting a Schematron check flagging multiple `//content/elementRef` elements.

**Comment by martindholmes** [comment]
It's not just elementRef, is it? Presumably multiple instances of any of the children should be flagged?

**Comment by rvdb** [comment]
Meaning that `<content>` should contain no more than one child element? I'll have to leave judgment to the experts, but it seems plausible to me, and a perfect fit for a simple Schematron check.

**Comment by sydb** [comment]
It seems to me `@lb42` is at least partially correct, it should never be the case that more than one element from model.contentPart is a child of a given `<content>`. In which case it is the schema (and perhaps the prose — see [TEI 1459](https://github.com/TEIC/TEI/issues/1459)) that is incorrect, not the stylesheet.

But N.B., it is legal (I think) to have more than one element from elsewhere, particularly RELAX NG.

I believe the discussion of this should be on the ticket mentioned above in the Guidelines repo, not here. As there is nothing to “fix” here, closing this ticket.
