### ISSUE TITLE
Fatal error proccessing ODD file in Oxygen 18.1 build 2017020917

### ISSUE THREAD

**Issue by sderrick** [TEIC/Stylesheets#248]
System ID: /home/scott/Oxygen XML Editor 18-1a/frameworks/tei/xml/tei/stylesheet/odds/teiodds.xsl
Scenario: TEI ODD XHTML
XML file: /home/scott/workspace/mbel-work/schemas/mbel.odd
XSL file: /home/scott/Oxygen XML Editor 18-1a/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl
Document type: TEI ODD
Engine name: Saxon-PE 9.6.0.7
Severity: fatal
Description: XTTE0570: An empty sequence is not allowed as the value of variable $max
Start location: 2265:0
URL: http://www.w3.org/TR/xslt20/#err-XTTE0570

I can translate the ODD to a rnc file successfully using Oxygen 17.1, any newer releases it fails.  I've posted the problem on Oxygen's forum but they are not responding.

Is there a newer stylesheet available that will not fail?

**Comment by martindholmes** [comment]
You can try installing one of the TEI plugins. Try the stable plugin, following these instructions:

http://blogs.it.ox.ac.uk/jamesc/2014/04/02/auto-update-your-tei-framework-in-oxygen/

If that fails, and you're feeling adventurous, you can uninstall it and try the bleeding-edge version of the plugin that we use for testing the development branches of the TEI and Stylesheets; if you want to do that, email me at mholmes@uvic.ca and I'll send you the URL of the update file to use.

**Comment by lb42** [comment]
Happy to take a look at this if you post a copy of the odd causing problems!

**Comment by sderrick** [comment]
I installed the latest stable plugin and that fixed it! You guys are great!
