### ISSUE TITLE
issue with multiple schemaSpecs

### ISSUE THREAD

**Issue by peterstadler** [TEIC/Stylesheets#249]
So I want to have (and process) multiple `<schemaSpec>` within one ODD file. The schema says it's valid and Sebastian already implemented this in `odd2odd.xsl`, providing the param `$selectedSchema` -- Hurray!!

**But**: 
All changes in different `<schemaSpec>` to a given `<elementSpec>` (I've only tested it for `<elementSpec>` ) are accumulated (for the first `<elementSpec>`) or dropped (for all other `<elementSpec>`)

The following ODD snippet is a minimal example:

```xml
<body>
  <schemaSpec ident="oddex1" start="TEI">
    <moduleRef key="textstructure" include="TEI"/>
    <elementSpec ident="TEI" mode="change" module="textstructure">
      <desc xml:lang="en">foo</desc>
    </elementSpec>
  </schemaSpec>
  <schemaSpec ident="oddex2" start="TEI">
    <moduleRef key="textstructure" include="TEI"/>
    <elementSpec ident="TEI" mode="change" module="textstructure">
      <desc xml:lang="en">bar</desc>
    </elementSpec>
  </schemaSpec>
</body>
```

When you process this with `odd2odd.xsl` it will (correctly) pick up the first `<schemaSpec>`  (see  `odd2odd.xsl`  line 135) **but** add both `<desc>` from (oddex1 and oddex2) to the compiled ODD – resulting in duplicate text in all subsequent stages.

If you want to process the second `<schemaSpec>`, you can invoke saxon like 
```
saxon -s:$MY_ODD_SNIPPET$ -xsl:$PATH_TO$/odd2odd.xsl selectedSchema=oddex2
``` 
but will get another issue: the changed `<desc>` is dropped due to the failed test in line 508.

**My solution**:

Remove the `<xsl:template match="tei:elementSpec[@mode eq 'change']|tei:classSpec[@mode eq 'change']|tei:macroSpec[@mode eq 'change']|tei:dataSpec[@mode eq 'change']"
                mode="pass0">` starting at line 503 completely. I tested this with `make test`and it didn't fail :)

**But**:
Sebastian introduced this template rule in https://github.com/TEIC/Stylesheets/commit/cdb2d4ca523ec9def61ad87a2fe0c28fc27c01da and I bet he did it on purpose …

Can anyone shed some light on this ?

**Comment by peterstadler** [comment]
I added a branch (based on `dev`) with my suggested fix. Could someone please test her/his ODDs with this branch to see if it fails?

**Comment by peterstadler** [comment]
Just ran `make test` in the TEI/P5 and the Stylesheets directory without errors.

**Comment by martindholmes** [comment]
What's the use-case for multiple schemaSpecs?

**Comment by jamescummings** [comment]
@martindholmes Easy!  If you use things like specGrp and specGrpRef!

i.e. You might have two schemaSpecs with detailed customisations that are only different in a few places. You can define a set of specGrp elements which contain those differences and then use specGrpRef to point to them to include them.  Containing the schemaSpecs in the same document makes it nice and easy to have schemas that are just different stages of the same workflow.

Indeed, some of my former colleagues in Oxford wrote a number of schemas this way even with only one schemaSpec.  You embed the specGrp (which may contain  classRef classSpec constraintSpec dataRef dataSpec elementRef elementSpec listRef macroRef macroSpec moduleRef moduleSpec outputRendition schemaSpec specGrp specGrpRef) at the point in the documentation that is concerning that modification and then your schemaSpec is nothing but a set of specGrp elements which point to the actual declarations.  Having more that one schemaSpec in that kind of instance is even more attractive.

(I know you know most of this, I'm just documenting my thoughts that accompany this while answering ;-) )

**Comment by martindholmes** [comment]
Thanks @jamescummings. I'd forgotten the details of this. So in this case, you'd expect two different RNG files to be produced from the two schemaSpec elements, right?

**Comment by lb42** [comment]
Is an ODD processor handling such a monster expected to produce all, or one only, of the available schemas? How about the reference documentation/s ?

**Comment by jamescummings** [comment]
@peterstadler That seems to make sense to me.... But we should test it with more complex multiple-schemaSpec ODDs.  I'll try to whip one up in the next week or so as a test. (If I don't feel free to nag me!)

@martindholmes Yes. Though I'd expect the processing software to probably only let me produce one at once.  Though as Lou mentions, maybe it should produce all of it...

@lb42 I would expect it to produce the one from the xml:id of the schemaSpec identified by selectedSchema, but yes, all the documentation. (I don't think we have a way of saying this bit of documentation applies to this schemaSpec only, do we?)  I think when discussing multiple schemaSpecs with Sebastian once he said that just producing all of them in one go was "tricky" but I forget the reason why. Surely we could just loop over for-each schemaSpec, do all the schemaSpec stuff?  Maybe it was to do with the documentation output and naming of things? But that should be based on the schemaSpec's `@ident` in any case so there should be any conflict, right?

**Comment by peterstadler** [comment]
I wouldn't worry about the documentation right now but focus on the RelaxNG output. I see this ticket as a bug report for something that should work (i.e. multiple schemaSpecs are allowed in the Guidelines and the one ODD processor has an extra switch 'selectedSchema' for it) but currently fails for the aforementioned reason.

I proposed a fix in the branch `peterstadler-fix-multiple-schemaSpecs` and all tests succeeded but still I feel a little bit uncomfortable and would be very happy if someone could try with a more complex ODD (thanks in advance @jamescummings!)

**Comment by ebeshero** [comment]
Per pull request https://github.com/TEIC/Stylesheets/pull/343 F2F Washington subgroup tested the code against an ODD with multiple schemaSpecs (and multiple elementSpecs within one of those schemaSpecs). We have made some improvements to the original code so it can properly select among  multiple schemas when it's selected by parameter, and still merge multiple `*Spec` elements within it.

**Comment by raffazizzi** [comment]
Just a note from the Washington F2F: @sydb raised the issue that using `ancestor::` to look up for the selected `schemaSpec` may not work if `<specGrp>`s are present. However we tested that `<specGrps>` get placed where they're invoked by `<specGrpRef>` *before* the keys are generated. Therefore our fix works.
