### ISSUE TITLE
extraction of ISO schematron messes up Quick Fixes

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#250]
The `odds/extract-isosch.xsl` program does not know about the `sqf:` namespace, and thus not only does not extract Schematron Quick Fixes properly, it ends up generating an invalid Schematron file if the input ODD uses `<sqf:*>`.

(Note: the generation of Schematron **inside** the RELAX NG does not work properly with Quick Fixes, either, but at least the output is not made invalid. Fixing that is **not** part of _this_ ticket, though.)

**Comment by rvdb** [comment]
Don't know if it is relevant here, but `<sqf:*>` (and `<xsl:*>`) descendants of `<constraint>` are processed correctly by [`odds/odd2relax.xsl`](https://github.com/TEIC/Stylesheets/blob/dev/odds/odd2relax.xsl). For example, there are no problems at all for the  [`tei_jtei.odd`](https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_jtei.odd) file.

**Comment by sydb** [comment]
At first blush seems to have been fixed in c8abc44, and Mr. Jenkins did not complain. Thus closing.
