### ISSUE TITLE
DOCX to TEI transformation produces invalid TEI

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#262]
The test file Test/test39.docx is a large document consisting of a detailed explanation of how DOCX to TEI conversions work. In the Test/Makefile, this document is converted to TEI, and the result is diffed against expected-results/test39.xml. However, that file is invalid, and the test result that matches it is also of course invalid. There are 28 errors, including:

- `<head>` appearing as a child of `<table>` after its `<row>`s instead of before them
- `<cit>` with a direct child text node, whereas the text should be inside a `<quote>`
- poetry which is encoded as a series of `<lg>` elements instead of a series of `<l>`s
- drama segments in which `<sp>` elements are the only markup, containing both speaker names and spoken lines
- non-existent elements including `<fwCatch>`, `<fwSig>`, `<fwPageNum>` and `<fwHeader>`

All of these look easily fixable, especially the last one. Anyone who'd like to take on one of these specific issues as a way of getting into how the docxtotei conversion works could spin it off into a separate ticket and make a note here.

**Comment by martindholmes** [comment]
The same sorts of problems exist in Test/test-rtf2tei.docx and expected-results/test-rtf2tei.xml.

**Comment by lb42** [comment]
For the last one,  might be worth making two possible outputs: one which says e.g. <fw type="catch"> and anther that says e.g. <fw:catch>  assuming you agree with me that we need some tests that use non TEI namespaces.

**Comment by martindholmes** [comment]
This is testing the regular docxtotei conversion, though; presumably your average user who wants to turn their DOCX to TEI doesn't want to get a bunch of mysterious non-TEI elements? I agree that we need to do a bit more testing of how things in other namespaces are handled, but that should presumably be part of the ODD processing, not the regular conversion code.

**Comment by ebeshero** [comment]
@martindholmes Looking at your initial post on this thread, is this a good ticket for a pupil in the Stylesheets group? It looks appealing to me...

**Comment by martindholmes** [comment]
@ebeshero Actually Syd and I made a plan on Friday for the next Stylesheets group, which he's going to email out (if he hasn't already). These might be good targets for a future meeting though. In one sense you don't learn much about how people use DOCX in general, because as the wonderfully informative (but unhelpfully-named) Test/test39.docx file explains, you use a special template for Word to create your document, and you use styles which are named after TEI elements; when the converter encounters some text which is styled with the named style "tei:term" it outputs a TEI `<term>` element. The problem with the fw elements in the output is that for an fw, you not only need to signal the tag name, you also need to specify the `@type` attribute value; in the test document, this is done with a style of tei:fwSig, which the code is presumably supposed to be able to decode into `<fw type="sig>`, but it doesn't, it outputs `<fwSig>` instead. I think this was another work-in-progress that didn't quite get finished. The test document was authored by Tomaž Erjavec and Andrej Pančur in 2014; they may know much more about it. It also links to this converter:

http://nl.ijs.si/tei/convert/

which I assume is theirs.

**Comment by jamescummings** [comment]
I thought it was tei_elementName not tei:elementName that the docxtotei XSL looked for?

**Comment by martindholmes** [comment]
Not in the test document; it's a colon in the style names, and the result (see expected-results) shows that the XSLT is acting on the colon. It may also handle an underscore, although using both would seem a bit fragile.

On a side note, one thing I keep noticing is that many Xtotei transformations (including this one) seem to produce `<cit>` elements containing plain text instead of a `<quote>` element. Was this ever valid in TEI?

**Comment by martindholmes** [comment]
I've written to Tomaž to see if he knows anything.

**Comment by martindholmes** [comment]
Tomaž has worked on this and knows quite a bit -- they have their own profile which is an extension of the regular tranformation -- but doesn't have much time to commit. I think the bit which produces things like `<fwSig>` is most likely happening here:

https://github.com/TEIC/Stylesheets/blob/dev/docx/from/pass2.xsl#L345

where the call to tei:nameOutputElement() uses this:

~~~~~
  <xsl:when test="starts-with(@rend,'tei:')">
	  <xsl:value-of select="substring(@rend,5)"/>
	</xsl:when>
~~~~~

Really, it should check to see if the result is a valid TEI element name, and if not, find the longest match. It's not clear how the remaining bit could be massaged into an appropriate attribute value, though, so perhaps the whole idea of using a style called tei:fwSig in the DOCX is wrong.

**Comment by lb42** [comment]
The Makefile ought to invoke this transformation using `profile="jsi" ` since the profile has some special code to deal with the representation of eg `<sp>` elements; if we want to fix the residual problems (chiefly non-existent tei attributes and elements) probably the changes should be made in that profile.

**Comment by lb42** [comment]
I tweaked my local copy of profiles/jsi/docx/from.xsl to (a) generate fw type="foo" rather than fwFoo (b) suppress cell/@tei:align ; I also tweaked the Makefile to invoke this profile. With these changes the TEI generated is valid against TEI All. Cant check these changes in because of a conflict in odd2odd though.

**Comment by lb42** [comment]
Now checked in. Hope I haven't broken anything/.
