### ISSUE TITLE
Whitespace issues in processing of <address> children

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#264]
Arising out of work on #261: If an `<address>` element has children such as `<region>`, `<country>` etc., when it's processed into HTML, whitespace between these elements is lost so they're run together.

**Comment by ebeshero** [comment]
F2F (with @peterstadler @martinascholger @tuurma ) Testing to see if  removing xsl:strip-space in common.xsl fixes the problem...
