### ISSUE TITLE
jTEI ODT transformation omits author names from author info

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#268]
When author metadata is added to the "Author" section at the end of the ODT file, only the affiliation is actually processed; the author name is not included. Preceding line 175:

https://github.com/TEIC/Stylesheets/blob/dev/profiles/jtei/odt/odt.common.xsl#L175

I think there should be this:

~~~~~
<text:p text:style-name="teiPara">
   <xsl:apply-templates select="name"/>
</text:p>
~~~~~

Ron, I'll assign this to you in case there's something obvious I'm missing -- perhaps the name is omitted on purpose for some reason?

**Comment by rvdb** [comment]
You're right of course, I've added the missing bits.
