### ISSUE TITLE
teianttasks.xml syntax error in L.24?

### ISSUE THREAD

**Issue by frakel** [TEIC/Stylesheets#288]
Hi, 
the line 24 `<property name="tempPrefix">build</property>` in */common/teianttasks.xml* produces the following error:
```
stylesheet/common/teianttasks.xml:24: The <property> type doesn't support nested text data ("build").
```
Should this line 24 not be  `<property name="tempPrefix" value="build"/>` ??
At least for me the latter prevents ant from breaking the build process.

Thank you. --franz

**Comment by jamescummings** [comment]
This is at https://github.com/TEIC/Stylesheets/blob/dev/common/teianttasks.xml#L24 (just adding for easy look up for those checking).

**Comment by peterstadler** [comment]
https://ant.apache.org/manual/Tasks/property.html suggests that both methods (`@name`/`@value` or `@name`/`nested text`) should work. And indeed, line 24 hasn't changed for 5 years, so I would have expected that 'error' to surface much earlier. 

Can you tell us a little bit more about your operating system and ANT version, maybe there is something hidden?

**Comment by frakel** [comment]
I'm running *Apache Ant version 1.7.1 compiled on May 10 2016* on *centos-release-6-4.el6.centos.10.x86_64*

But I was not aware that the `ant.TraXLiaison` library was missing, and after installing it the aforementioned tweak in *teianttasks.xml* was no longer necessary
