### ISSUE TITLE
improvements to extract-isosch.xsl needed

### ISSUE THREAD

**Issue by sebastianrahtz** [TEIC/Stylesheets#29]
Two improvements still needed for the new, improved extract-isosch.xsl:
1. When an "isosch" constraint is a descendant of a 〈classSpec type="model"〉 but does not have a 〈sch:rule〉, the generated rule does not have the right context=.
1. When an @validUntil occurs on any of the following, it is not processed.
   classSpec
   constraintSpec
   macroSpec
   moduleSpec
   classSpec//valItem

Note (on #2): there is also no processing when @validUntil is on the following, but in these cases I, at least, don't know what kind of Schematron rule we would want in these cases.
schemaSpec (what does that mean?)
valDesc
valList

**Comment by martindholmes** [comment]
I think we're going to need @validUntil on `<defaultVal>` too, since we're going to be deprecating a lot of `<defaultVal>`s in the next little while.

**Comment by sydb** [comment]
Also, the text node child of a <tei:desc> child of <tei:constraintSpec> ends up as plain text inside a <sch:pattern>, which of course is a no-no.
