### ISSUE TITLE
BUILD FAILED: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl

### ISSUE THREAD

**Issue by frakel** [TEIC/Stylesheets#290]
Since a few days I am trying to get the Stylesheets package up and running on a
Linux (Centos flavoured) system but continuously get the following error msg:

```
teianttasks.xml:386: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
```

According to Saxon/Michael Key this should be solved by correctly setting the CLASSPATH
variable. I included the `Stylesheets-dev/lib/saxon9he.jar` into the CLASSPATH.
But this did not the trick as I expected anyways. Since I did a `make install` which
installed everything nicely to `/usr/bin` (binaries) and
`/usr/share/xml/tei/stylesheet` (libraries and modules), the latter being the
default path for the saxon and trang libraries according to `teitorelaxng --help`:

```
 Options, shown with defaults:
  --saxonjar=/usr/share/xml/tei/stylesheet/lib/saxon9he.jar  # location of Saxon jar file
  --trangjar=/usr/share/xml/tei/stylesheet/lib/trang.jar  # location of trang jar file
``` 

That's maybe the reason why including the
`--saxonjar=/usr/share/xml/tei/stylesheet/lib/saxon9he.jar` option wont change anything
of the general problem since this should be found anyway by default.

However, calling the `teitorelaxng --debug --localsource=../mei/source/driver.xml --odd myodds/mei-DME.odd` throws the following error

```
    [...]
    [echo] Do ODD expand processing (schema )
     [xslt] Using class org.apache.tools.ant.taskdefs.optional.TraXLiaison
     [xslt] Processing ./myodds/mei-DME.odd to ./myodds/mei-DME.odd.processedodd
     [xslt] Loading stylesheet /usr/share/xml/tei/stylesheet/odds/odd2odd.xsl
     [xslt] Failed to process ./myodds/mei-DME.odd

BUILD FAILED
/usr/share/xml/tei/stylesheet/relaxng/build-to.xml:29: The following error occurred while executing this line:
/usr/share/xml/tei/stylesheet/common/teianttasks.xml:386: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
    [...]
```

Maybe there is someone out who has experience with running the TEI Stylesheets on a
Linux/Centos system .

Any ideas on how to avoid this error are very much appreciated ...

**Comment by martindholmes** [comment]
What version of ant do you have installed?

**Comment by frakel** [comment]
Apache Ant version 1.7.1 compiled on May 10 2016

**Comment by martindholmes** [comment]
Could you try updating to a more recent version? My machines seem to have been on 1.9+ for some years now, and I seem to recall some issue with 1.7 years ago.

**Comment by frakel** [comment]
Oh yes, sorry for not answering immediately. I finally could update Ant to V. 10 and this did the trick. 

Apparently this problem arises only with Ant version 1.7. However, this is the default version that comes with Centos at the moment...

**Comment by martindholmes** [comment]
Thanks for letting us know -- I'll close this now, since version 1.7 was superseded over seven years ago. I think it might be worth raising a bug with the CentOS team to get their package updated. :-)
