### ISSUE TITLE
odd2odd.xsl: invalid Base URI

### ISSUE THREAD

**Issue by frakel** [TEIC/Stylesheets#291]
I'm trying to do the following:
```
$ cd /home/franz/Customization
$ teitorelaxng --localsource=./mei/source/driver.xml --odd ./myodds/mei-DME.odd
```

but unfortunately the build fails here `odd2odd.xsl; Line#: 243` with the following message:

```
using /home/franz/Customization/mei/source/driver.xml as default source
Convert mei-DME.odd to /home/franz/Customization/myodds/mei-DME.odd.relaxng (tei to relaxng) using profile default
     [echo] Do ODD expand processing (schema )

BUILD FAILED
/usr/share/xml/tei/stylesheet/relaxng/build-to.xml:29: The following error occurred while executing this line:
/usr/share/xml/tei/stylesheet/common/teianttasks.xml:386: Fatal error during transformation using /usr/share/xml/tei/stylesheet/odds/odd2odd.xsl: Base URI {file:/home/franz/Customization/...} is invalid: Illegal character in path at index 33: /home/franz/Customization/myodds/"/home/franz/Customization/mei/source/driver.xml"; SystemID: file:/usr/share/xml/tei/stylesheet/odds/odd2odd.xsl; Line#: 243; Column#: 25
```

Why is odd2odd.xsl trying to build a path like `/home/franz/Customization/myodds/"/home/franz/Customization/mei/source/driver.xml"`?
Is this a bug or am I overlooking something? 
Thanks for pointing me to the right direction!

**Comment by hcayless** [comment]
Would you mind sharing the ODD you're using? Best guess at the moment is something funny in the `@source` on the schemaSpec. But seeing the ODD you're using would help us rule that in or out.

**Comment by lb42** [comment]
I have noticed that the teitoxxx scripts are in general a bit unhappy with relative URLs

**Comment by sydb** [comment]
@frakel, can you provide us with your mei-DME.odd file, or any other ODD file that produces this error?

**Comment by frakel** [comment]
[SOLVED] In the meantime I ran the tools on OS X where I had absolutely no build problems. When I came to run it on CentOS again I tried with a fresh install of TEIC/Stylsesheets and miraculously all the problems where gone also on the Linux system. Unfortunately I cannot tell why ...
...sorry for not answering that long...
