### ISSUE TITLE
error showing author etc

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#293]
I get a run-time error (function returns wrong kinda thing) when I do the following in oXygen 19.1 using the TEI add-on v. 7.0.0.

1. Open test_function_return.xml from [attached tfr.zip](https://github.com/TEIC/Stylesheets/files/1444175/tfr.zip)
(important bit is that it is a TEI document with a teiHeader/fileDesc/titleStmt/editor)
1. Config transform scenario
1. copy “TEI P5 XHTML”
1. edit new scenario, and set parameter "showTitleAuthor" to "true"
1. run new scenario

I get the same error when running `saxon -xsl:profiles/tei/html/to.xsl -s:/tmp/test_function_return.xml showTitleAuthor=true > /tmp/test_function_return.html` on the command line.

I am not sure, but it looks to me like the following functions have an `@as=node()*`, but actually return a string. Is this a run-time error or not? (Have these never been tested?)

#### Functions listed in order they appear in Stylesheets/common/functions.xsl

- tei:generateTitle() [maybe, depending on what applied templates return]
- tei:generateMetadataTitle()
- tei:generateEditor() [causes the **error above**]
- tei:generateAuthor [not sure: does `<xsl:sequence>` cast items in the sequence?]
- tei:generateMetadataAuthor()
- tei:generateRevAuthor()
- tei:generateRevDate()
- tei:generatePublisher()
- tei:makeDescription() [maybe, depending on what applied templates return]
- tei:generateDocumentationLang()
- tei:makeGloss [maybe, depending on what applied templates return]
- tei:whatsTheDate() [actually this one is `as=node()+`]

But I must be wrong about this, because tei:generateEditor() is only called from one place (inside Stylesheets/html/html_header.xsl), and tei:generateAuthor() and tei:generateRevAuthor() are called just before it in a similar context, and they don’t cause errors first.

**Comment by peterstadler** [comment]
I believe the error to be on line https://github.com/TEIC/Stylesheets/blob/f0f9af35c9195972d4835eb4237e4bf66555b397/common/functions.xsl#L732 where I would change the `<xsl:sequence select="tei:i18n('and')"/>` to `<xsl:value-of select="tei:i18n('and')"/>` because the latter does construct a text node where the former outputs the atomic value.

**Comment by ebeshero** [comment]
Look for functions that have an `@as="node"` and a `descendant::xsl:sequence`

**Comment by martindholmes** [comment]
Functions which have return type of node() but also have xsl:sequence in them somewhere:

~~~~~
common/functions.xsl
Description: as="node()*" name="tei:generateEditor"
XPath location: /xsl:stylesheet[1]/xsl:function[22]
Start location: 720:3
End location: 743:18

common/functions.xsl
Description: as="node()*" name="tei:generateAuthor"
XPath location: /xsl:stylesheet[1]/xsl:function[23]
Start location: 747:3
End location: 777:18

common/functions.xsl
Description: as="node()*" name="tei:makeDescription"
XPath location: /xsl:stylesheet[1]/xsl:function[40]
Start location: 1110:3
End location: 1229:18

html/html.xsl
Description: as="node()*" name="tei:processRendition"
XPath location: /xsl:stylesheet[1]/xsl:function[1]
Start location: 221:3
End location: 248:18

odt/grouping.xsl
Description: as="node()*" name="mf:group"
XPath location: /xsl:stylesheet[1]/xsl:function[1]
Start location: 57:2
End location: 84:17

markdown/markdown-to-tei.xsl
Description: as="node()*" name="tei:parseString"
XPath location: /xsl:stylesheet[1]/xsl:function[2]
Start location: 97:2
End location: 166:17

mediawiki/mediawiki-to-tei.xsl
Description: as="node()*" name="tei:parseString"
XPath location: /xsl:stylesheet[1]/xsl:function[2]
Start location: 102:2
End location: 171:17
~~~~~

**Comment by martindholmes** [comment]
The reported bug no longer exists; in commit 7b9dc822 I just fixed a missing space arising out of the original fix; and I don't think a vague notion of examining functions when there are no reported errors coming from them is worth keeping a ticket open for. Closing this.
