### ISSUE TITLE
Minor rendering issue in HTML documentation output

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#296]
If you look here:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.measurement.html

you'll see that there's no space between the suggested value token and its parenthesized gloss. There should be a space in there.

I had a shot at this and was working in tei:renderGloss() in common/functions.xsl (IIRC) but the fallout for non-HTML output was so extensive I rolled it back.

**Comment by martindholmes** [comment]
Discussing with @sydb: 1) Why render this list at all, when the suggested values are rendered below; and 2) in the rendering of the suggested values below, the ident and the gloss are offset, which is confusing.

**Comment by martindholmes** [comment]
The makeDescription() function at line 1110 in common/functions.xsl should have a new boolean parameter called "showMiniList", which should be false by default. Then all contexts in which this function is called need to be tweaked to add the extra param. The only place where we know we need it to be true is in the generation of RELAX NG; other than that, it should be false, as far as we know.

**Comment by martindholmes** [comment]
Work is happening in this branch:

https://github.com/TEIC/Stylesheets/tree/bug296makeDescription

Pull request coming soon.

**Comment by martindholmes** [comment]
There is still the rendering ugliness in chapter pages -- see this (scroll down a bit):

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONANU

So we can't close this ticket yet.

**Comment by martindholmes** [comment]
I think I've fixed the spacing issue, but we need to see it go through Jenkins to confirm there are no ill-effects for PDF generation.

**Comment by martindholmes** [comment]
Could someone do my pull request?

https://github.com/TEIC/Stylesheets/pull/307

**Comment by hcayless** [comment]
Done. I think if it looks good in the Jenkins builds, then it can get merged into the release.

**Comment by martindholmes** [comment]
Don't know how I missed that fix; I tested it locally. Sorry folks.

**Comment by hcayless** [comment]
No worries. It was easily fixed. The PDF looks ok to me (generated locally)

**Comment by martindholmes** [comment]
Behaviour is unchanged in the PDF. Interestingly, the suggested value list doesn't show up in the prose chapter output, but it turns out that it didn't before either.

I think this can be merged for release.
