### ISSUE TITLE
Schematron in RELAX NG output

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#335]
@rvdb observes on [a TEI ticket](https://github.com/TEIC/TEI/pull/1818#issuecomment-420674325) that the Schematron that is inside the RELAX NG output of ODD generates an error when processed by oXygen that makes him think the query binding is set to XSLT 1.0.

This probably isn’t actually the case, I notice, because he has other constructs (e.g., “some $i in …”) which would fail in XSLT 1.0. But there is still a problem in there, and it would still be a good idea (if it is even possible) to indicate that the query binding should be XSLT 2.0 (or 3.0).

**Comment by rvdb** [comment]
On further investigation, it seems that Schematron doesn't provide a mechanism for specifying the query binding when Schematron rules are embedded in another schema instance (RelaxNG, XML schema). Yet, Oxygen has an "[Embedded rules query language binding](https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/schematron-preferences-page.html#schematron-preferences-page__embedded-rules-query-language)" setting that can be set to `xslt3` from Oxygen-17.1 onwards; Oxygen-15 supports up to `xslt2`.

So, given the fact that the target languages don't support a syntactic means to express the query binding for embedded Schematron rules, I'm not sure if it makes sense to be able to specify it in an ODD, apart for pure documentation purposes.

**Comment by sydb** [comment]
Thank you **very** much for looking into this, @rvdb.

IMHO the primary method for using Schematron from ODD is to generate a free-standing Schematron schema using the odds/extract-isosch.xsl program, rather than to generate a RELAX NG grammar and use the Schematron embedded within. The free-standing schema does have a `@queryBinding` attribute, although it is currently hard-coded in odds/extract-isosch.xsl.

**Comment by sydb** [comment]
Without diving back into the details, my quick take is that there is nothing to be done _in the Stylesheets_ themselves, but that we should be documenting this behavior somewhere obvious.

**Comment by sydb** [comment]
See conversation in [#2330](https://github.com/TEIC/TEI/issues/2330).
