### ISSUE TITLE
doctotei.xsl unable to work with .docx files from browser version of Word?

### ISSUE THREAD

**Issue by Cutuchiqueno** [TEIC/Stylesheets#341]
When I try to make a `.docx` to TEI P5 transformation of a file I created and downloaded from the browser version of Word I get the error:

    Processing terminated by xsl:message at line 180 in docxtotei.xsl; SystemID: file:/home/firestarter/opt/Oxygen%20XML%20Editor%2020/frameworks/tei/xml/tei/stylesheet/docx/from/docxtotei.xsl; Line#: 180; Column#: 31

The referenced line tries to make use of the `$relsFile` variable defined at the beginning of `doctotei.xsl`. The variable definition is:

    128 <xsl:variable name="relsFile"  select="concat($wordDirectory,'/word/_rels/document.xml.rels')"/>

And here is the problem. I looked into the`.docx` archive and found out that this archive does not create a `document.xml` and `document.xml.rels` but a `document22.xml` and a `document22.xml.rels`. 

Consequently,

    179: <xsl:if test="not(doc-available($relsFile))">

fails.

I have not tested if Word Online always produces variations of the naming convention of `document.xml` and if the variation itself is consisten. However, it seems to do so sometimes and for those cases the stylesheet can not be used.

**Comment by peterstadler** [comment]
A quick search reveals other software faces the same problem: https://github.com/PHPOffice/PHPWord/issues/1253 (there is also a test file attached)

Echoing [a comment there](https://github.com/PHPOffice/PHPWord/issues/1253#issuecomment-364571249), "the best way would be to read the file names from [Content_Types].xml instead of hardcoding it."

**Comment by hcayless** [comment]
I can't replicate the problem. Perhaps the online version of Word doesn't do this anymore?
