### ISSUE TITLE
TEI ODD to DTD fails

### ISSUE THREAD

**Issue by laurentromary** [TEIC/Stylesheets#345]
System ID: /Users/romary/Documents/Workbench/IFIPSpecifications/Specification/out/SpringerBook.rng
Scenario: TEI ODD to DTD
Build file: /Users/romary/Library/Preferences/com.oxygenxml/extensions/v20.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/dtd/build-to.xml
Document type: TEI ODD
Engine name: ANT
Severity: fatal
Description: Transformation failed. /Users/romary/Library/Preferences/com.oxygenxml/extensions/v20.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/common/teianttasks.xml:386: java.lang.NoClassDefFoundError: ro/sync/basic/util/Crypto

**Comment by martindholmes** [comment]
@laurentromary Could you try this:

1. Duplicate the scenario in Oxygen.

2. Go to the Libraries section.

3. Delete Saxon EE, and replace it with Saxon HE instead.

Does that work? We've found problems with scenarios that use EE before.

**Comment by martindholmes** [comment]
Could you try simply deleting the saxonee? I think if you do that, HE will be used instead.

**Comment by lb42** [comment]
Have you tried using the teitodtd command? And could you make the ODD source available for testing?

**Comment by laurentromary** [comment]
Are there instructions somewhere so that I make a test? Here's my ODD (you'll guess the application domain). The disruption may also come from Oxygen. Let us inquire.
[SpringerBook.xml.zip](https://github.com/TEIC/Stylesheets/files/2635661/SpringerBook.xml.zip)

**Comment by laurentromary** [comment]
Note that it works on Oxgarage.

**Comment by lb42** [comment]
Definitely a problem in your oXygen installation.  I tried it with my installation of oxyGen 20.0 and it works fine

Executing:
"/home/lou/Oxygen XML Editor 20/jre/bin/java" -Dfile.encoding=UTF-8 -Xmx256m -classpath "/home/lou/Oxygen XML Editor 20/tools/ant/lib/ant-launcher.jar" "-Dant.home=/home/lou/Oxygen XML Editor 20/tools/ant" org.apache.tools.ant.launch.Launcher -lib "/home/lou/Oxygen XML Editor 20/classes" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygen.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygenAuthor.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygenDeveloper.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygenEclipse.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygenAuthorEclipse.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygenDeveloperEclipse.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/resolver.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/xercesImpl.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/saxon9ee.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/saxon.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/xml-apis-ext.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/log4j.jar" -lib "/home/lou/Oxygen XML Editor 20/lib/oxygen-basic-utilities.jar" -f "/home/lou/.com.oxygenxml/extensions/v20.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/dtd/build-to.xml" "-DinputFile=/home/lou/Downloads/SpringerBook.xml" "-DoutputFile=/home/lou/Downloads/out/SpringerBook.dtd" "-Dprofile=default" "-Dlang=en" "-Doxygenlib=/home/lou/Oxygen XML Editor 20/lib" "-DdefaultSource=file:/home/lou/.com.oxygenxml/extensions/v20.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/odd/p5subset.xml" "-Dwebhelp.trial.license=no"

Buildfile: /home/lou/.com.oxygenxml/extensions/v20.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/dtd/build-to.xml

go:
     [echo] Do ODD expand processing (schema ${selectedSchema}) 
     [xslt] Processing /home/lou/Downloads/SpringerBook.xml to /home/lou/Downloads/SpringerBook.xml.processedodd
     [xslt] Loading stylesheet /home/lou/.com.oxygenxml/extensions/v20.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/odd2odd.xsl
     [echo] XSLT generate dtd files
     [xslt] Processing /home/lou/Downloads/SpringerBook.xml.processedodd to /home/lou/Downloads/out/SpringerBook.dtd
     [xslt] Loading stylesheet /home/lou/.com.oxygenxml/extensions/v20.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/profiles/default/dtd/to.xsl

oddcleanup:
   [delete] Deleting: /home/lou/Downloads/SpringerBook.xml.processedodd

dist:

BUILD SUCCESSFUL
Total time: 16 seconds

The process finished with exit code: 0

**Comment by martindholmes** [comment]
Works for me on Oxygen 20.1 build 2018101517 with the bleeding edge plugin.

**Comment by martindholmes** [comment]
It also works if I force the use of saxon9he rather than EE. I remembered that you don't do that by removing saxon9ee itself; you remove the oxygen.jar file from the libs, and that forces the fallback to HE. Can you try that?

**Comment by laurentromary** [comment]
Thanks you all. I will carry tests step by step, resorting to OxGarage to generate the thing in emergency.
I now observe that macro.anyXML is now transformed into EMPTY in DTD instead of ANY, which is a real issue. Have you also observed this? Shall open another ticket?

**Comment by lb42** [comment]
macro.anyXML is rather differently expanded in recent versions of ODD and I am not at all surprised that it doesn't do what it used to do. Probably a quick practical fix would be to compile your ODD against an older version of the Guidelines, using the @source attribute.

**Comment by peterstadler** [comment]
Just tested both with OxGarage and locally with Oxygen 21.1. and both produced a valid DTD without any further ado. 

So closing here, but feel free to reopen if the error resurfaces.
