### ISSUE TITLE
conversion of hand in p4top5

### ISSUE THREAD

**Issue by sebastianrahtz** [TEIC/Stylesheets#35]
A P4 document containing `<hand xml:id="RG" style="ink correction" ink="black" character="regular" first="yes" resp="eds"/>`
gets converted to `<handNote xml:id="BG" style="typewritten" medium="black" character="schooled" first="no" resp="#eds"/>` using the default p4top5 stylesheet used by oxgarage which is invalid: @character and @first are not available on `<handNote>`

**Comment by lb42** [comment]
Looking at this again, I see no need for action. JC fixed the stylesheet to handle these weirdo attributes back in 2013-11, if we are to believe the source. I fixed a spelling mistake, and am closing this ticket forthwith.
