### ISSUE TITLE
Extra space before semicolon in list of suggested values in the RELAX NG

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#357]
In the annotations that list the (suggested|sample) values include in the RELAX NG there is an extra space before the separating semicolon after a value iff there is a `<gloss>` for that value.

**Comment by sydb** [comment]
@martindholmes and I have found the source of the problem, which is the `tei:makeGloss()` function in common/functions.xsl, as called from line 1199.

**Comment by peterstadler** [comment]
is that related or maybe introduce by #137 ?
(just for reference of the issue)

**Comment by martindholmes** [comment]
I'm pretty sure it wasn't introduced by #137's fix, because it already appears in the quoted text which forms part of the bug report in #137. :-)

**Comment by sydb** [comment]
Stylesheets group discussed this. We think the best idea is to change tei:makeGloss() so that it returns a single string (rather than node()*), which has no leading or trailing space; and change the 6 places where tei:makeGloss() is called so each expects that (a single string w/o leading or trailing whitespace). We also think this is the hardest fix to implement.

Easier would be to change the one place where tei:makeGloss() is called that causes **this** problem. (Roughly line 1198 of common/functions.xsl.) Which is what we ended up doing. Note that we had to use `<value-of>` rather than `<sequence>`, as the latter serializes the items in the sequence with a space between ’em.

**Comment by martindholmes** [comment]
I think the merge of Peter's pull request to fix the broken build has undone this fix. Needs to be re-implemented. I'm not sure why this happened.

**Comment by peterstadler** [comment]
That's hopefully not the case though I admit that I tweaked the processing a little bit in 
f4e343d (but referenced it here properly ;) 
The rest of the change from 7f30618 is untouched, see https://github.com/TEIC/Stylesheets/blob/f4e343dbb264d4ab968e3c7775fcd720018fa592/common/functions.xsl#L1201

**Comment by peterstadler** [comment]
@martindholmes can you give an example where you see that extra space before the separating semicolon?

**Comment by martindholmes** [comment]
Sorry @peterstadler, my mistake. My Test2 expecte-results were out of date.
