### ISSUE TITLE
OxGarage Does Not Preserve Manual Page Breaks in TEI P5

### ISSUE THREAD

**Issue by mysheepb** [TEIC/Stylesheets#358]
It seems that OxGarage does not keep the manual page breaks in DOCX or ODT documents when converting to TEI documents. If I want to keep the manual page breaks in TEI documents, using the <pb /> tag, what should I do? Can I modify a "profile" or code for this purpose?

**Comment by peterstadler** [comment]
I took a look at the Stylesheet `odttotei.xsl` and think I can up with a solution. PR coming …

**Comment by mysheepb** [comment]
That's great! Thank you so much for your help!

**Comment by peterstadler** [comment]
I just created the PR #359. Feel free to try it out—Feedback much appreciated!

Anyway, thanks for spotting and notifying!

**Comment by mysheepb** [comment]
I have tried the fix and it works well! Thanks a lot!
