### ISSUE TITLE
egXML examples need the egXML namespace in output

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#361]
@sydb and @martindholmes looking at egXML discovered that Guidelines examples of `<egXML>`:

https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-egXML.html

don't show the crucial examples namespace. Anyone copy-pasting from the examples will have a problem with this. It's slightly tricky to implement, but it's pretty important to show the xmlns on the element because that's what causes something to be processed as an example rather than a real instance. So egXMLs which are inside egXMLs (i.e. serving as examples) need to be processed in such a way that the xmlns is output on them.

**Comment by sydb** [comment]
Note that this is similar to #118.

**Comment by martindholmes** [comment]
Should we close it? That other one hasn't had much love, though.

**Comment by lb42** [comment]
Not really : 118 is complaining about the *invalidity* of a file which includes an egXML inside an egXML. This one is complaining that the examples don't show the correct use of namespace. To address that point, I note that (a) there is a comment immediately ahead of the first example in https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-egXML.html reminding you that a namespace declaration is needed (b) there is a third example which does include a namespace declaration. The fact that this third example gets away with it by being inside a CDATA block is slightly annoying, but for pedagogic purposes (as raised on this ticket) it's immaterial. So I'd suggest changing the examples to use a CDATA block.

**Comment by sydb** [comment]
While I see @lb42’s point (we could get away with just improving the nearby prose that says “use the namespace” and using CDATA marked sections), I’m inclined to say those are good temporary hacks that we should use until such time as we fix this and actually do it right. And the existence of these hacks allows us to make fixing it a relatively low priority issue. But we really ought to be allowing the specification of namespaces inside `<egXML>`. I suspect it will be hard, but probably in the end doable.

**Comment by lb42** [comment]
You can specify namespaces inside egxml. Just not the examples namespace. See my comments on the "unloved" ticket
