### ISSUE TITLE
XML comments published w Schematron constraints on element pages 

### ISSUE THREAD

**Issue by ebeshero** [TEIC/Stylesheets#363]
Do we want our XML comments to be published on element pages as they are here? Look at 
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relation.html at the Schematron. 

This is possibly related to https://github.com/TEIC/Stylesheets/issues/306 .

**Comment by lb42** [comment]
I noticed that too. I think its a corrigible errir

**Comment by sydb** [comment]
I claim the system is already working quite well, if not exactly as designed. A comment that is a child of `<constraintSpec>` is ignored, and a comment that is a child of `<constraint>` is displayed. Thus if you don’t like the comment displayed on that page, you either reword it until you do or move it up one level in the hierarchy.

**Comment by lb42** [comment]
I vote for moving it up a level.

**Comment by sydb** [comment]
@peterstadler and I believe that the _Stylesheets_ are behaving correctly.
Whether or not the particular comment should be left as is, re-written, removed, moved up a level, or changed to a `<desc>` is another question which perhaps should be raised on a ticket in the _Guidelines_ repo.
