### ISSUE TITLE
docx problem with <hi> over special chars (with fix!)

### ISSUE THREAD

**Issue by TomazErjavec** [TEIC/Stylesheets#389]
For special characters that are in DOCX files written with `<w:sym>` the conversion from DOCX ignores their styling, i.e. does not wrap them in `<hi>` with appropriate `@rend`.
For an example see http://nl.ijs.si/tei/convert/log/rP7WlZiWM1/Pravopisna_pravila-vzorec_2019-08-28/tei.xml where the symbol ⇒ should have been converted to `<hi rend="color(0070C0)">⇒</hI>` (ditto for ∧)  but isn't.

The culprit is line 358 in `Stylesheets/docx/from/textruns.xsl`, which reads:

```
 <xsl:when test="normalize-space(.)=''">
```
It should be 

```
 <xsl:when test="normalize-space(.)='' and not(w:sym)">
```

**Comment by peterstadler** [comment]
fixed in #390
