### ISSUE TITLE
Some XSL libs still point to http://www.tei-c.org/Vault/P5

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#400]
Some libs have been changed to use https, but others are still pointing to plain http, which will no longer work when trying to retrieve p5subset.xml. Is there any reason not to change all of these?

**Comment by peterstadler** [comment]
I think this is not much of an issue anymore since the server configs got fixed and the redirects (http->https) are working properly. Nevertheless, I will grep through the Stylesheets and see wich occurrences of `http://(www.)?tei-c.org/(Vault|release)` might benefit from being changed.
