### ISSUE TITLE
Stylesheets do not correctly handle Schematron rules in attDefs

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#403]
Working on https://github.com/TEIC/TEI/issues/1950, @sydb and I discovered a problem with the output of Schematron from an ODD into RELAX NG (as opposed to the .isosch context). If you put a `<constraintSpec>` in the context of an `<attDef>` as opposed to a class or element definition, the constraint gets hoisted up to the parent level, and therefore any context-dependent XPath in the Schematron will fail.

We think that the Stylesheets should either correctly output such a constraint in the appropriate context in the RELAX NG (preferable option), or they should doctor any XPath in the Schematron to make it work in the context of the parent (probably impossible).

We have checked and confirmed that putting the Schematron in the context of the attribute does work in RELAX NG, but we also need to check what the situation is with XSD.

**Comment by sydb** [comment]
@martindholmes and I are working on a small ODD file to reproduce this problem (which he will upload shortly). It looks as if the problem is not that **everything** gets hoisted to the wrong level, but only the `<sch:let>` statement.

**Comment by martindholmes** [comment]
Herewith an example ODD, generated RNG, and instance file showing the problem. 
[issue403.zip](https://github.com/TEIC/Stylesheets/files/4020069/issue403.zip)

**Comment by lb42** [comment]
,

reluctantly using Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sydb** [comment]
Stylesheets mini-group (@peterstadler, @raffazizzi, and I) have made a precision repair to Stylesheets/odds/teiodds.xsl which fixes the exact problem of the `<sch:let>` getting stuck in wrong place IF and ONLY IF the `<sch:rule context=".">` is **not** specified. If it is specified, all goes wrong.

It is another ticket for another day to solve _that_ problem, but we note that no one has yet complained.
