### ISSUE TITLE
Overriding an attribute in a class removes element from list of members

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#404]
This build of a branch has this page:

https://jenkins.tei-c.org/job/TEIP5-branch-unihan/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.gaijiProp.html

which shows only `<localProp>` as a member of `att.gaijiProp`, but in fact two other elements (`<unicodeProp>` and `<unihanProp>`) are members; it's just that they override two of the class attributes. We need to check what's causing this, in case it's a bug in the Stylesheets (which it seems to be).

**Comment by martindholmes** [comment]
This does seem to be a general problem, with some unpredictable results. For example, `<sound>` is a member of `att.typed`, but it does not appear in the list of members:

https://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.typed.html

but on its own page, where `@type` is overridden, the class does correctly appear:

https://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-sound.html

**Comment by sydb** [comment]
I am not sure if this is the same problem or just a similar, but different, one. (If so, we may want to create a new issue for it.)

Looking at both the [current release](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-classSpec.html) and the [latest build](https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-classSpec.html) of the tagdoc page for `<classSpec>`, you will find that the definition of `@type` has lost its “legal values are” list. I believe the same is true in the schema — the values are not limited to the two desired values. But I have not checked that carefully.

NB that in the released version the `@type` attribute is owned by the `<classSpec>` element, but in the latest build it is inherited from att.typed and overridden.

**Comment by martindholmes** [comment]
@sydb I think this was just a corrigible error, which I've corriged. The `<valList>` on classSpec had no `@mode` attribute, when in fact I think it needs `@mode="add"`, because there is no `<valList>` in the `att.typed` definition of the attribute. Added in commit cbec67806, and once the current build breakage is cleared we'll see if it solves the problem.

**Comment by sydb** [comment]
Thank you, @martindholmes.
What build breakage?

**Comment by ebeshero** [comment]
@sydb Well, the build breakage is not from me any more, thankfully! I had broken 
TEIP5-Documentation-dev on the epub3 test with my SVG. But I've packed that little experiment away to a branch now.

**Comment by martindholmes** [comment]
As far as I can see, `<classSpec>` now looks good. I don't think this was an instance of the problem this ticket deals with (although you could argue that if a valList is provided where one didn't exist before, we could/should/might assume `@mode="add"`).

**Comment by martindholmes** [comment]
Stylesheets group meeting today managed to narrow down the locus of the problem. When the generateMembers template is called to create a list of members of att.typed (line 561, calling the template starting on 2171 of common_tagdocs.xsl), the xsl:key which is used to retrieve the list of class members does not include `<sound>` (and presumably other elements which override att.typed values).
We don't yet know why that key doesn't include these elements, because as far as we can tell, the key is instantiated against the processed odd, and we've confirmed that in the processed odd, the `<sound>` element retains its class membership in att.typed.

**Comment by martindholmes** [comment]
We finally determined that by adding the context `$top` to the key instantiation, the problem is fixed. @sydb checked in https://github.com/TEIC/Stylesheets/commit/7a8f386c2e6198ee316c3dbabcb26e174672a5aa
; thanks also to @martinascholger, @lujessica, and @peterstadler. We believe there may be similar problems in other areas of the odd processing, but we haven't found them yet.
