### ISSUE TITLE
Incorrect "may contain" value when building documentation

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#408]
With an elementSpec like this:

~~~~~
<elementSpec ident="verbose" module="ss" ns="http://hcmc.uvic.ca/ns/staticSearch">
            <gloss>Turns on more detailed reporting during the indexing process.</gloss>
            <content>
              <dataRef name="boolean"/>
            </content>
          </elementSpec>
~~~~~

where the content is a single dataRef, the output in the spec page for the element shows "May contain: Empty element". It's not empty, of course.

**Comment by ebeshero** [comment]
@sydb We think your push didn't go through after the Stylesheets meeting! Can you redo that?

**Comment by martindholmes** [comment]
Before I can test properly, I need to get my bleeding-edge plugin to update, and right now the build on my Jenkins (which builds my plugin) is broken; but it's not broken on the main Jenkins, which suggests they're out of sync somehow. Working on that problem now.

**Comment by martindholmes** [comment]
Fix works fine. Closing! Thanks all.
