### ISSUE TITLE
JTEI: colspanning table cells should have centred content

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#409]
@rvdb and I agree that if a cell spans multiple columns, its content should be centred. To achieve this in PDF, add this at line 912 of profiles/jtei/pdf/to.xsl:

~~~~~
<!-- Colspanning cells should have centred content. -->
      <xsl:if test="@cols[xs:integer(.) gt 1]">
        <xsl:attribute name="text-align">center</xsl:attribute>
      </xsl:if>
~~~~~

To get the same result in ODT, in the template ODT's styles.xml, replicate the teiParaTinyMarginsHeader as teiParaTinyMarginsCentre, and switch fo:text-align to centre; then in profiles/jtei/odt/odt.common.xsl, at line 583, add this block:

~~~~~
<xsl:when test="@cols[xs:integer(.) gt 1]">
            <text:p text:style-name="{if (@role='label' or parent::row[@role='label']) then 'teiParaTinyMarginsHeader' else 'teiParaTinyMarginsCentre'}"><xsl:apply-templates/></text:p>
          </xsl:when>
~~~~~

@rvdb  please test and see if it works for you!

**Comment by rvdb** [comment]
@martindholmes Ok, I've added support for all three output formats, thanks for your ODT and PDF code!

Note: I've created 2 new styles for the ODT template:

- `teiParaTinyMarginsCentre`: for column-spanning data cells
- `teiParaTinyMarginsHeaderCentre`: for column-spanning label cells

**Comment by martindholmes** [comment]
Thanks @rvdb ! I've merged it, and yesterday I committed a -source.xml for #173 to the svn repo, ready for proofing; we can use that as our final test before closing this ticket.
