### ISSUE TITLE
License Copyright

### ISSUE THREAD

**Issue by hcayless** [TEIC/Stylesheets#413]
The BSD 2-clause license we have for the Stylesheets requires a copyright statement, but we don't provide one. I assume we want to assert © TEI Consortium, as in https://tei-c.org/guidelines/licensing-and-citation/, but wanted to check before just doing it.

**Comment by sydb** [comment]
@peterstadler thinks this is just a GO, and @sydb does not object. @hcayless to just put ’em in, but a © statement needs a year, doesn’t it?
