### ISSUE TITLE
`@ns` in ODD customizations causes horrible problems in RNG

### ISSUE THREAD

**Issue by ebeshero** [TEIC/Stylesheets#424]
We find that when an `@ns` attribute appears on a schemaSpec or an elementSpec (whether as a result of being generated as a default attribute by oXygen, or for some other reason), it results in broken RNG's that don't carry customizations of attributes in particular. 

What we've tested at the Stylesheets meeting on 2020-02-25: All of these results are coming from the RNC output from trang. (Stylesheets use trang.)

1) attDef with/without the `@ns` set to TEI doesn't do anything, which means it's inconsequential to the processing. (But it should be creating an attribute in the TEI namespace.)
1) attDef with an `@ns` set to a non-TEI namespace, with a schemaSpec set to a different non-TEI namespace results in attDef's `@ns` gets ignored and the schemaSpec's `@ns` prevails.
1) elementSpec and schemaSpec with default `@ns`set to TEI namespace results in suppressing any customized attDef from the RNG.
1) elementSpec and schemaSpec with default `@ns`set to something other than the TEI namespace results in GOOD results: element and attribute customizations come through. (We should check and see if their customized namespaces appear in the RNG.)
1) elementSpec with `@ns` of TEI and schemaSpec without `@ns` is fine. 
1) schemaSpec with `@ns`of TEI and elementSpec without `@ns` works
1) schemaSpec with `@ns`of TEI and elementSpec  `@ns` of TEI suppresses all the attributes customized in attDef
1) elementSpec with `@ns` that's NOT  TEI and schemaSpec with `@ns` of TEI: results in losing the attributes on that element.  
1) attDef with `@ns` other than TEI, and no `@ns` anywhere else works just fine. (Make sure you use `mode="add"` when testing. We might have forgotten to do this in earlier tests.)

Perhaps where the namespaces don't match, the entire customized element is lost  from the RNG?

There are probably about six tickets to be opened from this. 
* There are problems with rng:grammar and Jing.... testing with Trang in Roma Command Line tool. How does this behave in Oxgarage or elsewhere? 
* What's happening in the tei-to-rnc conversion?

Please amend this ticket as we continue testing. People involved today: @sydb @martindholmes @martinascholger @hcayless  and @ebeshero with Nicholas Cole for a moment but we're having trouble finding his GitHub handle!!!!

**Comment by martindholmes** [comment]
On the Trang/RngToRnc issue, I posted this ticket:

https://github.com/TEIC/Stylesheets/issues/423

**Comment by martindholmes** [comment]
@sydb and I looked into this and we determined that:

When `@ns=TEI` is added to any TEI elementSpec element, any child attribute change results in the loss of the attribute rather than its modification.

It makes no difference whether `@ns` is on schemaSpec or not, or the attDef is mode="change" or "replace". The only problem factor is the presence of `@ns=TEI` on the `elementSpec`.

HOWEVER, when an attribute has `@mode=add`, then presence or absence of `@ns=TEI` IS a problem; when `ns` is present on schemaSpec, the new attribute is not created, but when it is absent, the attribute is created.

These may or may not be separate problems. In the code, we should be looking for places where the presence/absence of `@ns` is checked, rather than the value of it.

**Comment by martindholmes** [comment]
Test file no schemaSpec/@ns:

[stylesheets_issue_424_no_ns_on_schemaSpec.odd.zip](https://github.com/TEIC/Stylesheets/files/4268199/stylesheets_issue_424_no_ns_on_schemaSpec.odd.zip)

**Comment by sydb** [comment]
Test file with `schemaSpec/@ns` set to TEI namespace:

[stylesheets_issue_424_with_ns_on_schemaSpec.odd.zip](https://github.com/TEIC/Stylesheets/files/4268211/stylesheets_issue_424_with_ns_on_schemaSpec.odd.zip)

**Comment by dmj** [comment]
I think the function [odds/odd2odd.xsl#tei:uniqueName()](https://github.com/TEIC/Stylesheets/blob/dev/odds/odd2odd.xsl#L278) does not look right. 

- If $e has a @ns of TEI then the unique name prefix is the empty string. 
- If $e has no @ns and the ancestor::schemaSpec as a @ns of TEI, the unique name prefix is 'http://www.tei-c.org/ns/1.0'.

If the @ns is supposed to be inherited (which I think is not made clear from specs), then in this case two elementSpec's referring to the same element are considered to be different.

I would rewrite the function as follows:
```
<xsl:function name="tei:uniqueName" as="xs:string">
    <xsl:param name="spec" as="element()"/>
    <xsl:variable name="ns" as="xs:string" select="($spec/@ns, $spec/ancestor::tei:schemaSpec/@ns, 'http://www.tei-c.org/ns/1.0')[1]"/>
    <xsl:value-of select="concat('Q{', $ns, '}', $spec/@ident)"/>
  </xsl:function>
```
- to obtain the effective namespace I take whatever comes first: the current spec's @ns, it's ancestor's @ns, or the default
- to avoid ambiquity I build a [URLQualifiedName](https://www.w3.org/TR/xpath-30/#doc-xpath30-URIQualifiedName) using the namespace URI

**Comment by dmj** [comment]
A)

Inheritance is discussed in 20.8:

> The elementSpec, attDef and schemaSpec specification elements also
have an attribute which determines which namespace to which the object
being created will belong. In the case of schemaSpec, this namespace
is inherited by all the elements created in the schema, unless they
have their own ns.

Thus the function might better rewritten as:

```
  <xsl:function name="tei:uniqueName" as="xs:string">
    <xsl:param name="spec" as="element()"/>
    <xsl:choose>
      <xsl:when test="$spec instance of element(tei:elementSpec)">
        <xsl:variable name="ns" as="xs:string" select="($spec/@ns, $spec/ancestor::tei:schemaSpec/@ns, 'http://www.tei-c.org/ns/1.0')[1]"/>
        <xsl:value-of select="concat('Q{', $ns, '}', $spec/@ident)"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:variable name="ns" as="xs:string" select="($spec/@ns, 'http://www.tei-c.org/ns/1.0')[1]"/>
        <xsl:value-of select="concat('Q{', $ns, '}', $spec/@ident)"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:function>
```

B) There is a nother bug in the template processing elementRef in pass1

https://github.com/TEIC/Stylesheets/blob/dev/odds/odd2odd.xsl#L621

The elementRef only has only a @key but no @ns. Thus we ignore any @ns on the target elementSpec or on the ancestor schemaSpec of the target. I created https://github.com/TEIC/TEI/issues/2040 for the missing @ns on elementRef.

**Comment by martindholmes** [comment]
Stylesheets group worked on a new version of tei:uniqueName() in branch issue_424_experiment, and got half-way to a solutions, but our implementation, although it doesn't apparently break anything, hasn't yet been tested to see if it solves any of the actual problems described above. We also noted that there are two identical definitions of tei:uniqueName() in odd2odd and teiodds, and we believe (although we're not sure yet) that the latter can simply be deleted without fallout.

**Comment by sydb** [comment]
## TODO
Stylesheets group meeting of today thinks the next steps forward are:

1. Clean up @ebeshero’s wonderful list in the OP of problem areas, simultaneously making it into a numbered list
2. Take one of the test ODDs that @martindholmes or I created for this and modify it so that it systematically tests each of the above cases (referring to it by list number)
3. (Note — this might take several ODDs, as we can only have 1 `<schemaSpec>` per ODD, right?)
4. Put the new tests into either Test/ or Test2/ (or both)

Note that the version of tei:uniqueName() used in the branch @peterstadler just issued a draft PR for fixes quite a few of these problem cases.
