### ISSUE TITLE
minOccurs= on <elementRef> not being honored

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#425]
@npcole and I just discovered (while working on [TEI ticket 1979](https://github.com/TEIC/TEI/issues/1979)) that the
~~~~~xml
  <elementRef key="ptr" minOccurs="2" maxOccurs="unbounded"/>
~~~~~
results in an incorrect RELAX NG schema (and DTD), namely just `ptr+` (instead of either `ptr, ptr+` or `ptr, ptr, ptr*`).

I believe (without a lot of evidence) that the problem is in teiodds.xsl circa line 2222.

**Comment by lb42** [comment]
I remember arguing about this w  spqr. Cant remember why, but thats why the content model is the way it is and not the way syd and logic might prefer

**Comment by martindholmes** [comment]
[test_issue_425.zip](https://github.com/TEIC/Stylesheets/files/7144834/test_issue_425.zip)

@npcole  and I checked into this, and the attached test file and output suggest that the problem is solved. This ticket should be ripe for closing unless @sydb has another scenario in which it fails.

**Comment by sydb** [comment]
I do not know when or where the fix was done, but it does seem to be working. The evidence (above and beyond the ODD file @martindholmes and @npcole provide, [above](#issuecomment-916996166)) is that the
~~~xml
<elementRef key="ptr" minOccurs="2"  maxOccurs="unbounded"/>
~~~
of transpose.xml is properly converted to
~~~
( ptr, ptr, ptr* )
~~~
Yay!
