### ISSUE TITLE
ODT processing differs in depending on environment

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#435]
@martindholmes has long been puzzled as to why ODT processing is different when he runs Test2 locally vs on the Jenkins machine.
Today we discovered that it is due to the presence or absence of ./names.xml, which is an artifact of the the Makefile that is not in the repo because it is (appropriately) in .gitignore. This file is just (an invalid) list of all the GIs in p5.xml (or p5subset.xml).
This ticket is for the repair of this problem.
Current plans are:

1. Add a target to Test2/build_utilities.xml which generates this file (probably using the same stylesheet, tools/getnames.xsl, eh?)
2. Make all ODT and DOCX targets in Test2/ depend on that new target.

Another thought, though, is to skip the generation of names.xml, and somehow teach the ODT and DOCX processing which p5subset they should be using, and just look in `p5subset//elementSpec/@ident`.

**Comment by martindholmes** [comment]
I believe this can now be closed. Will reopen if eventual Jenkins build fails, but all local tests work.
