### ISSUE TITLE
odd2lite drops <desc> child of <graphic>, leaving invalid PCDATA

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#444]
On ticket #328 @joeytakeda raised an issue that @peterstadler and I think deserves to be a separate ticket, so here it is. My next comment is just a copy of @joeytakeda’s comment on that ticket.

**Comment by sydb** [comment]
[From @joeytakeda]

odd2lite.xsl also seems to drop child `<desc>`s in `<graphic>`. This:

```
<p>Here is the TEI badge: <graphic url="http://www.tei-c.org/wp-content/uploads/2016/11/I-use-TEI.png"><desc>The TEI Badge</desc></graphic></p>
```

Becomes

```
        <p>Here is the TEI badge: <graphic
                    url="http://www.tei-c.org/wp-content/uploads/2016/11/I-use-TEI.png">The TEI
                    Badge</graphic></p>
```

**Comment by npcole** [comment]
Assignments copied from the parent ticket.

**Comment by sydb** [comment]
We (@martindholmes, @npcole, and I) found a likely cuprit in the template that matches tei:desc in common/common_tagdocs.xsl. (It was just doing &lt;apply-templates>, no more.) We changed it so it copied the `<desc>` itself and all its attributes. Change passed the tests of Stylesheets/Test/, Stylesheets/Test2/, and TEI/P5/Test/, so we are reasonably confident this is a fix.

**Comment by sydb** [comment]
Oy vey.
This fix turns out to break the build. I have put an hour or so into figuring this out, and what I have determined is I am probably not going to fix it today, and thus I am going to back out the change made in 668331b and re-open this ticket.

The problem seems to be that there are several places in the build process (or, at least, 2 obvious places in the building of ePubs) where the new &lt;desc> elements (“new” in the sense that yesterday the were just invalid PCDATA) are copied through rather than properly processed.

I found what I think is the first of these: The program P5/Utilities/expand.xsl generates the “tab-content-models” table by looking for //macroSpec and (among other things) applying-templates to the first &lt;desc> child. (This is problematic in itself — it should not be the 1st &lt;desc> child, it should be processing the &lt;desc> child of the currently-being-processed language.) There is no template for &lt;desc> in this stylesheet, so I just added one. Seemed like a good idea at the time. But no. Instead of a dozen errors just in the ePub portion of the build, there were thousands all over the build, because the p5odds.rng file itself is invalid (due to the &lt;desc> showing up as text there).

I have no idea how that happened. Goes to remind us all this is a very fragile system.

**Comment by martindholmes** [comment]
@sydb and I looked at this ahead of the Stylesheets meeting and determined that instead of modifying the template for tei:desc, we should add one for tei:graphic/tei:desc, that copies the desc. Then we will have to deal with any fallout downstream, where tei-to-other-things is not expecting a desc inside graphic. Those downstream things might choose to drop the desc, or turn it into an attribute, or similar.
