### ISSUE TITLE
all of them? are you serious? it’s global, that’s what global means

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#451]
Listing _every_ TEI element in the “Members” portion of the tagdoc for [att.global](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html), and after “att.global” in square brackets in the “Members” portion of the tagdocs for [att.global.X](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.responsibility.html),  is (IMHO) silly.
Don’t quite know what to put there instead (a link to [Appendix C — Elements](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/REF-ELEMENTS.html), perhaps?), but a list of 580 elements is really not helpful.

**Comment by martindholmes** [comment]
It's logical, it's consistent with the rest of the documentation, it's informative, and it does no harm. I'd keep it. :-)

**Comment by sydb** [comment]
It is certainly consistent with the rest of the documentation. Whether it is logical or not is debatable, I would say. But it conveys no useful information at all, and it certainly does (mild) harm: it makes it harder to read the useful information on the page.

**Comment by sydb** [comment]
I had not expected anyone to chirp up and say that it was useful to leave it. But if people think seeing a list of all TEI elements at this point in a tagdoc is helpful, we could consider some sort of when-asked approach. E.g., have the words “all TEI elements” which has the full list as a mouse-over, or gets swapped to the full list if clicked on (how does the user get back, though?) or some such.

**Comment by martindholmes** [comment]
I was thinking that if one of your habits is to click your way to a ref page and then control+F to find whether an element you care about can carry that attribute, then changing this would disrupt your workflow. And it's perhaps useful to see that "global" includes egXml even though it's in a different namespace. That's not necessarily obvious.

Either way, it does seem like a low-priority thing really.

**Comment by sydb** [comment]
Sorry, absolutely no sympathy for described workflow.
Yes, useful to see that `<egXML>` gets global attrs, but not useful enough to make page so hard to use, IMHO.
At least we agree this is low-priority. :-)

**Comment by jamescummings** [comment]
In some ways it is easier to list them all and if the same mechanism is used in customisations where 'global' does not necessarily mean 'all' then it is good to maintain or we'll have different processes for odd documentation and guidelines. (It probably is already different but I'm minded to suggest that our guidelines generation abdominal html odd output should remain as similar and linked as possible.)

**Comment by martindholmes** [comment]
@jamescummings "abdominal" made my day. :-)

**Comment by ebeshero** [comment]
Mine too! But what word is it substituting for? (Probably not abominable!) :-)

**Comment by sydb** [comment]
Yes, @jamescummings, it is certainly _easier_ to list them all. That’s why we do list them all. I do not think it is a good thing, though, let alone _better_ than figuring out how to suppress that list and yet still display something that could be useful.

**Comment by sydb** [comment]
On talking this over with @martindholmes, we’re thinking the right way to do this is in the interface, not in the Stylesheets. (Yes, I know, the Stylesheets produce the interface, but you know what I mean.) If the interface sees _any_ long list of elements (maybe more the 50?) it should give the user the choice to see them all or just an initial sampling. (Making use of `<html:details>` and `<html:summary>` elements, probably.)

**Comment by jamescummings** [comment]
> @martindholmes: @jamescummings "abdominal" made my day. :-)
> @ebeshero:  Mine too! But what word is it substituting for? (Probably not abominable!) :-)

Apologies, my phone sometimes puts that instead of 'and'.

**Comment by npcole** [comment]
Assigned to @npcole to have a look at @sydb's suggestion from 25th September.
