### ISSUE TITLE
Test2 needs to be updated to use source/p5subset.xml

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#456]
The change to using a local p5subset.xml in the source/ folder has not yet been integrated into Test2. This should be done after the upcoming release.

**Comment by sydb** [comment]
(Just convinced @martindholmes to fix this right now, as he and I are the only two using this dir, anyway.)

**Comment by martindholmes** [comment]
Should be done in commit #69b1e8b6.

**Comment by martindholmes** [comment]
Leaving this open until we know whether the tests succeed on Jenkins.
