### ISSUE TITLE
odd2xsd11?

### ISSUE THREAD

**Issue by eduarddrenth** [TEIC/Stylesheets#458]
Dear all,

Would it be an idea to add odd conversion to xsd 1.1?

This makes implicit validation including constraints possible in for example exist-db.

Bye, Eduard

**Comment by martindholmes** [comment]
@eduarddrenth Since we use Trang to create XSD from RELAXNG, and the RELAXNG includes embedded Schematron, would this be better as a feature request for Trang? There is already an issue on that repo:

 https://github.com/relaxng/jing-trang/issues/205

**Comment by eduarddrenth** [comment]
Yes, good idea
