### ISSUE TITLE
collection missing in msdescription

### ISSUE THREAD

**Issue by eduarddrenth** [TEIC/Stylesheets#460]
using 7.50.0 I have to add collection to msdescription like this.

```
        <!-- for some reason collection isn't in msdescription-->
        <elementSpec ident="collection" mode="add" module="msdescription">
          <classes mode="replace">
            <memberOf key="att.canonical"/>
          </classes>
        </elementSpec>
```

collection doesn't seem to be available by default.

**Comment by martindholmes** [comment]
This seems like a ticket for the TEI repo, not the Stylesheets repo. Am I missing something?

I did check the latest release, and this is perfectly valid using tei_all:

~~~~~
<sourceDesc>
            <msDesc>
               <msIdentifier>
                  <repository>Somewhere</repository>
                  <collection></collection>
               </msIdentifier>
            </msDesc>
         </sourceDesc>
~~~~~

**Comment by sydb** [comment]
+1 to what @martindholmes just said (he beat me to it by minutes. :-)

But in addition, `<collection>` is indeed in the msdescription module; see [the tagdoc](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-collection.html). So I am wondering what you mean by “isn’t available by default”? What is it you tried that produced the undesirable result?

Furthermore, it is not clear to me what the posted `<elementSpec>` will actually do. I suspect (but have not tested) that in the absence of `<moduleRef key="msdescription">` it will import that `<collection>` element; but it might also delete its contents.

**Comment by ebeshero** [comment]
@eduarddrenth I wondered what might be causing the problem, and whether it is that you wanted to use `<collection>` in a different location within `<msDesc>`? Checking the specs in the Guidelines shows it not to be a child of `<msDesc>`, but has a pretty precise position inside `<altIdentifier>`, `<msIdentifier>`, or `<objectIdentifier>` :
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-collection.html

**Comment by eduarddrenth** [comment]
I'll show you soon

**Comment by eduarddrenth** [comment]
Found it! I did:

```
        <moduleRef key="msdescription" include="repository institution msDesc msIdentifier msName"/>
```
instead of:
```
        <moduleRef key="msdescription" include="repository institution msDesc msIdentifier msName collection"/>
```
Sorry for the mistake, thanks for looking!
