### ISSUE TITLE
Processing of `@rendition` attributes in HTML is namespace-ignorant

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#463]
This pair of xsl:keys in html/html_header.xsl:

~~~~~
<xsl:key name="ALL-EXTRENDITION" match="@rendition[not(starts-with(.,'simple:') or starts-with(.,'#'))]" use="1"/>
  <xsl:key name="EXTRENDITION"
	   match="@rendition[not(starts-with(.,'simple:') or starts-with(.,'#'))]" use="."/>
~~~~~

matches `@rendition` attributes in any namespace. That means it matches `@rendition` attributes in the `<egXML>` examples namespace, when it shouldn't. The result is that if you try to process an ODD file into HTML documentation, and your ODD file happens to contain examples which include the use of a private URI scheme in `@rendition` attributes, the conversion will fail with an "unknown protocol" error. This simple fix solves the problem:

~~~~~
  <xsl:key name="ALL-EXTRENDITION" match="tei:*/@rendition[not(starts-with(.,'simple:') or starts-with(.,'#'))]" use="1"/>
  <xsl:key name="EXTRENDITION"
	   match="tei:*/@rendition[not(starts-with(.,'simple:') or starts-with(.,'#'))]" use="."/>
~~~~~

I'll create a pull request for the fix and link it below.

**Comment by ebeshero** [comment]
@martindholmes ~~This is strange.~~ I've been testing with the bleeding edge plugin in oXygen, and first just trying to see if I can reproduce the error. ~~I haven't been able to yet: I'm getting good HTML documentation and not seeing errors, not even any any validation errors when I inspect the HTML.~~ **Correction:** Yes: the error is generated, but oXygen still generates the HTML documentation and that documentation looks okay.

 I tried two different `<elementSpec>`s with some foreign namespace content in egXMLs in my simple ODD: 

One elementSpec was for an element in the TEI namespace:
```
 <elementSpec ident="seg" module="linking" mode="change">
               <attList>
                  <attDef ident="rendition" mode="replace" usage="req">
   
                     <valList type="closed">
                        <valItem ident="rnd:upover"/>
                        <valItem ident="rnd:downlow"/>
                     </valList>
                  </attDef>
               </attList>
               <exemplum xml:lang="en">
                  <p>The <gi>seg</gi> is here to help me test stuff that isn't working in ODD transformations. </p>
                  <egXML xmlns="http://www.tei-c.org/ns/Examples" xml:space="preserve">My silly example contains a <seg rendition="rnd:upover">tester element</seg>.
                  </egXML>
               </exemplum>  
            </elementSpec>

```


I also tried one where the element is in a new namespace:

```
  <elementSpec ident="myTesterElem" ns="http://www.example.org/ns/tei_minimal" mode="add">
               <classes>
                  <memberOf key="att.canonical"/>
               </classes>
               <content>
                  <content>
                     <rng:text/>
                  </content>
               </content>
               <exemplum xml:lang="en">
                  <p>The <gi>myTesterElem</gi> is for testing whether stuff is working when I put non TEI elements in an ODD</p>
                  <egXML xmlns="http://www.tei-c.org/ns/Examples" xml:space="preserve">My silly example contains a <myTesterElem rendition="rnd:upover">tester element</myTesterElem>!
                  </egXML>
               </exemplum>
            </elementSpec>
```

This was using the bleeding edge plugin (Jenkins build number 2020-10-06-151351). I also started out just processing with the default oXygen TEI plugin. ~~These are working for me...so In what context isn't it working? Or what am I missing here?~~

**Comment by sydb** [comment]
I haven’t looked or tested at all. Will try to do so shortly. But just glancing at this, I am not sure it is the right fix. Why would the TEI `@rendition` be limited to elements in the TEI namespace? Surely if I add a new element in a different namespace to my TEI schema, it is reasonable that I want it to have `@rendition` (and `@rend` and `@n` and `@next` and `@prev`, etc.), no? So wouldn’t the fix be something like `@rendition[not(ancestor::teix:*)][not(starts-with(.,'simple:') or starts-with(.,'#'))]` instead?

OK, now I’ve done some testing with this [ODD](https://github.com/TEIC/Stylesheets/files/5359139/T.odd.txt) file (attached as .txt). I get inconsistent results:

1. Running commandline `roma` using the released branch of the Stylesheets I get the same “unknown protocol” error.
1. Applying either @martindholmes’ suggested fix (above) or mine solves the problem.
1. Running `Stylesheets/bin/teitohtml` with or without the `--odd` switch (also from the released branch of the Stylesheets) does **not** result in an error!

I don’t get that last bit.

**Comment by martindholmes** [comment]
Away from my computer, but I think @sydb 's refinement is good. Re the Oxygen behaviour, two things spring to mind: it may use Saxon PE or EE, or its lib may include a tweaked XML parser that doesn't generate the error.

**Comment by ebeshero** [comment]
Here's [my tester ODD file](https://raw.githubusercontent.com/newtfire/textEncoding-Hub/master/Troubleshooting/testerODD/tester-ODD.odd): should have linked it earlier (it's in one of my repos, linked directly.) The customized elements are `<myTesterElem>` and `<seg>`. I don't think there's any substantial difference between mine and @sydb 's except mine has one elementSpec in the TEI namespace, and another defined in a custom namespace. And I added a closed valList for the `@rendition` on one of those elementSpecs but not the other. I doubt there's any difference in the processing of `@rendition` from that; I was just experimenting. 

Figuring out the contexts that do and don't raise the error in the first place seems a good idea. I see my oXygen transformation from ODD to HTML is using Saxon PE. So, let's see what happens with it in command-line Roma after I update my local Saxon on this new computer...

**Comment by martindholmes** [comment]
In my original file that generates the problem:

[wendat.odd.zip](https://github.com/TEIC/Stylesheets/files/5359419/wendat.odd.zip)

the rnd: prefix is only used in egXMLs in the body (documentation), not in the schemaSpec. 

We did have an attempt to purge all use of EE and PE from the Oxygen plugin, because Oxygen's optimizations were causing unwanted behaviour in our processing, and because we wanted to maintain the parallel between transformations done outside of Oxygen and those done in Oxygen. That one must have slipped past us, or perhaps been reset to PE somehow. We should never be using EE or PE in the Oxygen transformations.

**Comment by ebeshero** [comment]
@martindholmes @sydb Update: Confirmed: the error shows up in both my Windows and Mac installations of oXygen (v. 22.1), and I didn't notice it last night b/c I was nevertheless still generating the HTML documentation and that documentation checked out and displayed my egXML. 

I see that yes, Saxon PE is what's running the transformation in oXygen on both my machines, too--so I think that may be the current default? (I'm pretty sure I didn't go in on purpose to change that setting.)

**Comment by martindholmes** [comment]
In commit #433ca5d in the oxygen-tei repo I've switched over from Saxon-PE to Saxon-HE to see if it helps with this problem. When the bleeding-edge plugin is built, I'll update my Oxygen and run some tests again.

**Comment by martindholmes** [comment]
Either this has solved the problem, or the problem went away because of some other change. At any rate, we have made an effort to keep all our Oxygen transformations pinned to Saxon-HE so that there are no differences between what you get in Oxygen and what happens at the command line, so the change is in line with previous decisions, and we get to close this ticket. Thanks everyone.
