### ISSUE TITLE
@ns attribute with the value of 'http://www.tei-c.org/ns/1.0' of an attDef is ignored when creating a schema

### ISSUE THREAD

**Issue by dmj** [TEIC/Stylesheets#467]
> attDef with/without the @ns set to TEI doesn't do anything, which means it's inconsequential to the processing. (But it should be creating an attribute in the TEI namespace.)

See #424

**Comment by dmj** [comment]
I think there is a problem with the definition of @ns: It is said to have a default value of 'http://www.tei-c.org/ns/1.0'. Thus an attDef without a @ns has an implied @ns with the value of 'http://www.tei-c.org/ns/1.0', which in turn means that the attribute is in the TEI-namespace. But the attributes are in no-namespace.

**Comment by dmj** [comment]
I cannot reproduce this problem. attDef with @ns creates a attribute tei:new-attribute. See https://gist.github.com/dmj/d63a2688e964fbcf7e33fc78486c07b3.

**Comment by martindholmes** [comment]
@dmj Is this still a problem, or should this ticket be closed?

**Comment by dmj** [comment]
I'm not sure. It was reported as an error by @ebeshero in #424.

**Comment by sydb** [comment]
This does indeed look like the same issue as #424. Thus closing here. Once #424 is fixed, if you still find a problem, @dmj, please re-open (or open a new ticket).
