### ISSUE TITLE
Section anchors should be anchor characters, not pilcrows, and should be visible

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#479]
egXMLs now have a nice little Unicode anchor character as their link; @sydb and I believe that the anchor should also be used where we currently use a pilcrow, to create anchors for prose chapter sections, and that the current style bookmarklink, which makes the character greyed-out until you mouseover it, should not do that, or shouldn't be quite so light so people can see it.

**Comment by sydb** [comment]
Stylesheets group thinks switching to anchor is a good idea, and darkening the color of those after attributes (we’re thinking #AAD).

**Comment by sydb** [comment]
HOWEVER, we note that the browser seems to apply a color to the anchor symbol (U+2693) that overrides the CSS. Considering either leaving it (in which case it gets the default color the browser likes) or perhaps trying to make it somewhat transparent so it is not so dark as compared to what the pilcrow is now (#DDF).

We also considered other characters, including the bookmark emoji (U+01F516) instead; but decided to keep the anchor symbol.

Solution to the color problem is to use `color: transparent; text-shadow: 0 0 0 #AAD;`.

**Comment by sydb** [comment]
We note that we are making the CSS changes only for the HTML Guidelines. It is likely the case that these changes will need to be reflected in various other profiles including epub, iso, teiepub, guidelinesprint, kindle. After Mr. Jenkins has finished building we should look at the Guidelines PDF and EPUB, and maybe open a new ticket.

We think this ticket can be closed if Mr. Jenkins is happy.

**Comment by Conal-Tuohy** [comment]
Browsers will render an anchor glyph in colour ⚓ because it's defined to be an emoji character. If you precede the character with a text variation selector (U+FE0E) then you will select a non-emoji glyph: ⚓︎
