### ISSUE TITLE
Obsolete email address in every Guidelines page 

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#484]
See TEIC/TEI/issues/2112. 

Lines 420ff of odds.guidelines.xsl hard-codes an obsolete email address into the Guidelines page headers:

~~~~~
<meta>
	<xsl:attribute name="{if ($outputTarget='html5') then 'property' else 'name'}">DC.Creator.Address</xsl:attribute>
	<xsl:attribute name="content">tei@oucs.ox.ac.uk</xsl:attribute>
    </meta>
~~~~~

Council should decide what email address is more appropriate, and then perhaps parameterize it.

**Comment by hcayless** [comment]
My inclination is to get rid of it entirely. There are plenty of ways for people to get in touch with the TEI-C that are less obscure.
