### ISSUE TITLE
HTML5 doctype created by the stylesheets is obsolete

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#487]
All HTML5 output from the stylesheets, including the Guidelines, contains the following long-obsolete formula:

~~~~~
<!DOCTYPE html
  SYSTEM "about:legacy-compat">
~~~~~

This was originally proposed as a sort of temporary hack for systems unable to produce the proper HTML5 doctype (https://dev.w3.org/html5/html-author/#doctype-declaration). It's a hindrance in that processors such as Saxon will stumble over it, making post-processing of TEI-generated HTML more difficult, and since producing the proper doctype is now trivial with modern versions of Saxon, we should eliminate this old form.

We should first update all our Saxon jars to make sure we don't have any old versions still floating about in the repos; then attend to all instances like this:

~~~~~
  <xsl:output encoding="utf-8" method="xml" doctype-public="-//W3C//DTD XHTML 1.1//EN"/>
~~~~~
and this:
 ~~~~~
  <xsl:output method="xml" omit-xml-declaration="yes" doctype-system="about:legacy-compat" />
~~~~~

moving instead to modern XHTML5:
~~~~~
<xsl:output method="xhtml" html-version="5" encoding="UTF-8" indent="yes" normalization-form="NFC"
    exclude-result-prefixes="#all" omit-xml-declaration="yes"/>
~~~~~

which will automatically give us the correct HTML5 doctype and properly-namespaced XHTML.

**Comment by sydb** [comment]
Hear hear!

**Comment by sydb** [comment]
@HelenaSabel & @martindholmes — What is left to do on this ticket?
I note that `<!DOCTYPE html
  SYSTEM "about:legacy-compat">` no longer appears in the output of `bin/teitohtml`, but still appears in the HTML version of the _Guidelines_.

**Comment by martindholmes** [comment]
That must be due to the guidelines.xsl.model, surely -- let's take a look this morning when we meet.

**Comment by HelenaSabel** [comment]
The reason is that [PR 499](https://github.com/TEIC/Stylesheets/pull/499) has not been merged yet because I wanted to make some final changes, but it will be over soon and we can close this ticket :)

**Comment by martindholmes** [comment]
@sydb and I just made a change to the xsl:output method in the TEI repo guidelines.xsl.model to make it html5, but that has no effect on the Guidelines build because it's overridden at odds/odd2html.xsl in the Stylesheets. 

And the xsl:result-documents in guidelines.xsl.model also take their output settings from the Stylesheets variables in the included files.

**Comment by sydb** [comment]
We (@martindholmes) and I just updated TEI/Utilities/guidelines.xsl.model to do the right thing, but it doesn’t, because it imports stylesheets from this repo and uses their values.

**Comment by HelenaSabel** [comment]
With the changes done by @sydb and @martindholmes, `make html-web` with the Stylesheets version of branch `iss487` generates the correct doctype.

**Comment by sydb** [comment]
Ummm … OK, is this closable now? (I.e., are we done?)

**Comment by HelenaSabel** [comment]
I certainly hope so!
