### ISSUE TITLE
constraintSpec in elementSpec/attList/attDef causes borked output

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#488]
Following on from this ticket: https://github.com/TEIC/TEI/issues/2115

Where an elementSpec has an attDef which contains a constraintSpec, the constraintSpec is not rendered where it should be (in the attDef context); instead, its content is blurted out in a messy way in the content model of the element itself. This is manifested in the spec pages for variantEncoding, rt, citeStructure and moduleRef in the 4.2.0 release of TEI.

**Comment by sydb** [comment]
I have not found the problem, but it certainly smells like the code that processes the contents of `<attDef>` is applying or calling the template for `<constraintSpec>` in the wrong mode.

**Comment by martindholmes** [comment]
It's in odd2lite.xsl:
~~~~~
java -jar Utilities/lib/saxon9he.jar -s:p5.xml -xsl:../../Stylesheets/odds/odd2lite.xsl -o:testp5lite.xml
~~~~~

And the problem is right there.

The issue shows up when the attDef is processed in the context of the element content model; the constraintSpec should be ignored but it's not.
