### ISSUE TITLE
upgrade Saxon

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#490]
@martindholmes points out we should upgrade our Saxon 9 to Saxon 10.

**Comment by sydb** [comment]
See also [TEI #2117](https://github.com/TEIC/TEI/issues/2117).

**Comment by sydb** [comment]
Most of this has been completed in branch _saxon10_ at commit 5d8f2a2e. We are waiting until it is done in the TEI repo, too, before issuing a PR.

**Comment by martindholmes** [comment]
Working with @npcole today, we realized that dev has moved and and would have to be merged, so we did that, which nuked some of the Test results changes from our previous work in this branch. We've now been re-running tests and re-fixing results. Hopefully we can get to a PR before more changes in dev cause more merge problems.
