### ISSUE TITLE
TOC creation for TEI-in-TEI

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#496]
Now that `<TEI>` can self-nest, the `mainTOC` template in ./html/html_textstructure.xsl needs to be updated. (At the very least, `test="self::tei:teiCorpus"` needs to be `test="self::tei:teiCorpus | self::tei:TEI[tei:TEI]"`, but there may be a lot more.)

(This is **status: Go** to see what needs to be done, and perhaps do it in a branch.)

**Comment by martindholmes** [comment]
@npcole, @sydb and I made a start on this in branch issue-496-corpus, and got some things working, but HTML is not yet working correctly. Ran out of time.

**Comment by sydb** [comment]
This was status GO to see what needs to be done. @martindholmes and I have spent ~2–3 hours together on this problem (one of them with @npcole’s help, too) and have not cracked this nut. (The problem is not that figuring out an XPath that does the right thing is difficult, but rather following the labyrinthine processing chain is a serious stumbling block.)
Thus, at least for the moment, this is going to be “closed, won’t fix”.
