### ISSUE TITLE
common_tagdocs.xsl ignores `<tag>/@type`

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#503]
The spec for the `<tag>` element includes values for `@type` including "start, "end", "empty" etc. 

https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-tag.html

However, the template that renders the element, in common_tagdocs.xsl (l.1852) ignores those values:

~~~~~
 <xsl:template match="tei:tag">
    <xsl:element namespace="{$outputNS}" name="{$hiName}">
      <xsl:attribute name="{$rendName}">
        <xsl:text>tag</xsl:text>
      </xsl:attribute>
      <xsl:text>&lt;</xsl:text>
      <xsl:apply-templates/>
      <xsl:text>&gt;</xsl:text>
    </xsl:element>
  </xsl:template>
~~~~~

I think appropriate content should be inserted, so that:

- "end" inserts a slash after the opening angle bracket
- "empty" inserts a slash before the closing bracket
- "comment" inserts "!--" before and "--" after the content
- "pi" inserts question marks before and after the content
- "ms" inserts escaped `[CDATA[` before and `]]` after the content

Otherwise I don't see much point in these `@type` values at all.

**Comment by sydb** [comment]
Assigning @npcole and @JanelleJenstad just to remind them that they are assigned to review the [associated pull request](#508).
