### ISSUE TITLE
Missing space after idno in biblStruct processing (obvious in Guidelines bibliography)

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#504]
@sydb and I, working on a TEI ticket, noticed that where an idno (eg for a doi) exists in a biblStruct, and its processing is followed by the processing of a journal title, there is no space between them in the output (both in the HTML and PDF Guidelines). Although we believe the simplest solution here is to re-encode the relatively few remaining biblStructs entries as bibls (we had a campaign to convert them a few years ago, but it was never completed), in the meantime we should fix the missing space.

**Comment by martindholmes** [comment]
Working fixes for this are on branch sydb-504_space_after_DOI, and I think we're ready for a pull request. Waiting for @sydb to confirm.

**Comment by sydb** [comment]
On my local machine:
- Quick eyeballing of output looks right.
- All tests in Test2/ pass
- All tests in Test/ pass (except building PDF, which always fails)

So yeah, I guess we are ready to pull & roll.
