### ISSUE TITLE
links from examples to BIB failing

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#520]
I have **not** yet investigated what is going on, but at first blush we have a serious problem: `@source` links from `<egXML>`s in the GLs to the bibliography are not working. First glance says it is because the ID of each `<bibl>` is not getting through to the BIB.html file. (Thus I am suspicious of @HelenaSabel’s recent ID fix which, IIRC, I approved just yesterday.)

Mildly more detailed:

- Built GLs in branch attlocatable-issue-1910, found “bibliography” links from examples were not working (took me to BIB.html file, but not proper entry); return links from BIB to example worked.
- Looked in BIB.html, did not see `@id` on entries.
- Built GLs in branch dev, found same (also discovered, kinda accidentally, that many of the “bibliography” links are simply missing, but that is a [different ticket](https://github.com/TEIC/TEI/issues/1476)).

**Comment by sydb** [comment]
Note: working on this locally in restored branch `iss516`, as I am all but convinced that the [corresponding PR](https://github.com/TEIC/Stylesheets/pull/517) is the source of the problem. (File `html/html_core.xsl` circa line 845, to be precise.)

**Comment by sydb** [comment]
The problem is different templates are getting fired. For a “regular” TEI file (like the test32.xml @HelenaSabel was working with), the template that handles the `<bibl>`s of interest is in common/common_core.xsl (circa line 1068). For the _Guidelines_ themselves the template that handles the `<bibl>`s of interest is in odds/guidelines.xsl (circa line 696).

**Comment by sydb** [comment]
Have a fix: the problematic template that is being fired for the BIB (odds/guidelines.xsl circa line 696) was using `<apply-templates/>`. Changing that to `<apply-templates select="@xml:id | node()"/>` seems to fix the problem. No idea what else it might break. Running tests now.

**Comment by sydb** [comment]
OK. All tests (Stylesheets/Test/, Stylesheets/Test2/, and TEI/Test/) seem to pass on my local system. Going to check this fix in and see what @HelenaSabel thinks.
Fix checked into branch at 4896fb33.

**Comment by peterstadler** [comment]
Sorry, I fail to see the faulty behaviour in the current dev branch. E.g. the example at https://jenkins.tei-c.org/view/TEI%20dev/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-div4.html has a proper link to the bibliography. What am I missing?

**Comment by sydb** [comment]
IIRC the faulty behavior was not in the dev branch, but in the iss516 branch, and has been fixed there.
