### ISSUE TITLE
How to add Author tag to the top when using html.xsl

### ISSUE THREAD

**Issue by CJohnno77** [TEIC/Stylesheets#530]
I am using `html.xsl` to convert TEI XML to HTML.  What do I need to do to add the Author(s) to the top of the document just below the Title.  I would like to add the Author(s) as an `<h2>` element below the `<h1>` Title.

I can see the Author(s) are found at `/TEI/teiHeader/fileDesc/titleStmt/author` in the XML.  What parameter do I need to add to my `to.xsl` file?

**Comment by sydb** [comment]
Well, according to [this documentation](https://tei-c.org/Vault/P5/4.0.0/doc/tei-xsl/#parameters), there is a `$showTitleAuthor` parameter which defaults to `false`. We (@martindholmes and I) have figured out that if you have a `…/front/titlePage/`, this parameter (and most all the metadata) is ignored.

Note that there are instructions in that documentation for setting parameters via some not too old (I hope) version of oXygen. If you want to use Saxon on the commandline you could issue
~~~bash
java -jar saxon10he.jar -xsl:/path/to/TEIStylesheets/html/html.xsl -s:/path/to/input.xml -o:/path/to/output.html  showTitleAuthor=true
~~~
Note that, depending on your shell, you may have to provide absolute paths to the input & output.

Please let us know (here) whether this works for you or not. If we don’t hear from you by 2022-01-14 we will close the ticket.
