### ISSUE TITLE
how to remove bullet points from 'simple' list using html.xsl

### ISSUE THREAD

**Issue by CJohnno77** [TEIC/Stylesheets#534]
I am using `html.xsl` on an `.xml` file which has lists of type 'simple': eg. `<list type="simple">`

The items of these lists are coming out as `<ul class="simple">` in the resulting HTML, which display with bullet points.

Is there a way to get `simple` lists to not have the bullet points?  Is there a parameter I can set in the XSL?

**Comment by peterstadler** [comment]
transferred to Stylesheets repo (from TEIC/TEI) per ticket triage with @sabineseifert since most of the discussion is related to Stylesheets and not Guidelines.

**Comment by martindholmes** [comment]
Fix added in commit d67c9512.
