### ISSUE TITLE
To what should relative $cssInlineFiles be relative to?

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#538]
According to the last entry in the CSS-related parameter table in [the documentation](https://tei-c.org/release/doc/tei-xsl/#index.xml-body.1_div.6_div.8_div.1), the `$cssInlineFiles` parameter should be a URI that points to a CSS file. (The contents of this file get copied into a `<style>` element in the output of profiles/default/html5/to.xsl.)

If I provide a relative URI (either with or without a leading `./`), it looks for a CSS file relative to the Stylesheets/html/ directory, not to either the input document directory (which is what I expected at first) nor to the XSLT file’s directory (which is profiles/default/html5/).

I do not think this is the right behavior, but I do not know what is, either.

**Comment by sydb** [comment]
Stylesheets group thinks the expedient solution for now is to update the documentation so that it _tells_ the user to what directory the file is relative.
Sometime later we can try to make it relative to the user’s current directory, or if that is impossible, to the input document. (And change the documentation to match.)

**Comment by sydb** [comment]
@peterstadler at Stylesheets group meeting found the spot in documentation we need to change (Stylesheets/html/html_param.xsl l. 124).
@sydb to correctly check-in change we made during meeting.

**Comment by HelenaSabel** [comment]
Stylesheets Group checked that the improvement of the documentation was done correctly.
