### ISSUE TITLE
All-examples pages in the Guidelines should make link target language explicit

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#571]
When you click on Show all to see all examples in the Guidelines, you get a list of all examples from all languages for the target element. This is a good thing, but when users click on the link "back" to the specification page from an example which is not in the language of the Guidelines they're in, they will end up on a spec page for a different language, which may be confusing. Therefore Council (2022-09-11) believes that the language of the target page for each link should be shown next to the link, to give some warning if the user will wind up on  a page in a different language.

The first task is to discover where those links are created, to see whether this is actually a Stylesheets issue or if the examples pages  are generated using XSLT in the TEI repo.

**Comment by sydb** [comment]
See https://github.com/TEIC/TEI/issues/1933.

**Comment by sydb** [comment]
Assigned to @npcole to at least perform first task as described in last para of original post — find out at least repo, if not which file, we need to be looking at.

**Comment by HelenaSabel** [comment]
The Stylesheets Group worked on this issue today. After spending some time examining and debugging [this template](https://github.com/TEIC/Stylesheets/blob/dev/odds/guidelines.xsl#L284) of [odds/guidelines.xsl](https://github.com/TEIC/Stylesheets/blob/dev/odds/guidelines.xsl), we, or rather, @peterstadler, figured out  that the file we needed to modify was  [P5/Utilities/guidelines.xsl.model](https://github.com/TEIC/TEI/blob/dev/P5/Utilities/guidelines.xsl.model). 

We did this commit during the meeting which successfully adds the language of the exemplum when is different from the current one: https://github.com/TEIC/TEI/commit/b7b449fc0173bba59bb69db26aa3ca5120fc29d1

This ticket will be kept open until the next TEI Council meeting where we will evaluate whether it looks good enough before the next release or if further enhancements are urgent.

**Comment by sydb** [comment]
Council is happy with the result insofar as it is definitely an improvement. Maybe more improvement will be in order later, in which case another ticket can be opened.
