### ISSUE TITLE
bug in common function `tei:render-subscript`

### ISSUE THREAD

**Issue by bwbohl** [TEIC/Stylesheets#584]
https://github.com/TEIC/Stylesheets/blob/6dbb58c2fa458879bcf5dd19f9c8b3c392d25b89/common/functions.xsl#L295-L307

The `tei:render-subscript` function outputs `true` for `@rend` containing `sup`.

https://github.com/TEIC/Stylesheets/blob/6dbb58c2fa458879bcf5dd19f9c8b3c392d25b89/common/functions.xsl#L302

This obviously is a copy paste error from `tei:rend-superscript` and should read:

```xml
        <xsl:when test="ancestor-or-self::*[@rend][tei:match(@rend,'sub')]">true</xsl:when> 
```

**Comment by GusRiva** [comment]
Typo was corrected in #670
