### ISSUE TITLE
following values for structural @type

### ISSUE THREAD

**Issue by sebastianrahtz** [TEIC/Stylesheets#6]
there is an interesting structural typology at http://dfg-viewer.de/en/structural-data-set/; it is possible that the stylesheets should be aware of this in some way

**Comment by sydb** [comment]
If I understand this correctly, I’d say that if the Stylesheets should be aware of any possible values, it is the suggested values list in P5 they should be aware of. So until P5 is updated, there is nothing to do here.

**Comment by martindholmes** [comment]
@ebeshero and I believe this should just be closed. It appears merely to be suggesting that one random typology/ontology be adopted over the many others that presumably exist. We don't see any reason to prefer this over our current `@type` values.

**Comment by sydb** [comment]
Agreed.
