### ISSUE TITLE
The tag element is not properly processed

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/Stylesheets#602]
`tag` elements do not appear to be formatted properly in the HTML output (and possible others) — see the release notes for 4.1.0, for instance: https://tei-c.org/Vault/P5/current/doc/tei-p5-doc/readme-4.1.0.html.

Anything with a `<tag>` should, at the very least, get a `<` before and a `>` after (like `<gi>`)

**Comment by peterstadler** [comment]
I believe this to be a duplicate of #567?

**Comment by joeytakeda** [comment]
Ah it is too! Thanks @peterstadler — We found this during the release, and so I made the ticket without due diligence :-)
