### ISSUE TITLE
Clarify if a user should expect a ODD processor to perform base URI fixup

### ISSUE THREAD

**Issue by dmj** [TEIC/Stylesheets#624]
An ODD customization may include external schema component specifications with classRef, dataRef, elementRef, macroRef, or moduleRef. Suche an external specification may contain relative URI references. It is currently unspecified if a user can expect a processor to perform base URI fixup, i.e. changing the base URI property of the included specification such that relative URI references still resolve against the same base URI.

**Comment by sydb** [comment]
**Excellent** question.

The current ATOP position is that any external specification (e.g., an `<elementRef>` that has a `@source`) needs to point to an  assembled specification (in this case, an `<elementSpec>` that does _not_ have any `@source` attributes on `<*Ref>` elements within). An assembled ODD can be generated using the ATOP routine assemble_odd.xslt. Thus there would not be any URIs that would need to be resolved, so whether they would be resolved relative to to the `<elementRef>` or the `<elementSpec>` it refers to is irrelevant.

This is a planned limitation of ATOP about which we do not feel guilty as the current Stylesheets will not handle this sort of externality, and (to our knowledge) no one has ever requested it. If & when someone does, we could consider adding this capability to ATOP.
