### ISSUE TITLE
global <constraintSpec> elements in ODD aren't processed for HTML documentation

### ISSUE THREAD

**Issue by rvdb** [TEIC/Stylesheets#65]
When an ODD file's &lt;schemaSpec> element contains global &lt;constraintSpec> elements (that is, as direct children of &lt;schemaSpec>), those constraints aren't processed when generating HTML documentation, e.g.: 

```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0" 
  xmlns:sch="http://purl.oclc.org/dsdl/schematron" 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!-- ... -->
  <schemaSpec ident="jtei" start="TEI">
    <!-- ... -->
    <constraintSpec ident="hyphens" scheme="isoschematron">
      <constraint>
        <sch:rule context="text()">
          <sch:assert test="not(contains(., '--'))"> Double hyphens should not be used for dashes.
            Please use the EM Dash (U+2014) instead. </sch:assert>
        </sch:rule>
      </constraint>
    </constraintSpec>
    <!-- ... -->    
  </schemaSpec>
</TEI>

```
This &lt;constraintSpec> element isn't processed at all when generating HTML documentation.

It would be nice if the TEI stylesheets generating ODD documentation provided processing of &lt;constraintSpec> elements in some way. If the problem is that &lt;constraintSpec> can occur in too many unpredictable places, wouldn't it be possible to support a default case for global Schematron constraints (say, when they are expressed as direct children of &lt;schemaSpec>)?

**Comment by sebastianrahtz** [comment]
I have had a first pass at this, and its more or less in place. probably fastest if we progress this by testing and by reporting niggles back on this ticket until its fixed.

**Comment by sebastianrahtz** [comment]
I am closing this issue for now, as the base work is done.
