### ISSUE TITLE
unhelpful report from attempt to build PDF Guidelines

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#679]
Here's what I see at the end of my recent run of "make install" following an update of my local copy of TEI P5

BUILD: make PDF version of Guidelines
make pdf
make[1]: Entering directory '/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5'
check if XeLaTeX exist
/usr/bin/xelatex
java -jar Utilities/lib/saxon10he.jar -s:Utilities/guidelines-latex.xsl -xsl:Utilities/guidelines_model_2_executable.xslt -o:Utilities/guidelines.xsl XSL="/usr/share/xml/tei/stylesheet"
BUILD: build Lite version of Guidelines, then LaTeX version of Guidelines from Lite, then run to PDF using XeLaTeX
Make sure you have Junicode and Noto CJK fonts installed
ANT_OPTS="-Xss2m -Xmx752m -Djava.awt.headless=true" ant -q -lib Utilities/lib/saxon10he.jar -f antbuilder.xml -DXSL=/usr/share/xml/tei/stylesheet -DXELATEX=xelatex pdfonce
     [echo] make LaTeX and PDF

BUILD FAILED
/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5/antbuilder.xml:225: exec returned: 1

Total time: 1 minute 8 seconds
make[1]: *** [Makefile:145: pdf-init] Error 1
make[1]: Leaving directory '/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5'
make: *** [Makefile:275: dist-doc.stamp] Error 2

I used to be able to build a nice PDF version of the Guidelines, and I can certainly do other tei to pdf conversions, It's not at all clear from the foregoing what is going wrong

**Comment by sydb** [comment]
@lb42 — @HelenaSabel and I each tried to reproduce the error using the Docker environment, and in both cases our builds succeeded. (There is no point in my trying to `make install` on my local system directly, as I do not have `xelatex` installed, so I know it will fail.) I concede the point that “mnt/…/Public/TEI/P5/antbuilder.xml:225: exec returned: 1” is not very helpful, but am not sure what we could do about that. It looks like it is running `xelatex` on Guidelines.tex. I tried running that (in the Docker environment), too, and got (as you might expect) dozens or hundreds of messages about underfull bounding boxes, etc., but no errors.
Do you still have this problem?

**Comment by lb42** [comment]
Yup, I just  did: a git pull on my TEI/P5 directory, followed by a sudo make install and got the same result. 

I certainly have xelatex installed, also the Noto CJK fonts. Not sure that I  know what "Junicode" is but there's no font of that name installed. 

Here's the log again


BUILD: make PDF version of Guidelines
make pdf
make[1]: Entering directory '/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5'
check if XeLaTeX exist
/usr/bin/xelatex
java -jar Utilities/lib/saxon10he.jar -s:Utilities/guidelines-latex.xsl -xsl:Utilities/guidelines_model_2_executable.xslt -o:Utilities/guidelines.xsl XSL="/usr/share/xml/tei/stylesheet"
BUILD: build Lite version of Guidelines, then LaTeX version of Guidelines from Lite, then run to PDF using XeLaTeX
Make sure you have Junicode and Noto CJK fonts installed
ANT_OPTS="-Xss2m -Xmx752m -Djava.awt.headless=true" ant -q -lib Utilities/lib/saxon10he.jar -f antbuilder.xml -DXSL=/usr/share/xml/tei/stylesheet -DXELATEX=xelatex pdfonce
     [echo] make LaTeX and PDF

BUILD FAILED
/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5/antbuilder.xml:225: exec returned: 1

Total time: 1 minute 11 seconds
make[1]: *** [Makefile:145: pdf-init] Error 1
make[1]: Leaving directory '/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/TEI/P5'
make: *** [Makefile:275: dist-doc.stamp] Error 2
(base) lou@foxglove:~/Public/TEI/P5$

**Comment by lb42** [comment]
Aha, wait. Junicode *is* a font and it's not installed, and that's my problem!  There's a "missfont.log" telling me this in my P5 directory, but I was too lazy to go looking for it.  So you can close this if you like!

**Comment by lb42** [comment]
Just to confirm that "make pdf" seems to work now I have installed Junicode ttf fonts on my linux box. The typesetting of the text itself seems pretty good, but I haven't looked very closely. Not sure I like the way the spec pages are coming out now, but they have always been a nightmare to render.
