### ISSUE TITLE
ODD to Schematron conversion outputs only QuickFixes, no patterns

### ISSUE THREAD

**Issue by jjarosch** [TEIC/Stylesheets#702]
* TEI Stylesheets used: release 7.57.0 (cloned git repo)
* command line call: `bin/teitoschematron --odd tei_bkd.odd tei_bkd.sch`
* input ODD: https://gitlab.rlp.net/adwmainz/digicademy/bkd/correspondences/-/blob/main/schema/tei_bkd.odd
* output SCH: https://gitlab.rlp.net/adwmainz/digicademy/bkd/correspondences/-/blob/main/schema/tei_bkd.sch (this one is a couple of months old; running it today, it’s structurally identical except that it includes some deprecation warnings)
* run in Ubuntu 22.04.5

As the title says, the generated file entirely skips the patterns and only includes the quick fixes. Vaguely, this seems to point to this section being the cause or involved: https://github.com/TEIC/Stylesheets/blob/c07e8d630ad4cbfc5fd102a40971ac7a863f09ac/odds/extract-isosch.xsl#L311-L354

Using TEI Garage, we get patterns (but no quick fixes) out of the same ODD. I understand TEI Garage uses this stylesheet: https://github.com/TEIC/Stylesheets/blob/dev/odds/extract-sch.xsl

Am I doing something wrong? Are there command line parameters to pass to `extract-isosch.xsl`?

**Comment by sydb** [comment]
Thanks for the report. After poking a little, it seems like extract-isosch.xsl is doing the right thing — there are no patterns in English (they are in German), and by default (perhaps somewhat inappropriately) it looks for English. BUT when I specify German as the desired language `saxon -xsl:odds/extract-isosch.xsl -s:tei_bkd.odd lang=de > /tmp/tei_bkd.isosch` seems to work fine, but `bin/teitoschematron --lang=de --odd tei_bkd.odd /tmp/tei_bkd.isosch` still fails to process the constraints!
Looking into it now, but I suspect I will have to go before I figure this out today. (It is _not_ a problem with the shell script, it is sending the `de` to the ant just fine.) 

P.S. Note that we do not expect extract-isosch.xsl to work entirely properly directly on tei_bkd.odd as I tried above, it is intended to be run on the “compiled” ODD generated from tei_bkd.odd + P5.

**Comment by sydb** [comment]
So it looks to me at first blush like processed (or “compiled”) ODD is being created correctly, but the language is not being passed on to profiles/default/schematron/to.xsl when it is invoked. In turn, I am not sure it would pass the $lang on to extract-isosch.xsl even if it had it.

OK. After poking around a bit more it looks like adding
~~~xml
      <param name="lang" expression="${lang}" if="lang"/>
~~~
to the call to XSLT/trax in profiles/default/schematron/to.xsl (~line 31) fixes the problem and allows the language `de` to passed in appropriately.

So that would seem to be the immediate fix to this problem. (Any chance you can test that, @jjarosch? I will try to test it more and make a PR later this weekend.) But it still strikes me that if _every_ `<constraint>` is in German the routine ought to be smart enough to look for German by default. (Or at least generate a warning message, maybe?)

**Comment by jjarosch** [comment]
I’m not entirely sure I follow. When I change https://github.com/TEIC/Stylesheets/blob/dev/profiles/default/schematron/to.xsl like this:
```
<xsl:stylesheet 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    version="3.0">
   <param name="lang" expression="${lang}" if="lang"/>
    <!-- import base conversion style -->
    <xsl:import href="../../../odds/extract-isosch.xsl"/>

  <doc xmlns="http://www.oxygenxml.com/ns/doc/xsl" scope="stylesheet" type="stylesheet">
```
– nothing changes. But is that what you meant in the first place?

Regarding general behaviour:

A message like “No language set, defaulting to en” might be a simple first prompt for users to realise that the `lang` parameter is needed. The slightly more elaborate thing to display might be “no constraints matching the selected language (en) found”.

A second thing that stands out to me is that the quick fixes are not checked for their language.

**Comment by sydb** [comment]
Sorry, that was my fault, I listed the wrong file for the `<param>` addition. Should have been schematron/build-to.xml, roughly line 31.

Yeah, I think your version of the message is mildly better, but we can worry about detailed wording later. The bigger question is whether we should presume that if there is no identifiable language for any constraints, they are all in English.

> … the quick fixes are not checked for their language.

Oh bloody BLEEP, you are absolutely right. I will be gone most of today (doctor’s appointment) but hope to work on this ticket a bit tonight.

**Comment by jjarosch** [comment]
Aah, yes, thanks, [there](https://github.com/TEIC/Stylesheets/blob/dev/schematron/build-to.xml)’s the trax you mentioned. This
```
    <xslt processor="trax" force="yes" style="${profiledir}/${profile}/schematron/to.xsl" in="${inputFile}.processedodd" out="${outputFile}">
      <factory name="net.sf.saxon.TransformerFactoryImpl"/>
      <param name="lang" expression="${lang}" if="lang"/>
    </xslt>
```
works for me – it generates a lot of constraints and the schema file works!

Will the `lang` parameter also be needed for the `notodd` target in lines 35–39?

**Comment by sydb** [comment]
Oh, not sure.
Gotta go now, but will try to take a look in ~6 hours, give or take a few, when I get back to this. (Plan to change all those keys to be based on lang, not '1'. That should do the trick. :-)

**Comment by jjarosch** [comment]
There’s no hurry on my end! Good luck at your appointment, and thanks again!

**Comment by sydb** [comment]
@jjarosch — If you are up to it please checkout the sydb_702_extract_schematron branch and test your ODD there. (And feel free to comment on the PR (#704) rather than here, if that seems to make more sense.)

**Comment by jjarosch** [comment]
It’s all looking good, it does what I expect. My colleague who wrote most of the schematron rules in our ODD had a look as well and didn’t spot any ‘semantic’ problems from the transformation.

So this patch will resolve my issue. Thanks again!!

**Comment by HelenaSabel** [comment]
Fixed via https://github.com/TEIC/Stylesheets/pull/704. Please be aware of https://github.com/TEIC/TEI/issues/2608
