### ISSUE TITLE
FO line-height configuration

### ISSUE THREAD

**Issue by bwbohl** [TEIC/Stylesheets#73]
Currently transforming TEI to FO and PDF doesn't allow specifying line-height. I consider implementing corresponding independent parameters for front, body and back.
If I set the line-height attribute in the corresponding page-sequences this will affect all content in the corresponding fo:flow, including footnotes. Besides footnotes cit[@rend='block'] might be another case where increased line-height is rather unwanted.
So alternatively:
- line-heights could either be set on div or p elements (excluding such things as footnotes and citations), or
- other parameters might be introduced to configure line-height for footnotes and cit[@rend='block'] respectively

Any thoughts or opinions?

**Comment by bwbohl** [comment]
lists of course might be considered differently, too!

**Comment by sebastianrahtz** [comment]
that's hard. my inclination is to do by inclusion, not exclusion. so apply
it to contexts where you know it makes sense,
eg on <p>, and add to other elements as you see the need.

On 12 January 2015 at 10:21, Benjamin W. Bohl <notifications@github.com>
wrote:

> Currently transforming TEI to FO and PDF doesn't allow specifying
> line-height. I consider implementing corresponding independent parameters
> for front, body and back.
> If I set the line-height attribute in the corresponding page-sequences
> this will affect all content in the corresponding fo:flow, including
> footnotes. Besides footnotes cit[@rend <https://github.com/rend>='block']
> might be another case where increased line-height is rather unwanted.
> So alternatively:
>
>    - line-heights could either be set on div or p elements (excluding
>    such things as footnotes and citations), or
>    - other parameters might be introduced to configure line-height for
>    footnotes and cit[@rend <https://github.com/rend>='block'] respectively
>
> Any thoughts or opinions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/73>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
