### ISSUE TITLE
java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl

### ISSUE THREAD

**Issue by ElCep** [TEIC/Stylesheets#77]
Dear all, 
I would try to convert tei to latex with ... `teitilatex` . I work on fedora with a texlive installation. After run `make` ... and install `jing` and `saxon` and re-run makeI have this issu 

     BUILD FAILED
    /home/delaye/github/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException:  net.sf.saxon.TransformerFactoryImpl
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

    Total time: 0 seconds
    make[1]: *** [test-from-docx] Erreur 1
    make[1] : on quitte le répertoire « /home/delaye/github/Stylesheets/Test »
    make: *** [test] Erreur 2

Some one can lead me in the installation part ? Or is there a manual ?

thank you and best regards

E.

**Comment by sebastianrahtz** [comment]
can you show the result of adding  --debug when you call teitilatex?

ie

teitolatex --debug test.xml test.tex

your error message appears to indicate that it can't find Saxon, but thats
puzzling as saxon9he.jar is part of the
file distribution.

sebastian

On 15 January 2015 at 23:15, Etienne DELAY <notifications@github.com> wrote:

> Dear all,
> I would try to convert tei to latex with ... teitilatex . I work on
> fedora with a texlive installation. After run make ... and install jing
> and saxon and re-run makeI have this issu
>
>  BUILD FAILED
> /home/delaye/github/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException:  net.sf.saxon.TransformerFactoryImpl
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>     at java.lang.Class.forName0(Native Method)
>     at java.lang.Class.forName(Class.java:191)
>     at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
>     at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
>     at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
>     at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
>     at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
>     at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
>     at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
>     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
>     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
>     at org.apache.tools.ant.Task.perform(Task.java:348)
>     at org.apache.tools.ant.Target.execute(Target.java:435)
>     at org.apache.tools.ant.Target.performTasks(Target.java:456)
>     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
>     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
>     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
>     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
>     at org.apache.tools.ant.Main.runBuild(Main.java:851)
>     at org.apache.tools.ant.Main.startAnt(Main.java:235)
>     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
>     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
>
> Total time: 0 seconds
> make[1]: *** [test-from-docx] Erreur 1
> make[1] : on quitte le répertoire « /home/delaye/github/Stylesheets/Test »
> make: *** [test] Erreur 2
>
> Some one can lead me in the installation part ? Or is there a manual ?
>
> thank you and best regards
>
> E.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/77>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by ElCep** [comment]
Thank you Sebastian, 
but when i try `teitolatex --debug ~/Téléchargements/test.xml  ~/test.tex` it doesn't work ... 
     bash: teitolatex : commande introuvable
It seems to be normal (I guess) if the make procedure doesn't end.

**Comment by sebastianrahtz** [comment]
What command do you use then ?

**Comment by ElCep** [comment]
nothing :-S if it doesn't work I need to finish the makefile no? But maybe I don't understand what's going on in the makefile...

**Comment by sebastianrahtz** [comment]
hmm.

I am a bit lost now. Tell me what stages you have gone through.

Sebastian

On 16 January 2015 at 20:53, Etienne DELAY <notifications@github.com> wrote:

> nothing :-S if it doesn't work I need to finish the makefile no? But maybe
> I don't understand what's going on in the makefile...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/77#issuecomment-70320397>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by ElCep** [comment]
I would like to convert tei to latex so I have do

     git clone git@github.com:TEIC/Stylesheets.git

the readme.md is not so explicit. I have seen a `Makefile` so I'm trying to run

      make

But in fact I don't know if I need to do that. When I try to run teitolatex from `bin\teitolatex` I have this message : `command not found `

**Comment by sebastianrahtz** [comment]
bin\teitolatex  isn't a valid Linux syntax. you mean bin/teitolatex,
assuming you are not trying to use this under Windows.

if you run "sudo make install" it would try to install the commands in
standard places on your system.

Sebastian


On 16 January 2015 at 21:25, Etienne DELAY <notifications@github.com> wrote:

> I would like to convert tei to latex so I have do
>
>  git clone git@github.com:TEIC/Stylesheets.git
>
> the readme.md is not so explicit. I have seen a Makefile so I'm trying to
> run
>
>   make
>
> But in fact I don't know if I need to do that. When I try to run
> teitolatex from bin\teitolatex I have this message : command not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/77#issuecomment-70324694>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by ElCep** [comment]
Ok :-S ... it work .... I have forgotten it work with  

      ./teitolatex ~/Téléchargements/test.xml ~/test.tex

Now I need to understand some tweaks :-p
Thank you Sebastian
