### ISSUE TITLE
tcp/tcp2tei.xsl should consider reversing order of revisionDesc

### ISSUE THREAD

**Issue by jamescummings** [TEIC/Stylesheets#78]
The revisionDesc entries in the TCP converted texts seems to have them in chronological order whereas the TEI Guidelines note that "Conventionally change elements should be given in reverse date order, with the most recent change at the start of the list."  While this is clearly a minor thing, perhaps the order should be reversed in the TCP conversion stylesheet for the next time we run a full conversion?

**Comment by PFSchaffner** [comment]
Frankly it never occurred to me that changes would ever be recorded
*other* than in chronological order. Certainly they are so recorded 
in the tracking database from which this info is derived; and likewise
in the MARC 583 'action notes' in which it is stored. And even the
change notes in our temporary headers are always in chronological order.

Never considering that there could be any other way, it never 
occurred to me as a question, and therefore I never saw the note
that James refers to. 

"Conventionally" is a bit weasily. Whose?

pfs



On Fri, Jan 16, 2015, at 12:05, James Cummings wrote:
> The revisionDesc entries in the TCP converted texts seems to have them in
> chronological order whereas the TEI Guidelines note that "Conventionally
> change elements should be given in reverse date order, with the most
> recent change at the start of the list."  While this is clearly a minor
> thing, perhaps the order should be reversed in the TCP conversion
> stylesheet for the next time we run a full conversion?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TEIC/Stylesheets/issues/78
-- 
Paul Schaffner  Digital Library Production Service
PFSchaffner@umich.edu | http://www.umich.edu/~pfs/

**Comment by lb42** [comment]
There are two possible chronological orderings  -- most recent first, 
and most ancient first. Most recent first is what the TEI has 
recommended ever since I noticed that some crazy people were doing it 
most ancient first -- way back in P2 days if memory serves! Surely it's 
better to see first the most recent change in a document?

Maybe this is one of things like date formats ...

**Comment by PFSchaffner** [comment]
I suspect it has to do with which unconscious analogies one is
employing. If you're thinking of release notes or Wikipedia revision
histories, you think 'most recent first'; if you think of DNB entries
or preservation and provenance notes, one is not likely to think it
natural to say
"died in 1940, while governor general of Canada; before that he
was a director of Reuters; and before THAT head of the British
Propaganda office, following on his earlier work in South Africa,
where he went after finishing his degree at Oxford."

FWIW, the immediate source (the MARC 583 notes) do not, so
far as I can tell,  specify an order, but do contain a field in 
which one can do so (a sequence number). All of the examples
that I can find proceed from oldest to newest: "Received --
acknowledged -- catalogued -- bound -- shelved -- rebound
-- damaged -- repaired" etc.).  FWIW.

pfs

On Fri, Jan 16, 2015, at 13:38, Lou wrote:
> There are two possible chronological orderings  -- most recent first, 
> and most ancient first. Most recent first is what the TEI has 
> recommended ever since I noticed that some crazy people were doing it 
> most ancient first -- way back in P2 days if memory serves! Surely it's 
> better to see first the most recent change in a document?
> 
> Maybe this is one of things like date formats ...
> 
> 
> 
> 
> On 16/01/15 18:32, Paul Schaffner wrote:
> > Frankly it never occurred to me that changes would ever be recorded
> > *other* than in chronological order. Certainly they are so recorded
> > in the tracking database from which this info is derived; and likewise
> > in the MARC 583 'action notes' in which it is stored. And even the
> > change notes in our temporary headers are always in chronological order.
> >
> > Never considering that there could be any other way, it never
> > occurred to me as a question, and therefore I never saw the note
> > that James refers to.
> >
> > "Conventionally" is a bit weasily. Whose?
> >
> > pfs
> >
> >
> >
> > On Fri, Jan 16, 2015, at 12:05, James Cummings wrote:
> > > The revisionDesc entries in the TCP converted texts seems to have 
> > them in
> > > chronological order whereas the TEI Guidelines note that "Conventionally
> > > change elements should be given in reverse date order, with the most
> > > recent change at the start of the list." While this is clearly a minor
> > > thing, perhaps the order should be reversed in the TCP conversion
> > > stylesheet for the next time we run a full conversion?
> > >
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/TEIC/Stylesheets/issues/78
> > -- 
> > Paul Schaffner Digital Library Production Service
> > PFSchaffner@umich.edu | http://www.umich.edu/~pfs/
> >
> > —
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/TEIC/Stylesheets/issues/78#issuecomment-70299204>.
> >
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TEIC/Stylesheets/issues/78#issuecomment-70300200
-- 
Paul Schaffner  Digital Library Production Service
PFSchaffner@umich.edu | http://www.umich.edu/~pfs/

**Comment by martindholmes** [comment]
I like most recent first, and I was glad to find it's the recommended way. But I have to enforce it with Schematron in my projects; other people obviously find it unintuitive.

**Comment by sebastianrahtz** [comment]
I am marginally with Paul, ie seeing it as a history in first - last order

Not sure why anyone cares. I would use version control myself for a real project.

**Comment by martindholmes** [comment]
Yes, I despair of revisionDesc ever being properly maintained. I tend to add entries in it only when I'm making mechanical changes on a large scale. Anything that a human has to remember to do is doomed, I think. And if your really did maintain it, it would be larger than the rest of the document in a couple of years.

**Comment by PFSchaffner** [comment]
That's (almost) exactly how we use it, for exactly your reasons -- i.e.
to record the major steps in the file's history to the extent that those
correspond to major nodes in the overall workflow, regardless of whether
those are manually or mechanically performed. Viz.,

ASSIGNED FOR KEYING -- to whom -- when ( -- version of specs )
RECEIVED FROM KEYERS -- when
SAMPLED/PROOFED -- by whom -- where -- when -- using which criteria --
what verdict?
REVIEWED/EDITED -- by whom -- where -- when
META-REVIEWED and DELIVERED -- by whom (me) -- when
PLACED ONLINE -- when

Some are repeatable, e.g. if PROOFED yields REJECTED, then the
file may well again be RECEIVED and again be PROOFED.

And just to be clear, I don't actually care about the order -- was
just embarrassed that I never even thought about it, just assumed.

pfs



On Fri, Jan 16, 2015, at 17:07, Martin Holmes wrote:
> Yes, I despair of revisionDesc ever being properly maintained. I tend to
> add entries in it only when I'm making mechanical changes on a large
> scale. Anything that a human has to remember to do is doomed, I think.
> And if your really did maintain it, it would be larger than the rest of
> the document in a couple of years.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TEIC/Stylesheets/issues/78#issuecomment-70330473
-- 
Paul Schaffner  Digital Library Production Service
PFSchaffner@umich.edu | http://www.umich.edu/~pfs/

**Comment by jamescummings** [comment]
Ok, closing issue then since there isn't an easy resolution that all of you agree with.

**Comment by lb42** [comment]
Of the responses to this proposal:

1 (mine) entirely agrees with the proposed change
1 (Martin's) thinks that using revisionDesc is rubbish anyway
1 (Sebastian's) expresses some "marginal" support for the current ordering
1 (Paul's) says he hasn't considered the possibility that the current 
order is wrong "And just to be clear, I don't actually care about the order"

So if there is a consensus here it is that most people don't care about 
the ordering.

But I do care (quite a lot) that a flagship project like this should not 
casually ignore what the TEI currently recommends, rightly or wrongly.

So I think the issue should be reopened.

**Comment by jamescummings** [comment]
reopening.

**Comment by sebastianrahtz** [comment]
There is another way to resolve the problem, which is to remove that recommendation from the TEI. I have submitted a bug report accordingly, suggesting that in this case the TEI is going the wrong way by recommending that order of change within revisionDesc is the way to go, rather than dating changes.

We may note that the TEI also says "No significant change should be made in any TEI-conformant file without corresponding entries being made in the change log", which is an even stronger statement than what we discuss here, and which is going to be widely ignored by anyone using a version control system.

We might reflect on the fact that the TEI Guidelines source does not use revisionDesc or change in the mandated manner. its `<revisionDesc>` is in fact highly misleading

**Comment by martindholmes** [comment]
I think I've been misrepresented. My first statement was "I like most recent first, and I was glad to find it's the recommended way." So I come down on Lou's side.

**Comment by lb42** [comment]
Apologies for having misrepresented Martin's views, especially if they agree with mine.

**Comment by sebastianrahtz** [comment]
since the TCP texts dont use regularized dates, do people think this request is actually feasible?

**Comment by PFSchaffner** [comment]
To be exact, revision notes do use regularized W3C/ISO dates but at present place those in the contents of the date tag, rather than in a when or when-iso attribute. I.e., they read &lt;date&gt;2008-10&lt;/date&gt; rather than &lt;date when="2008-10"/&gt;. This was simply a transformation decision that could easily be changed. The immediate ancestor is MARCxml:
&lt;marc:datafield tag="583" ind1=" " ind2=" "&gt;
&lt;marc:subfield code="a"&gt;Batch review (QC) and XML conversion&lt;/marc:subfield&gt;
&lt;marc:subfield code="b"&gt;DDAT&lt;/marc:subfield&gt;
&lt;marc:subfield code="c"&gt;2014-03&lt;/marc:subfield&gt;
and the next generation back, plain old MARC:
=583  \\$aBatch review (QC) and XML conversion$bDDAT$c2014-03

**Comment by sebastianrahtz** [comment]
ah, so i can trust them to be normalized? one will never see 2005-?06
or 2005-06/07?

On 26 June 2015 at 14:58, Paul Schaffner <notifications@github.com> wrote:

> To be exact, revision notes do use regularized W3C/ISO dates but at
> present place those in the contents of the date tag, rather than in a when
> or when-iso attribute. I.e., they read <date>2008-10</date> rather than
> <date when="2008-10"/>. This was simply a transformation decision that
> could easily be changed. The immediate ancestor is MARCxml:
> <marc:datafield tag="583" ind1=" " ind2=" ">
> <marc:subfield code="a">Batch review (QC) and XML
> conversion</marc:subfield>
> <marc:subfield code="b">DDAT</marc:subfield>
> <marc:subfield code="c">2014-03</marc:subfield>
> and the next generation back, plain old MARC:
> =583 \$aBatch review (QC) and XML conversion$bDDAT$c2014-03
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/78#issuecomment-115698820>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by PFSchaffner** [comment]
Trying to think of exceptions. It is *possible* that some early files, before montly tracking began in earnest, were dated "2000-00" which makes no sense except as an equivalent for "2000", formatted with the "-oo" in order to make it regex-compatible with real dates. I'll go look.

**Comment by PFSchaffner** [comment]
When data is not controlled, there are *always exceptions.* So: in EEBO to date, there are 244,533 revision dates (in the MARC). Of these, 1,257 take the anomalous form "yyyy-00" (which semantically = "yyyy"). And two mistakes: "2008-7" and "2001pr-01", the latter apparently a data corruption of some kind. The remainder all take the form (20[01]-0[123456789])|(20[01]-1[012]). I haven't checked ECCO or Evans.

**Comment by PFSchaffner** [comment]
Make that "2010lpr-01"

**Comment by sebastianrahtz** [comment]
so sort select="concat(substring(.,4),substring-after(.,'-')) would do it....

**Comment by jamescummings** [comment]
Since prose of the Guidelines has been updated, and it turns out that _if_ there is dateCreated and dateUpdated in TCP it puts them in updated then created order (see https://github.com/TEIC/Stylesheets/blob/dev/tcp/tcp2tei.xsl#L2067) closing this ticket unless someone feels strongly.
