### ISSUE TITLE
ODD processing anomaly

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#80]
Changing the valList for an attribute inherited from a TEI attribute class is possible only if the element concerned is in the TEI name space. Since TEI attributes are not namespaced, this seems like a mistake.

**Comment by peterstadler** [comment]
for a test case see https://github.com/TEI-Correspondence-SIG/correspDesc/blob/master/odd/proposal.xml

**Comment by sebastianrahtz** [comment]
this is unrelated, I think, to the external namespace. If I take out the
ns=, it still doesn't work. But I can't test your example
cos its wiped out in the email.

Sebastian

**Comment by sebastianrahtz** [comment]
I don't think the report is accurate. I believe that what you have found is that you can't add a new element and at the same time modify it. Which is a bit odd, I agree.

**Comment by sebastianrahtz** [comment]
I have committed a change to odd2odd.xsl which fixes this error. The test suite does not show an anomaly so far.

**Comment by lb42** [comment]
Yes sorry I was prevented from including  my nice clean example by my ignorance of markdown syntax. But your explanation sounds entirely plausible.




Sent from my Samsung Galaxy Tab®|PRO


-------- Original message --------
From: Sebastian Rahtz
Date:01/30/2015 20:04 (GMT+00:00)
To: TEIC/Stylesheets
Cc: Lou Burnard
Subject: Re: [Stylesheets] ODD processing anomaly (#80)

this is unrelated, I think, to the external namespace. If I take out the
ns=, it still doesn't work. But I can't test your example
cos its wiped out in the email.

Sebastian
