### ISSUE TITLE
&lt;affiliation> element not properly handled by  teitolatex

### ISSUE THREAD

**Issue by lb42** [TEIC/Stylesheets#86]
Following recommendations of the jtei package, I have a title statement like this:
````
     <titleStmt>
            <title type="main">How many standards do we need to model reality?</title>
            <author>
              <name><forename>Lou</forename>
                  <surname>Burnard</surname></name>
               <affiliation>Lou Burnard Consulting</affiliation> 
               <email>lou.burnard@retired.ox.ac.uk</email>
            </author>
         </titleStmt>
````
This generates the following in my Latex file:
````
\usepackage[pdftitle={How many standards do we need to model reality?},
 pdfauthor={ {\name  Lou Burnard} \mbox{}\\ Lou Burnard Consulting }]{hyperref}
\hyperbaseurl{}

...

\author{ {\name  Lou Burnard} \mbox{}\\ Lou Burnard Consulting }\makeatletter 
```
which upsets xetex.  The upset takes the form of going into a tight loop, soaking up 100% of my cpu and not saying anything at all, except in the log which after much hand waving says
```
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.
```

Alas, not a good decision. Removing the &lt;affiliation> element works fine, of course, but the JTEI schema requires it to be there.

**Comment by sebastianrahtz** [comment]
At first blush, I can't replicate this by changing elements in the <titleStmt>, which I assume is where you are. Can you provide a test file?

**Comment by lb42** [comment]
On 15/03/15 14:46, Sebastian Rahtz wrote:
>
> At first blush, I can't replicate this by changing elements in the , 
> which I assume is where you are. Can you provide a test file?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TEIC/Stylesheets/issues/86#issuecomment-81053321>.
>

Here's my test file.

**Comment by lb42** [comment]
Sure can, but this interface doesnt seem to offer any way of sending it to you except as an image. So it's in your email.

**Comment by sebastianrahtz** [comment]
The test file doesn't correspond to your report. you have got the affiliation and the email inside the `<name>` in the test file, but outside in the bug report. Sigh.

**Comment by lb42** [comment]
Sorry... that was one of many things I tried. But moving it outside the name doesn't affect the issue.




Sent from my Samsung Galaxy Tab®|PRO


-------- Original message --------
From: Sebastian Rahtz
Date:03/15/2015 16:02 (GMT+00:00)
To: TEIC/Stylesheets
Cc: Lou Burnard
Subject: Re: [Stylesheets] <affiliation> element not properly handled by teitolatex (#86)


The test file doesn't correspond to your report. you have got the affiliation and the email inside the <name> in the test file, but outside in the bug report. Sigh.

**Comment by lb42** [comment]
On 15/03/15 16:02, Sebastian Rahtz wrote:
>
> The test file doesn't correspond to your report. you have got the 
> affiliation and the email inside the |<name>| in the test file, but 
> outside in the bug report. Sigh.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TEIC/Stylesheets/issues/86#issuecomment-81127052>.
>

so try this one...

**Comment by sebastianrahtz** [comment]
changes pushed to Github should do the right thing now, inside or out.

**Comment by lb42** [comment]
On 15/03/15 18:56, Sebastian Rahtz wrote:
>
> changes pushed to Github should do the right thing now, inside or out.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TEIC/Stylesheets/issues/86#issuecomment-81197170>.
>

Well, this does the right thing in that it does not now loop forever 
without returning any results; on the other hand it does not do the 
right thing in that the PDF generated contains neither email address nor 
affiliation.
