### ISSUE TITLE
Flow chart conversion issue

### ISSUE THREAD

**Issue by dhalapathy** [TEIC/Stylesheets#97]
While the conversion from word 2014 to xhtml (includes flow chart), we didn't got flowchart. But the text in flow chart has shown alone.

**Comment by sebastianrahtz** [comment]
Can you supply a test file, please?

I suspect the the flow chart uses Microsoft's proprietary drawing markup language, which it is not practical to translate.

**Comment by dhalapathy** [comment]
PFA the sample. Let me know anything unclear.

Regards
Dhalapathy

**Comment by sebastianrahtz** [comment]
Sorry, I cannot see any attachment. at
https://github.com/TEIC/Stylesheets/issues/97#issuecomment-93946960

On 17 April 2015 at 12:14, dhalapathy <notifications@github.com> wrote:

> PFA the sample. Let me know anything unclear.
>
> Regards
> Dhalapathy
>
> On Fri, Apr 17, 2015 at 2:25 PM, Sebastian Rahtz <notifications@github.com
> >
> wrote:
>
> > Can you supply a test file, please?
> >
> > I suspect the the flow chart uses Microsoft's proprietary drawing markup
> > language, which it is not practical to translate.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/TEIC/Stylesheets/issues/97#issuecomment-93946960>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/97#issuecomment-93966957>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by dhalapathy** [comment]
https://drive.google.com/open?id=0Bzjf1_7QDyjWeGlaMVVMeVp4WE0&authuser=0

**Comment by sebastianrahtz** [comment]
I had a look at the file. As  I suspected, the flow chart uses Microsoft's drawingML language which will not be at all easy to convert. Not hard to add the code in, if someone contributes a transformation

**Comment by sebastianrahtz** [comment]
I am closing this for now. I dont see much likelihood of my working on it, I am afraid.
