### ISSUE TITLE
Lines of table are missing in some instance

### ISSUE THREAD

**Issue by dhalapathy** [TEIC/Stylesheets#98]
Belo are Sample html only. i missed docx file
https://drive.google.com/open?id=0Bzjf1_7QDyjWOWdMNXdzelIyUkE&authuser=0

**Comment by sebastianrahtz** [comment]
I am not sure what you want me to look at here. How can I tell which lines of a table are missing?

**Comment by dhalapathy** [comment]
<td style="border: .. is missing for last Table.

**Comment by sebastianrahtz** [comment]
I can't do anything about this, I am afraid, without seeing the source.

**Comment by sebastianrahtz** [comment]
closed  due to inactivuty
